### PR TITLE
fix broken links (from link checking report tool testing)

### PR DESCRIPTION
**Pull request by RichieEscarez**
contributes to fixing items in #1750

/cc @adrcunha  @eallred-google 

related (for v0.10): #1974

### CODE REVIEW

**Comment by adrcunha** [comment]
Ignoring the SSL and non-parsable URLs, are these other errors from the presubmit test relevant?

```
community/samples/README.md
	ERROR	../../../docs/samples/
		Stat ../docs/samples: no such file or directory
	ERROR	../../contributing/DOCS-CONTRIBUTING.md
		Stat contributing/DOCS-CONTRIBUTING.md: no such file or directory
community/samples/serving/helloworld-dart/README.md
	ERROR	www.dartlang.org
		Stat community/samples/serving/helloworld-dart/www.dartlang.org: no such file or directory
docs/README.md
	ERROR	../contributing/CONTRIBUTING.md
		Stat contributing/CONTRIBUTING.md: no such file or directory
docs/eventing/samples/kafka/channel/README.md
	ERROR	../../channels/default-channels.md
		Stat docs/eventing/samples/channels/default-channels.md: no such file or directory
docs/install/README.md
	ERROR	./knative-custom-install.md
		Stat docs/install/knative-custom-install.md: no such file or directory
docs/install/installing-istio.md
	ERROR	./knative-with-gke.md
		Stat docs/install/knative-with-gke.md: no such file or directory
```

**Comment by RichieEscarez** [comment]
The '/contributing/' ones are a different problem that I'm working on but I'll have to verify the others.

**Comment by RichieEscarez** [comment]
All markdown link errors resolved (so no 404s viewing/using these pages from within GitHub repo), minus the inprogress fixes for `.../contributing/...` related pages. [I looks like I skipped over these during the first pass because on the site, all these links resolved to the right place.]

**Pull request merged**
