### PR TITLE
Added rollout & time-based in words list, made the changes(roll-out to rollout) in some files  (#3997)

### LINKED ISSUE #3997: Style Guide: Add rollout and time-based to the word list for docs contributors
Add "rollout" (not roll-out) and "time-based" (not time based) to the word list.
Follow up from #3990

### PR DESCRIPTION
**Pull request by soham283**
"Fixes #3997" 
- changed roll-out -> rollout in(both admin and developer directory)rolling-out-latest-revision.md
- Added the rollout  & time-based in wordlist
- Nothing Changed related to time-based in (both admin and developer directory)rolling-out-latest-revision.md (because already time based was changed to time-based )
-
-

### CODE REVIEW

**Comment by snneji** [comment]
Hi @soham283, PR looks good. 🙂 Could you fix the whitespace error, then I can get this merged. Thanks!

**Comment by abrennan89** [comment]
/lgtm
/approve

Thanks @soham283 ! 🙂

**Pull request merged**
