### PR TITLE
monitoring is now named knative-monitoring

### LINKED ISSUE #423: Openshift: Knative namespace change for monitoring
## Expected Behavior

Correct usage of the `knative-monitoring` namespace

## Actual Behavior

using the old name for the namespace (`monitoring`)

### PR DESCRIPTION
**Pull request by matzew**
Fixes #423

## Proposed Changes

* correct usage of the `knative-monitoring` namespace
* also added explicit watch for the `knative-build` pods, since they are installed by the `https://storage.googleapis.com/knative-releases/serving/latest/release-lite.yaml` file too....
*

### CODE REVIEW

**Comment by matzew** [comment]
@bbrowning little updates to the `knative-monitoring` namespace,

**Comment by bbrowning** [comment]
@matzew Thanks for the contribution! This is actually a duplicate of #416, which is on hold for now. The docs aren't yet versioned and this repo is intended to reference the latest release, which does not have the monitoring rename yet. I'm putting this on hold for now, given the above.

/hold

**Comment by bbrowning** [comment]
The other changes here, around waiting for knative-build to finish installing, are not a duplicate. I'll leave it up to you if you'd like to change the scope of this PR to just the latter or open a new one for that part.

**Comment by matzew** [comment]
@bbrowning Ok, I will close this, since #416 is more complete

however, the actualy `release-lite` file does already contain the new namespace - so, not exactly 100% why that change is on hold

**Comment by bbrowning** [comment]
Yes, that's a good catch! The installation instructions should reference an actual release and not latest. Handling doc versioning for both the most current release and the latest development head came up in the Contributor Working Group today. Hopefully we can clear up this confusion soon so it's clear what docs correspond to specific releases and which correspond to the `latest/release*.yaml`.

**Comment by matzew** [comment]
@bbrowning I've filed a new PR:

https://github.com/knative/docs/pull/431

**Pull request closed without merging**
