### PR TITLE
WIP: Fix integration tests

### PR DESCRIPTION
**Pull request by julz**
trying to figure out why the tests fail. Im guessing it may be because install_istio downloads the latest istio, and this recently became v1.10.

### CODE REVIEW

**Comment by julz** [comment]
@csantanapr did you intend to assign this? it's a WIP pr..

**Comment by julz** [comment]
Tracked it down and turns out to be https://github.com/knative-sandbox/net-istio/pull/686, so this should fix itself once that lands 🤞

**Comment by dprotaso** [comment]
might need to wait for the nightly

**Comment by julz** [comment]
yeah, thought this might be using main; oh well

**Comment by dprotaso** [comment]
I re-triggered it - I think it should appear running here in a few min
https://prow.knative.dev/?job=ci-knative-sandbox-net-istio-nightly-release

**Comment by dprotaso** [comment]
oh here we are: https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-sandbox-net-istio-nightly-release/1407421220160278528

**Comment by julz** [comment]
w00p \o/

/close

**Pull request closed without merging**
