### PR TITLE
Update set-up-a-local-knative-environment-with-kind.md

### PR DESCRIPTION
**Pull request by vatro**
Correcting two port typos.

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by ReToCode** [comment]
Thank you!

**Comment by psschwei** [comment]
This article was deprecated in #4982 and is no longer available from the main site.

**Comment by vatro** [comment]
I've found it useful as I was searching for info on how to switch `kourier` service to be of `NodePort` type instead of `LoadBalancer` while adding `Knative Serving` to my "office-lab" Kubernetes cluster (_bare-metal_).

**Pull request merged**
