### PR TITLE
Bumping Ambassador's feature state to beta with v0.18

### PR DESCRIPTION
**Pull request by alexgervais**
Bumping Ambassador's feature state to beta with v0.18

### CODE REVIEW

**Comment by tcnghia** [comment]
@nak3 can you please help review this?  thanks

**Comment by nak3** [comment]
@alexgervais As far as seeing the result of https://github.com/knative/serving/pull/9862, it seems that Ambassador is not stable. Is it possible to fix the errors?

**Comment by alexgervais** [comment]
@nak3 could you point me to somebody with experience with this test suite? It appears https://github.com/knative/serving/pull/9862 is failing, but so are all of the previous builds: https://prow.knative.dev/job-history/gs/knative-prow/pr-logs/directory/pull-knative-serving-ambassador-latest?buildId=1246242082381631488

On the Ambassador side, I've updated our integration tests to use Knative `v0.18` against our main branch. These tests are passing. We also have users running these recent versions in production.

**Comment by nak3** [comment]
@alexgervais sure, I can help it and found an issue. Could you please check https://github.com/knative/serving/pull/9862#issuecomment-716264859 ?

**Comment by abrennan89** [comment]
@nak3 @alexgervais any update on this one?

**Comment by abrennan89** [comment]
@alexgervais there's been no update on this for ~5 months; please open a new PR if these changes still need to be applied.

**Pull request closed without merging**
