### PR TITLE
Update Cloudevents Player deployment

### LINKED ISSUE #5485: Update Cloudevents Player repository and deployment
The maintained registry for the cloudevents player application is on Quay.io. Also the deployment can be simplified to just mention the broker name.

The screenshots can also be updated to the latest version

### PR DESCRIPTION
**Pull request by ruromero**
Fixes #5485

## Proposed Changes 

- Update registry to `quay.io/ruben/cloudevents-player:latest`
- Update screenshots to the latest version that includes extension attributes
- Describe the current configuration possibilities like the use just `BROKER_NAME` instead of the full `BROKER_URI`

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
Thanks for the fix!
/approve

for eventing signoff
/assign @pierDipi

**Comment by ruromero** [comment]
What is missing in this PR?

**Review by pierDipi — APPROVED** [review]
Thanks!

Sorry for getting back to this a little late, time is the only missing thing :)

/lgtm
/approve

**Comment by ruromero** [comment]
@pierDipi no worries. I thought I was missing something. Thanks a lot for your time.

**Pull request merged**
