### PR TITLE
Remove prometheus addon from Istio installation instructions

### PR DESCRIPTION
**Pull request by arturenault**
Fixes knative/serving#10221

## Proposed Changes 

- This addon is no longer supported in Istio 1.8. Remove it since it was disabled anyways.

### CODE REVIEW

**Review by nak3 — COMMENTED** [review]
@arturenault Could you also remove `cluster-local-gateway`?

**Review by nak3 — APPROVED** [review]
/lgtm

**Comment by arturenault** [comment]
@nak3 can I get an approval here? You're still assigned

I'm not totally clear on the difference between lgtm and approval yet, so let me know if I should ping someone else

**Comment by nak3** [comment]
/approve

But I think I don't have the permission to approve. @abrennan89 @tcnghia  could you please take a look?

/cc @abrennan89 @tcnghia

**Review by tcnghia — APPROVED** [review]
/lgtm

**Pull request merged**
