### PR TITLE
Fix all links to nightly releases

### PR DESCRIPTION
**Pull request by gvmw**
Fixes knative/eventing#5930

## Proposed Changes 

Nightly (a.k.a. development) releases are published to knative-nightly, and do not use the org name. This has not changed since 2019-05-17: https://github.com/knative/test-infra/blob/09f2b26361c825a1a110ce96a3c2657e3d5a23a9/scripts/release.sh#L96

Thank you @andersonsoares-tomtom for reporting this via https://github.com/knative/eventing/issues/5930

### CODE REVIEW

**Comment by gvmw** [comment]
This shows the problem (taken from https://knative.dev/development/eventing/broker/rabbitmq-broker/)

```sh
$ curl -I https://storage.googleapis.com/knative-sandbox-nightly/eventing-rabbitmq/latest/rabbitmq-broker.yaml
HTTP/2 404
x-guploader-uploadid: ADPycdsiyLDJnhTWo56YX9dWcbLAL8MAVSN7iNgQh3HWyKxiMUdkWgbJD36FRPBRFUU-xffExYuoYm13PzFcPInYJOwdXPmvAw
content-type: application/xml; charset=UTF-8
content-length: 133
date: Thu, 25 Nov 2021 11:19:49 GMT
expires: Thu, 25 Nov 2021 11:19:49 GMT
cache-control: private, max-age=0
server: UploadServer
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"

$ curl -I https://storage.googleapis.com/knative-nightly/eventing-rabbitmq/latest/rabbitmq-broker.yaml
HTTP/2 200
x-guploader-uploadid: ADPycdu31uThAddkmMuklFea-ee-THVk1imvUILLGogls8L6zK1PCYSJNdXq50n4f3kyJZsk9NEj1BVLSHThZad5xsT_Q1eoEg
expires: Thu, 25 Nov 2021 12:19:54 GMT
date: Thu, 25 Nov 2021 11:19:54 GMT
cache-control: public, max-age=3600
last-modified: Thu, 25 Nov 2021 09:54:49 GMT
etag: "a287dc5bf89b96188bb42418819bc3a8"
x-goog-generation: 1637834089814120
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 14420
content-type: application/octet-stream
x-goog-hash: crc32c=MEtNmA==
x-goog-hash: md5=oofcW/iblhiLtCQYgZvDqA==
x-goog-storage-class: MULTI_REGIONAL
accept-ranges: bytes
content-length: 14420
server: UploadServer
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

**Review by julz — APPROVED** [review]
Nice catch @andersonsoares-tomtom and @gvmw - thanks!

/lgtm
/approve

**Comment by gvmw** [comment]
Thanks for the prompt merge @julz!

When can we expect the https://knative.dev/development/eventing/broker/rabbitmq-broker/ links to be re-generated?

**Pull request merged**
