### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by SaaldjorMike**
Fixes #(issue-number)

## Proposed Changes

* 
* 
*

### CODE REVIEW

**Comment by samodell** [comment]
Thanks for your PR!

This is actually not a typo; the demo shows adding a new revision and at first not routing any traffic to it. In the next step, the traffic gets a 50-50 split.

**Comment by SaaldjorMike** [comment]
@samodell I understand that the next step changes it to 50/50 split, but to me it looks like that exact point in time (where the comment is) defines traffic is 100% for blue-green-demo-00001 and 0% for blue-green-demo-00002

**Comment by samodell** [comment]
@SaaldjorMike  Ah, yes! Apologies; I was reading this as adding the 5 instead of deleting it. Thanks for catching that.

**Comment by SaaldjorMike** [comment]
I signed it!

**Pull request merged**
