### PR TITLE
Document SASL and SSL support for Kafka Broker

### PR DESCRIPTION
**Pull request by pierDipi**
Part of #3202

## Proposed Changes 

- Document SASL and SSL support for Kafka Broker

/cc @abrennan89 @matzew @slinkydeveloper

### CODE REVIEW

**Comment by csantanapr** [comment]
Thank you @pierDipi for the contribution, I saw a lot of users asking how to configure kafka auth for both Source and Broker having this helps a lot 🙏

**Comment by csantanapr** [comment]
@pierDipi Support for this goes back to 0.17 (oldest documented version, 0.18 soon) right, so after merging this we would need to cherry-pick back to the other branches

**Comment by pierDipi** [comment]
@csantanapr this feature will be released in v0.21 and it's not available in any of the previous versions. 
However, the Broker implementation can be used when a previous version of Knative Eventing is installed.
For example, I can use Knative Eventing v0.18 and the Kafka Broker v0.21 without issues.
Perhaps should we clarify this aspect in our docs?

**Pull request merged**
