### PR TITLE
Bump the min k8s version to 1.15

### PR DESCRIPTION
**Pull request by ZhiminXiang**
Bump the min k8s version to 1.15 in doc as we have already bumped the k8s version to 1.15 in other knative repo.

/cc @mattmoor

### CODE REVIEW

**Comment by samodell** [comment]
/approval

I can let Matt LGTM if you want, @ZhiminXiang . Thanks for the PR!

**Comment by ZhiminXiang** [comment]
> /approve
> 
> I can let Matt LGTM if you want, @ZhiminXiang . Thanks for the PR!

Thanks @samodell ! I just added other docs I accidentally missed in my previous commit. Could you take another look?

**Comment by samodell** [comment]
/lgtm

Thanks!

**Pull request merged**
