### PR TITLE
Copied the README into _index.md instead of referencing README from

### LINKED ISSUE #3367: Diagram in serving docs is a broken link
On this page https://knative.dev/docs/serving/ the "Diagram that displays how the Serving resources coordinate with each other" is a broken link.

I think the closest correct link is https://github.com/knative/serving/blob/main/docs/spec/images/object_model.png.

### PR DESCRIPTION
**Pull request by mpetason**
index so that the website will build properly. Did not delete README so
that github renders as well.

Fixes #3367 

## Proposed Changes 

- Copied README over to the _index.md file so that it renders correctly on the website
- Removed reference to README in _index.md.

### CODE REVIEW

**Comment by csantanapr** [comment]
I think we should not have duplicate files with the same content `README` `_index.md`
it will get out of sync very quick, if I have to choose then optimized for the website not github

**Comment by mpetason** [comment]
I agree. There were a couple other directories with both - so I went ahead and kept it, however I think we should work on what Hugo will render instead of caring about it showing up on Github. I can make the change and do another push. Prob a good thing to bring up in the docs working group. I'll see if I can add it to the agenda. There's a bunch of other places that this happens where we could remove files.

**Comment by mpetason** [comment]
Added this to next weeks agenda. I'll wait until there's a consensus and then make an update.

**Comment by csantanapr** [comment]
Sounds cool is the docs working group meeting weekly?
I been trying to join and have not been able to make is good to bring it up

**Comment by mpetason** [comment]
9:30 AM Pacific on Tuesdays. I'll be there next week. I haven't been in a little bit.

**Comment by abrennan89** [comment]
@mpetason I think it's fine to delete the README file

**Comment by mpetason** [comment]
Updated. Went ahead and removed the README.md

**Review by abrennan89 — APPROVED** [review]
Thanks! 🙂 
/lgtm

**Pull request merged**
