### PR TITLE
Add real build/unit presubmit tests

### PR DESCRIPTION
**Pull request by adrcunha**
Addresses #66.
Addresses #67.

* Update test-infra to use the default build/unit test runners, which includes building go code and linting markdown files.
* Remove the integration tests, as they only start Knative Serving, which is irrelevant for this repo.

Bonuses:
* fix unbuildable `grpc-ping-go` sample
* remove test-infra import hack from `Gopack.lock` and `update-deps.sh`

### CODE REVIEW

**Comment by samodell** [comment]
@adrcunha Can you add a reviewer who can take a look from an engineering perspective?

**Comment by adrcunha** [comment]
The build tests revealed several missing dependencies in the samples, I'll have to add them.

**Comment by adrcunha** [comment]
Ok, this is ready for review.

/hold cancel

**Comment by samodell** [comment]
Thanks @adrcunha ! Could you add a reviewer who could take a look from an eng perspective?

**Comment by adrcunha** [comment]
/assign @rgregg 

For approval.

**Pull request merged**
