### PR TITLE
Remove superfluous conjunction

### PR DESCRIPTION
**Pull request by eldondev**
This is a minor grammar fix.

### CODE REVIEW

**Comment by samodell** [comment]
/ok-to-test
/lgtm

Please check out the bot's info for help with getting your CLA signed, and then I'll be happy to merge this in. Thanks for the PR!

**Comment by samodell** [comment]
I think the issue with the OWNERS is actually in the set of steering committee members; it looks like Jaice isn't a member of the Knative Org anymore -- https://github.com/orgs/knative/people?utf8=%E2%9C%93&query=jdumars

I'll remove him from the top-level owners file and see if that fixes the issue.

**Comment by eldondev** [comment]
@samodell Ok, thanks. I will need to repush with an email with related google account I guess. Will do shortly.

**Comment by eldondev** [comment]
@googlebot  I signed it!

**Comment by eldondev** [comment]
Ok, looks like I didn't actually have to update the email on the commit.

**Comment by samodell** [comment]
yep, so long as the email the commit is signed with is the same email address used to sign the CLA, you're good to go!

Thanks for your contribution :)

/approve

**Pull request merged**
