### PR TITLE
Mkdocs netlify

### PR DESCRIPTION
**Pull request by csantanapr**
- adds netlify config
- supports preview

You can see netlify here in my personal fork
https://upbeat-austin-3c1868.netlify.app/docs/

Previews is available from netlify tasks
image

### CODE REVIEW

**Comment by julz** [comment]
oh hah, we both did this in parallel :D Im gonna close mine!

**Review by julz — APPROVED** [review]
nice, your version looks way cleaner than mine did :) 

/lgtm
/approve

BTW if you do the following netlify will do a nice comment on the PR when it generates the preview (from https://levelup.gitconnected.com/how-to-setup-previews-for-prs-on-your-github-repo-using-netlify-105c80574875)

Screenshot 2021-05-18 at 00 30 33

**Comment by csantanapr** [comment]
wait I think I'm mising requirements.txt?

**Comment by julz** [comment]
no you have it here: https://github.com/knative/docs/blob/6da9437213b0812732c9644cf69dc57b701bb095/requirements.txt

**Comment by csantanapr** [comment]
ah I was looking for the comment thing

**Comment by csantanapr** [comment]
nevermind I thought I edited 3 files, but is only 2

**Comment by csantanapr** [comment]
comment works
image

**Pull request merged**
