### PR TITLE
Fix typo in kpa-specific.md

### PR DESCRIPTION
**Pull request by r00ta**
fix typo

"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-
-
-

### CODE REVIEW

**Comment by psschwei** [comment]
Thanks for the PR! You'll need to sign the CLA before this can merge.
/ok-to-test

**Comment by abrennan89** [comment]
@r00ta please sign the CLA so that we can merge / close this PR. Thanks.

**Comment by r00ta** [comment]
@abrennan89 signed, thanks!

**Review by psschwei — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
