### PR TITLE
Update community samples to use v1beta1 APIs

### LINKED ISSUE #1330: Community samples need to be updated for Serving 0.6
**Describe the change you'd like to see**
https://github.com/knative/docs/tree/master/community/samples/serving demonstrate using the new API shapes introduced in Serving 0.6

**Additional context**
Serving 0.6 updated the recommended API fields for Services. The examples were updated in https://github.com/knative/docs/tree/master/docs/serving/samples, but this directory was missed.

### PR DESCRIPTION
**Pull request by dgerd**
Replace the use of `runLatest` with `template`.

/label cherrypick-0.6

Fixes #1330

### CODE REVIEW

**Comment by RichieEscarez** [comment]
@grayside any chance that you are able to help validate these updates?

**Comment by dgerd** [comment]
@RichieEscarez I don't think the failure looks related to my change. Is there a known flake or breakage in the integration tests?

**Comment by RichieEscarez** [comment]
@chaodaiG can you please help with this failure too?

**Comment by chaodaiG** [comment]
It's pretty weird error, I'll take a look at it

**Comment by dgerd** [comment]
@RichieEscarez Do you have any concerns merging this, or can we add another reviewer?

**Pull request merged**
