### PR TITLE
Release notes for Knative 0.18

### PR DESCRIPTION
**Pull request by csantanapr**
Blog for release notes 0.18

### CODE REVIEW

**Comment by csantanapr** [comment]
I have release notes for Serving and Eventing.

Waiting for the following release notes to be publish
- Eventing-Contrib
- Client (CLI)
- Operator

**Comment by rhuss** [comment]
The client will be released as usual one week after serving/eventing, so the target date is October 6 (might slip to October 7).

**Comment by csantanapr** [comment]
@mpetason dont worry about the 429s it can't be fix with the current tool we have that checks for links

**Comment by rhuss** [comment]
@csantanapr the release noted for the client 0.18.0 are now online.

**Comment by csantanapr** [comment]
Got Eventing Contrib and CLI release notes in.

Waiting for operator release notes to be posted https://github.com/knative/operator/releases/tag/v0.18.0

I ping @houshengbo on Slack to let me know when he is done with the release notes, the release was cut yesterday.

**Comment by csantanapr** [comment]
I got the release notes for operators added today.

**Comment by csantanapr** [comment]
/unhold

This is ready now

**Comment by mattmoor** [comment]
/assign @n3wscott @ZhiminXiang 

(release leads) 🙏

**Comment by n3wscott** [comment]
lgtm on the eventing side.

**Pull request merged**
