### PR TITLE
Update version warning banner for new release

### LINKED ISSUE #4150: Remove yellow banner from website
## Expected Behavior
Now that we've released the new version of the website, we can remove the yellow banner from the top of the site. 

## Actual Behavior
It's still there

## Steps to Reproduce the Problem

1. Go to knative.dev 
2. Look at top of page 
3. Become visibly upset

### PR DESCRIPTION
**Pull request by julz**
We've been live for a full release now with the new site. Time to take the warnings about being new away!

Also fixed up the colours and text for the warning shown on old docs versions, and added an emoji because emojis are cool.

(Do let me know if you hate the diagonal stripes, I think they look good and emphasise the warning, but this is the sort of things where opinions differ in which case I'll happily drop them!)

Fixes #4150.

/assign @omerbensaadon @csantanapr

### CODE REVIEW

**Comment by julz** [comment]
/hold

spotted a little problem

**Comment by omerbensaadon** [comment]
Thanks for this @julz!!

I would go a step further and cherry-pick the removal of the banner to the current version. 

I am not seeing any changes to the warning on previous versions of the documentation based on the Netlify link.

**Comment by julz** [comment]
Yeah we'll need to cherry-pick it back for it to show on older versions

**Comment by julz** [comment]
You can test with something like `KNATIVE_VERSION=1.2.3 VERSION_WARNING=true mkdocs serve`

**Comment by csantanapr** [comment]
thank you for the clean up
/lgtm

**Pull request merged**
