### PR TITLE
Updated cloudevents-rust sample to sdk-rust 0.2

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

## Proposed Changes 

- Updated cloudevents-rust sample to sdk-rust 0.2, using the new apis

### CODE REVIEW

**Comment by markusthoemmes** [comment]
@slinkydeveloper is this still up-to-date? If yes we can merge it.

**Comment by slinkydeveloper** [comment]
@markusthoemmes it's updated, let's merge it

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
