### PR TITLE
Update k8s minimum version in (docs/install/any-kubernetes-cluster.md)

### LINKED ISSUE #3169: Update Kubernetes minimum version in install docs
## Expected Behavior

Kubernetes minimum version is **v1.17** or newer in [Knative docs](https://knative.dev/docs/install/any-kubernetes-cluster/#before-you-begin).

## Actual Behavior

Kubernetes minimum version is **v1.16** or newer in [Knative docs](https://knative.dev/docs/install/any-kubernetes-cluster/#before-you-begin).

## Steps to Reproduce the Problem

1. Navigate to [Knative docs](https://knative.dev/docs/install/any-kubernetes-cluster/#before-you-begin).
1. Select v20.0 in the documentation version dropdown box. 

Also, see on the git repo for [master](https://github.com/knative/docs/blob/master/docs/install/any-kubernetes-cluster.md) and [release-0.20](https://github.com/knative/docs/blob/release-0.20/docs/install/any-kubernetes-cluster.md).

## Additional Info
[This PR](https://github.com/knative/docs/pull/3126) fixed the minimum version for the v19.0 docs but it seems it was not applied to master and release-0.20 branches.

### PR DESCRIPTION
**Pull request by izabelacg**
Fixes #3169

## Proposed Changes 
Update Kubernetes minimum version from `v0.16` to `v0.17` in the install docs.

### CODE REVIEW

**Comment by nak3** [comment]
/assign @dprotaso @mattmoor 

Actually the next Knative release 0.21 will change the min version to [k8s 1.18.x](https://github.com/knative/community/blob/master/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#knative-serving-version-table) so we would need to update this doc soon  :thinking:

**Comment by izabelacg** [comment]
> /assign @dprotaso @mattmoor
> 
> Actually the next Knative release 0.21 will change the min version to [k8s 1.18.x](https://github.com/knative/community/blob/master/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#knative-serving-version-table) so we would need to update this doc soon 🤔

Hi, I see that the [contributing docs](https://github.com/knative/docs/blob/master/CONTRIBUTING.md#choosing-the-correct-branch) recommended to add a label to indicate when a pr needs to be merged into master and a release branch. I tried to add the label `needs-cherry-pick` and `release-0.20`, but it didn't work.

**Comment by dprotaso** [comment]
/ok-to-test
/lgtm
/approve

I'm fine merging this now and bumping when Prow gets 1.18. 


/cherrypick release-0.20

**Comment by dprotaso** [comment]
@izabelacg you'll need to sign the CLA

**Comment by izabelacg** [comment]
@googlebot I signed it!

**Pull request merged**
