### PR TITLE
The api version should match the broker config apiversion

### PR DESCRIPTION
**Pull request by akesiraju**

### CODE REVIEW

**Comment by dprotaso** [comment]
Thanks @akesiraju you'll want to sign our CLA - details here https://github.com/knative/docs/pull/5597#issuecomment-1583292117

/assign @gabo1208

**Review by gabo1208 — APPROVED** [review]

**Comment by gabo1208** [comment]
Thank you very much @akesiraju !! Approved cc @dprotaso

**Comment by akesiraju** [comment]
Anything else I should do to merge this PR

**Comment by gabo1208** [comment]
Do you fixed the CLA? If you did push an empty commit for the CI to take it

**Comment by skonto** [comment]
@akesiraju gentle ping. Could you fix the CLA issue so we can merge this?

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
