### PR TITLE
Add CA certificates

### PR DESCRIPTION
**Pull request by michaelabdelmalek**
Add CA certificates so we can make HTTPS requests. See https://godoc.org/cloud.google.com/go#hdr-Using_the_Libraries_with_Docker

### CODE REVIEW

**Comment by samodell** [comment]
@michaelabdelmalek  It looks like you've accidentally deleted a large number of lines in this PR. Can you restore the removed lines?

**Comment by michaelabdelmalek** [comment]
@samodell sorry I don't know what happened with the accidental removals. Fixed. PTAL

**Comment by samodell** [comment]
So close - now there's a conflict, @michaelabdelmalek

**Comment by samodell** [comment]
Ah, actually, I realize now this is a dupe of #1143 . Sorry for the trouble, but closing this as a dupe.

**Pull request closed without merging**
