### PR TITLE
Fix markdown rendering issue with brackets

### PR DESCRIPTION
**Pull request by psschwei**
xref #5230 
/assign @abrennan89

### CODE REVIEW

**Comment by psschwei** [comment]
check the preview to make sure :smile:

**Comment by psschwei** [comment]
doesn't actually fix the issue
/hold

**Comment by abrennan89** [comment]
Looks like it fixes it OK?
/lgtm
/approve

The build check I guess is still failing and unrelated, but at least this fixes that one page

**Comment by psschwei** [comment]
> Looks like it fixes it OK? 

first fix showed the backslashes, new one uses `{% raw %}` jinja tags so that macros plugin will ignore it

**Pull request merged**
