### PR TITLE
Release 1.2

### PR DESCRIPTION
**Pull request by gabo1208**
Rebasing to 1.2

### CODE REVIEW

**Comment by csantanapr** [comment]
google cla is not happy. 
Don't understand why it thinks that @starpit have not sign the CLA
image

**Comment by starpit** [comment]
Strange, the PRs have all been happy. Here is the CLA check for the PR in question: https://github.com/knative/docs/pull/4746/checks?check_run_id=5208725441

why would the CLA bot be happy for the PR but unhappy here?

**Comment by gabo1208** [comment]
I think this happens when someone fix the cla manually in an old PR (?)

**Comment by csantanapr** [comment]
>https://opensource.google/documentation/reference/cla#verify
I could not figure out what to do from the instructions shared on this link. 

I did a manual sync here https://github.com/knative/docs/pull/4772
/close

**Pull request closed without merging**
