### PR TITLE
add docker development workflow

### LINKED ISSUE #3664: Create a Docker image for contributor use
## Description: 
We have added a number of extensions to the existing Material for MkDocs deployment and need to create a Docker image which reflects those additions.

---

## Story
```
As Carlos the Contributor 
I want to leverage a Docker image to work on the docs/website
So that I don't have to deal with local tooling 
And I can contribute to docs in the way that is most comfortable for me 
```

## Acceptance Criteria
`Docker Image Works`
```
GIVEN a Docker image has been created for Knative's deployment of MkDocs 
WHEN I follow the instructions on https://hub.docker.com/r/squidfunk/mkdocs-material/, substituting the link to the new Docker image
THEN I can successfully render the Knative site without errors on my local machine 
```

`Documentation Exists`
```
GIVEN I want to use the Docker image for a local deployment of the Knative.dev website 
WHEN I look follow the link https://dev-knative.netlify.app/development/getting-started/contributing/contributing/#use-the-docker-container
THEN I see some basic instructions for getting the Docker Image to work. 
```

## Known Issues and Considerations: 
See https://dev-knative.netlify.app/development/getting-started/contributing/contributing/#install-knative-specific-extensions for a list of the extensions we currently use. They are reproduced below: 

```
mkdocs-material-extensions 
mkdocs-macros-plugin 
mkdocs-exclude 
mkdocs-awesome-pages-plugin 
mkdocs-redirects
```

**You may also want to check the mkdocs.yaml file for any we've missed?** 

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [x] New Contributors

### PR DESCRIPTION
**Pull request by csantanapr**
Closes #3664 

Provides a simple workflow for mkdocs

Do once to build the container
```
npm run dev:build
```

To start working on docs (instant livereload using a container)
```
npm run dev
```

When done working on docs
```
npm run dev:stop
```

cc @abrennan89 @RichardJJG @snneji 

/kind mkdocs
/assign @julz 
/assign @omerbensaadon

### CODE REVIEW

**Review by julz — COMMENTED** [review]
Just to check I understand the reasoning, could we not ship a pre-built docker image with the deps installed and avoid docs writers having to have node/npm installed (and the build step)?

**Comment by csantanapr** [comment]
>Just to check I understand the reasoning, could we not ship a pre-built docker image with the deps installed and avoid docs writers having to have node/npm installed (and the build step)?

No reason why we can't use a prebuilt image. How do I do that in this PR?

**Comment by omerbensaadon** [comment]
+ 1 to pre-built image, not sure if I did a good job of specifying that in
the story…

**Comment by csantanapr** [comment]
A pre-built image is a good idea, we just need to work with someone that knows how the infra/prow works to be able to push an image with a nightly job

I propose we merge this PR and an issue is already created for the pre-built image https://github.com/knative/docs/issues/3664

**Pull request merged**
