### PR TITLE
Updated link

### LINKED ISSUE #4621: Knative Offerings -> Gardener's link is broken
## Expected Behavior
Link to me to a page where I can understand the Gardener Knative Offering

## Actual Behavior
[Gardener](https://gardener.cloud/docs/tutorials/knative-install/) link is a 404

## Steps to Reproduce the Problem

1. Visit [Knative Offerings](https://knative.dev/docs/install/knative-offerings/#knative-offerings) 
1. Click `Gardener`

### PR DESCRIPTION
**Pull request by n-boshnakov**
Fixes #4621 

## Proposed Changes 

- Change Gardener link in "Knative Offerings" page to point to Github repository

### Reasoning:
The Gardener website has been restructured, so that only tutorials for Gardener components are shown. We can't find a component to attach this tutorial to, but we can link to the original Github page, which has the same content.

### CODE REVIEW

**Comment by abrennan89** [comment]
@n-boshnakov I think you need to sign the CLA

**Comment by n-boshnakov** [comment]
> @n-boshnakov I think you need to sign the CLA

I have signed the CLA.

**Comment by snneji** [comment]
Thanks for spotting this and making a PR @n-boshnakov!

/lgtm
/approve

**Pull request merged**
