### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by Murphylu1993**
Fixes #issue-number or description of the problem the PR solves

## Proposed Changes 

-
-
-

### CODE REVIEW

**Comment by Murphylu1993** [comment]
i signed it

**Comment by Murphylu1993** [comment]
> @googlebot I signed it

**Comment by Murphylu1993** [comment]
> @googlebot I signed it!

**Comment by Murphylu1993** [comment]
> @googlebot I signed it!

**Comment by matzew** [comment]
```

Markdown_Link expand_less | 0s
-- | --
docs/serving/knative-kubernetes-services.md 	ERROR	https://knative.dev/docs/install/knative-custom-install/ 		Not Found (HTTP error 404)

```

**Pull request merged**
