### PR TITLE
Swap website colours of the Home page

### LINKED ISSUE #6028: Swap website colours to be in line with logo and to meet WCAG AAA
## What is changing? (Please include as many details as possible.)
Swapping website colours to align with the logo and meet WCAG AAA standards.

## How will this impact our users?
Improved accessibility and a cohesive visual experience with the logo.

### PR DESCRIPTION
**Pull request by ShravaniAK**
Fixes #6028 

## Proposed Changes 

- swapped the main 2 primary light and primary dark colours
- changed the nav-item-color to #494848
- added consistent corner rounding and spacing between buttons.

### CODE REVIEW

**Comment by Cali0707** [comment]
/hold until UX WG approves colour changes
/cc @mmejia02 @zainabhusain227 
do these new colours match the design system or should we change them at all?

**Comment by mmejia02** [comment]
@ShravaniAK, these are already really great changes!! It looks like you got all of the hex codes right, but weirdly it seems to be rendering the dark blue much lighter than it should. I'm unsure how to solve that problem. As you know, the dark blue hex code is #0D4984, which you have in your sourcecode. However, if you put the pre-release side by side, you see this dark blue is much lighter. 
image
Also it would be great if the text colour on the first block of the homescreen were black/the off black colour we've been using. The light blue and greys look great!! Thank you for all of your work!

**Comment by ShravaniAK** [comment]
@mmejia02 thankyou very much for your feedback , the dark blue color problem is not there in my browser and also i checked with the latest deploy preview link , also I have already replaced the text color of first container of homescreen with black color , do you want be to replace it with some different shade of black ?
 

Screenshot 2024-07-01 at 4 56 42 PM

**Comment by mmejia02** [comment]
@ShravaniAK , in your browser it looks amazing and I have no other feedback!! Exciting stuff :) I still have no idea why my rendering is being weird but it's fine

**Comment by Cali0707** [comment]
Okay let's merge this for now, and then  @ShravaniAK can you try testing this on some other browsers?

**Review by Cali0707 — APPROVED** [review]
/unhold
/lgtm
/approve

**Pull request merged**
