### PR TITLE
Update links in document to Knative v1.0.0

### PR DESCRIPTION
**Pull request by tendant**
Update documents to reflect changes for knative v1.0.0.

### CODE REVIEW

**Comment by tendant** [comment]
Please re-scan for CLA check.

**Comment by snneji** [comment]
Hi @tendant, thanks for the PR! The CLA bot is still failing. Have you signed the CLA using the email address listed in your commit [here](https://github.com/knative/docs/commit/4a2882f4b660bac50ed6b5db8467628d4d37f943.patch)?

**Comment by tendant** [comment]
I just check cla from https://cla.developers.google.com/. It was signed. However my account also has an alternative email. I just removed alternative email address. Could you please rescan again? Thanks.

**Comment by snneji** [comment]
Hi @carlisia, since you are on call for knative.party this week, could you check this one over and add LGTM. Thanks!

**Pull request merged**
