### PR TITLE
update docs for topic Installing Istio for Knative

### PR DESCRIPTION
**Pull request by james426759**
Signed-off-by: james759426 <james759426@gmail.com>

Fixes #

## Proposed Changes 

- update docs for topic Installing Istio for Knative v.0.20

   old: Replace the `local-gateway.knative-serving.cluster-local-gateway` field with the custom service. As an example, if you name both

   new: Replace the `local-gateway.knative-serving.knative-local-gateway` field with the custom service. As an example, if you name both

### CODE REVIEW

**Comment by nak3** [comment]
/assign @arturenault @JRBANCEL @ZhiminXiang 
/ok-to-test

We need to update all `cluster-local-gateway` in the docs https://knative.dev/docs/install/installing-istio/ should be updated to `knative-local-gateway`?

**Review by csantanapr — APPROVED** [review]
Thanks for the update the details are in the config map for net-istio https://github.com/knative-sandbox/net-istio/blob/master/config/config.yaml

**Pull request merged**
