### PR TITLE
Fontsizing for tables, code tags fixing issue (#3694)

### PR DESCRIPTION
**Pull request by soham283**
"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-Font size changes  for 
- table tag
- code tag
- admonition class
-Fixing issue #3694

### CODE REVIEW

**Comment by soham283** [comment]
@snneji  please check this PR which will probably fixing the small text errors.
the output for my local machine deployment :
font sizing tables
knative font sizing

**Comment by snneji** [comment]
Thanks @soham283. The text looks to me like a much better size. 

/lgtm

**Comment by omerbensaadon** [comment]
/ok-to-test 

lol

**Pull request merged**
