### PR TITLE
Fixed error in incomplete sentence.

### PR DESCRIPTION
**Pull request by SamuPert**
There is an incomplete sentence in the community documentation in https://knative.dev/docs/community/.

## Proposed Changes 

- Corrected the documentation fixing the error in the incomplete sentence.

### CODE REVIEW

**Comment by psschwei** [comment]
Thanks for the PR @SamuPert !

Once you sign the CLA we can get this merged

/hold
for CLA

**Comment by SamuPert** [comment]
> Thanks for the PR @SamuPert !
> 
> Once you sign the CLA we can get this merged
> 
> /hold for CLA

Oops. I missed this!
I just signed the CLA.
Thank you for the feedback @psschwei !

**Review by psschwei — COMMENTED** [review]
Thanks @SamuPert  !!

/lgtm
/approve

**Pull request merged**
