### PR TITLE
Fixed Broken Image Links

### PR DESCRIPTION
**Pull request by hpandeycodeit**
Fixes: 

The website has a couple of  broken image links on this page: 
https://www.knative.dev/docs/install/knative-with-gardener/

Under the following sections: 

1. Access Gardener [Download Kubeconfig for Gardner](https://www.knative.dev/docs/install/knative-with-gardener/images/gardener_service_account.png)
2. Creating a Kubernetes cluster [shoot creation](https://www.knative.dev/docs/install/knative-with-gardener/images/gardener_shoot_creation.png)

## Proposed Changes

- Fixed the dead links on this page.

### CODE REVIEW

**Comment by samodell** [comment]
hm, @hpandeycodeit , not sure what's going on with the conflicts here. Is the file maybe in the wrong spot? In release-0.3, this file is in /docs/install/, and not just /install.

https://github.com/knative/docs/tree/release-0.3/docs/install

**Comment by hpandeycodeit** [comment]
@samodell let me check.

**Comment by samodell** [comment]
Ah, sorry @hpandeycodeit ; it looks like this was fixed somewhere along the way. Those images show up fine now.

**Pull request closed without merging**
