### PR TITLE
Release blog post for Knative v0.20

### LINKED ISSUE #3156: Do the blog relesae notes for v0.20
Write up blog similar to https://knative.dev/blog/2020/11/13/version-v0.19-release/ but for v0.20

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #3156 

Provides a consolidated view of release notes for v0.20

### CODE REVIEW

**Comment by csantanapr** [comment]
/hold

@rhuss and @houshengbo please let me know when the release notes are available for Client and Operator to add them to blog post.

**Comment by csantanapr** [comment]
/assign @evankanderson 

This is ready now

**Review by mattmoor — APPROVED** [review]
/lgtm

I'm assuming the content is largely from hackmd.  thanks!

**Pull request merged**
