### PR TITLE
add Kubernetes API server event source

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

- add Kubernetes API server event source in the list of sources with CRDs

### CODE REVIEW

**Comment by sebgoa** [comment]
I believe you need to run the generator to create the table in markdown as well. I don't think the CI does it automatically yet.

**Comment by samodell** [comment]
@sebgoa  is correct; you should regenerate the table yourself and include the updates to the .md file in this PR. Instructions for doing so are on lines 5-12 of this file: https://github.com/knative/docs/blob/master/docs/eventing/sources/generator/ReadmeTemplate.gomd

**Comment by lionelvillard** [comment]
thanks! The apiserver source is being moved to `eventing`. When this is done I'll update this PR and regenerate the doc.

**Comment by samodell** [comment]
@lionelvillard  Ping me when you've regenerated the doc and we'll get this merged in :)

**Comment by lionelvillard** [comment]
@samodell I fixed the link to the apiserver source and regenerated the doc.

**Comment by n3wscott** [comment]
I did not see this one and already added the apiserversource via https://github.com/knative/docs/pull/1307
/close

**Pull request closed without merging**
