### PR TITLE
Update README.md

### LINKED ISSUE #3124: Broken link in /docs/eventing/samples/kafka/binding/index.html
Screen_Shot_2021-01-06_at_10_42_14_AM

## Expected Behavior
Link works

## Actual Behavior
Link doesn't work

## Steps to Reproduce the Problem

1. Go to page referenced in title
1. Click the link 
1. Read it and weep

## Additional Info
**Additional context**
I am going to open a PR to fix this. 

Originally surfaced by @MaciekLeks in #3121

### PR DESCRIPTION
**Pull request by omerbensaadon**
Fixes #3124

Broken link fixed

### CODE REVIEW

**Comment by omerbensaadon** [comment]
First surfaced by #3121

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/assign @vaikas

**Pull request merged**
