### PR TITLE
Align Scala sample with the rest of our samples

### PR DESCRIPTION
**Pull request by markusthoemmes**
This aligns the Scala sample with our other samples, behavior and layout-wise. Also bumps the Scala version and dependencies to something much more recent.

### CODE REVIEW

**Comment by skonto** [comment]
I haven't tried it but lgtm.

**Comment by markusthoemmes** [comment]
/assign @mattmoor 

Care to stamp this?

**Review by mattmoor — COMMENTED** [review]
/lgtm

Awesome, thanks! 🤩

**Pull request merged**
