### PR TITLE
gen-api-reference-docs: fixes for eventing-contrib

### LINKED ISSUE #1528: Cannot build release 0.7 API docs for knative/eventing-contrib
Following the [instructions to build the Knative API docs](https://github.com/knative/docs/blob/master/docs/reference/README.md) fails (see error below) for the knative/eventing-contrib repo.

The [gen-api-reference-docs.sh](https://github.com/knative/docs/blob/master/hack/gen-api-reference-docs.sh) script looks for the API in the [repo]`/pkgs/apis/` folder but that is no longer the structure of the knative/eventing-contrib repo, [for example](https://github.com/knative/eventing-contrib/tree/master/contrib/awssqs/pkg/apis).

Error:
```
I0625 22:01:32.404033   65566 main.go:118] parsing go packages in directory ./pkg/apis
W0625 22:01:32.404871   65566 parse.go:224] Ignoring directory ./pkg/apis: unable to import "./pkg/apis": cannot find package "./pkg/apis" in:
	/var/folders/gq/__83tbn10y753yg0kmgnhcyr009dwx/T/tmp.sc2JgEAe/src/github.com/knative/eventing-contrib/pkg/apis
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14096e5]

goroutine 1 [running]:
k8s.io/gengo/parser.(*Builder).AddDirRecursive(0xc0001a2000, 0x7ffeefbff9bc, 0xa, 0x0, 0x0)
	/Users/rescarez/go/pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/parser/parse.go:229 +0xb5
main.parseAPIPackages(0x7ffeefbff9bc, 0xa, 0x151bc04, 0x23, 0xc00014ff08, 0x1, 0x1)
	/Users/rescarez/go/pkg/mod/github.com/ahmetb/gen-crd-api-reference-docs@v0.0.0-20190107211124-5c208a662b46/main.go:186 +0x60
main.main()
	/Users/rescarez/go/pkg/mod/github.com/ahmetb/gen-crd-api-reference-docs@v0.0.0-20190107211124-5c208a662b46/main.go:119 +0x222
```

cc/ @ahmetb

### PR DESCRIPTION
**Pull request by ahmetb**
This updates to a recent version of gen-crd-api-reference-docs and allows
customizing the -api-dir option so that the docs for theeventing-contrib repo
can be generated.

Fixes #1528.

### CODE REVIEW

**Comment by RichieEscarez** [comment]
The build ran perfectly! Im now trying to stage and test the output in my folk.

**Comment by ahmetb** [comment]
SGTM. There are some issues like duplicated API Groups (both for eventing and serving) at the beginning of the doc.

It's happening because now there are different Go packages adding types to an `apiGroup`, so I need to go figure out how to de-dupe them.

**Comment by RichieEscarez** [comment]
I found something interesting (not sure if its a Golang thing, but the HTML output is incorrectly picking up a parenthesis from comment:
https://github.com/knative/eventing-contrib/blob/9d20f1c0ceeffd937d70d77abbea8bb1df3c32f3/contrib/gcppubsub/pkg/apis/sources/v1alpha1/gcp_pubsub_types.go#L58

The 404 is caused by a closing parenthesis `)`:
image

**Comment by RichieEscarez** [comment]
Ill manually remove the duplicate packages and fix the URLs for now. Thanks Ahmet!

image


image

**Comment by RichieEscarez** [comment]
Re: duplicate Packages in serving: I found that its due to v1alpha1 vs v1beta1 (thus two `serving.knative.dev`)

**Comment by RichieEscarez** [comment]
Capturing manual updates:

eventing-contrib-resources.md:

Remove duplicate Packages links and titles + consolidate Resource Types into single list
image
In each section, remove the duplicate title and move the Resource Types into the consolidated list, for example:
image

serving.md:

Qualify v1alpha1 vs v1beta1 (fix Packages list, link IDs, and Section titles)
image
image
image

**Comment by ahmetb** [comment]
We might be able to fix the parenthesis issue by tuning the Markdown renderer.

Can you open an issue to the tool?

**Comment by RichieEscarez** [comment]
created https://github.com/knative/docs/issues/1559 for tracking the current issues

**Pull request merged**
