### PR TITLE
home page new design implementation

### PR DESCRIPTION
**Pull request by ShravaniAK**
issue #6040 

changes made :
1. replaced the svg for "Why serverless containers" section .
2. aligned the text to center of "Knative Components" section.
3. replaced the svg for "Trying it all together" section

### CODE REVIEW

**Review by Cali0707 — COMMENTED** [review]
@ShravaniAK when I hover over the SVGs in the "why serverless containers" section, the text seems to be shifted down. Would you be able to fix this?

**Comment by ShravaniAK** [comment]
hey @Cali0707 , I have fixed the hovering issue over the SVGs, and also did some minor styling fixes.

**Review by Cali0707 — APPROVED** [review]
/approve

@mmejia02 @zainabhusain227 can one of you review this and add an lgtm if it looks good to you?

**Pull request merged**
