### PR TITLE
remove old hugo static build for v0.21

### PR DESCRIPTION
**Pull request by csantanapr**
when we release the new version of the docs for v0.25, the PR is here https://github.com/knative/docs/pull/4151

We can then remove the archived files for v0.21

holding until #4151 is merged first
/hold

/assign @julz

### CODE REVIEW

**Comment by csantanapr** [comment]
/unhold
The new v0.25 is live now https://knative.dev/docs/, now we can remove v0.21

**Comment by csantanapr** [comment]
@julz this one is ready now

**Comment by csantanapr** [comment]
adding @omerbensaadon  to see it can review/merge
/assign @omerbensaadon

**Comment by omerbensaadon** [comment]
Woo! Only a few more of these to go! Thanks @csantanapr for this 👍🏼

**Review by julz — APPROVED** [review]
/lgtm

**Pull request merged**
