### PR TITLE
Adds namespace to Role and RoleBinding in ApiServerSource example

### PR DESCRIPTION
**Pull request by gab-satchi**
"Fixes #issue-number" or "Add description of the problem this PR solves":
Following the `Creating an ApiServerSource object` docs leads to a permission issue with the ApiServerSource.

## Proposed Changes 
Adds namespace to the Role and RoleBinding. They would be tied to the default namespace otherwise and the ApiServerSource wouldn't start

### CODE REVIEW

**Comment by snneji** [comment]
Hi @gab-satchi, thanks for the PR!

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
