### PR TITLE
Fix cloudevent-nodejs sample to support SDK 4.0

### LINKED ISSUE #3247: Serving CloudEvent Sample for nodejs is broken
## Expected Behavior
Working sample cloudevent for nodejs here https://knative.dev/docs/serving/samples/cloudevents/cloudevents-nodejs/

## Actual Behavior
Doing the first scenario to run without `K_SINK` defined it should reply with a new CloudEvent

## Steps to Reproduce the Problem

```
git clone https://github.com/knative/docs.git knative-docs
cd knative-docs/docs/serving/samples/cloudevents/cloudevents-nodejs
docker build --no-cache -t csantanapr/helloworld-nodejs .
docker run --rm -p 8080:8080 csantanapr/helloworld-nodejs
```
Send a cloudevent
```
curl -X POST \
    -H "content-type: application/json"  \
    -H "ce-specversion: 1.0"  \
    -H "ce-source: curl-command"  \
    -H "ce-type: curl.demo"  \
    -H "ce-id: 123-abc"  \
    -d '{"name":"Dave"}' \
http://localhost:8080
```

Logs from the container
```
Cookie monster is hungry for some cloudevents on port 8080!
Cookie monster is going to reply back with cloudevents
Accepted event: {
  "id": "123-abc",
  "time": "2021-02-13T03:19:57.513Z",
  "type": "curl.demo",
  "source": "curl-command",
  "specversion": "1.0",
  "datacontenttype": "application/json",
  "data": {
    "name": "Dave"
  }
}
ValidationError [TypeError]: invalid payload
  {"keyword":"type","dataPath":".time","schemaPath":"#/definitions/time/type","params":{"type":"string"},"message":"should be string"}
    at Object.validateCloudEvent (/opt/app-root/src/node_modules/cloudevents/dist/event/spec.js:23:19)
    at CloudEvent.validate (/opt/app-root/src/node_modules/cloudevents/dist/event/cloudevent.js:134:27)
    at new CloudEvent (/opt/app-root/src/node_modules/cloudevents/dist/event/cloudevent.js:100:23)
    at receiveAndReply (/opt/app-root/src/index.js:66:25)
    at /opt/app-root/src/index.js:95:43
    at Layer.handle [as handle_request] (/opt/app-root/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/app-root/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/app-root/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/app-root/src/node_modules/express/lib/router/layer.js:95:5)
    at /opt/app-root/src/node_modules/express/lib/router/index.js:281:22 {
  errors: [
    {
      keyword: 'type',
      dataPath: '.time',
      schemaPath: '#/definitions/time/type',
      params: [Object],
      message: 'should be string'
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by csantanapr**
Closes #3247

The following PR #3136 updated the cloudevent SDK from version 3.x to 4.x and this is a major semantic version, which caused code brakes as the code was not compatible with the new major version of the SDK.
https://github.com/knative/docs/pull/3136/files#diff-8d77ef3aae2dea7cc68b9f32a40ac8f43a211f8f6e7f673d12723ed596eca805R16

## Proposed Changes
This PR updates the sample code to be compatible with the new major version of the SDK

### CODE REVIEW

**Comment by csantanapr** [comment]
I guess PRs can't be assigned to `@knative/api-core-wg-leads` github teams.

Assigning to Knative Serving since this is a sample under serving in the docs.
Hope the WG leads move forward this PR to resolution.
/assign @mattmoor 
/assign @dprotaso 

pinging Ville just for awareness
/unassign @vaikas 
cc @vaikas

**Comment by mattmoor** [comment]
Try this:

/cc @knative/api-core-wg-leads

**Comment by mattmoor** [comment]
Perhaps who can be labeled reviewer depends on who has edit access?

/cc @knative/docs-wg-leads

**Review by mattmoor — APPROVED** [review]
/lgtm

**Pull request merged**
