### PR TITLE
[0.19] Document Apache Kafka Sink (#3031)

### PR DESCRIPTION
**Pull request by pierDipi**
Backport #3031 

## Proposed Changes 

- Document Sink concept
- Document Apache Kafka Sink

### CODE REVIEW

**Comment by pierDipi** [comment]
/cc @abrennan89 @mpetason 

@mpetason, can you consent?

**Comment by csantanapr** [comment]
thanks for the cherry pick @pierDipi but it looks like you need to look at the CLA issues

**Comment by pierDipi** [comment]
The bot is happy now, PTAL.

**Pull request merged**
