### PR TITLE
Add doc about cutomize kourier-bootstrap for Kourier gateways

### PR DESCRIPTION
**Pull request by nak3**
## Proposed Changes

This path documentation about the new field introduce by https://github.com/knative/operator/pull/1227

/cherrypick release-1.10
/cherrypick release-1.9

/cc @houshengbo

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
/approve
/assign @houshengbo

**Comment by dprotaso** [comment]
bump @houshengbo

**Comment by skonto** [comment]
@houshengbo gentle ping.

**Review by houshengbo — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
