### PR TITLE
More cleanup for helloworld-dart sample

### PR DESCRIPTION
**Pull request by kevmoo**
Align README.md content with code content
Fix a spelling issue
Ignore files as appropriate

### CODE REVIEW

**Comment by kevmoo** [comment]
@mattmoor ? (Hey, Cous!)

**Comment by kevmoo** [comment]
Friendly ping? @samodell @mattmoor @carieshmarie

**Comment by samodell** [comment]
Thanks, @kevmoo !

/lgtm
/approve

**Pull request merged**
