### PR TITLE
Subscriber image should not be in a sub array.

### PR DESCRIPTION
**Pull request by cr22rc**
Fixes #issue-number or description of the problem the PR solves

## Proposed Changes 

-
-
-

### CODE REVIEW

**Comment by cr22rc** [comment]
@googlebot I signed it!

**Comment by cr22rc** [comment]
@googlebot I signed it!

**Comment by cr22rc** [comment]
@googlebot I signed it!

**Comment by cr22rc** [comment]
I'm not sure why this still has the cla-no tag. I click the link above https://cla.developers.google.com/clas  And it shows me the cla aggrement

**Comment by vagababov** [comment]
@cr22rc I verified internally you have no record of CLA being signed.
Please go through the process again.

**Comment by cr22rc** [comment]
@vaikas Ok to merge?

**Comment by vaikas** [comment]
Thanks!

**Pull request merged**
