### PR TITLE
Removed errant ./ from URLs

### LINKED ISSUE #4043: Fix all instances of ./ in relative links
Fix all instances of ./

Detail: `[<some-page>](./<some-folder>/<some-page>)` is not valid (and the link checker doesn't like it -- it causes 404 errors in staging). The link must be one of the following:

`[<some-page>](../<some-folder>/<some-page>)`
`[<some-page>](<some-folder>/<some-page>)`

### PR DESCRIPTION
**Pull request by RichardJJG**
Fixes #4043

### CODE REVIEW

**Comment by RichardJJG** [comment]
This is effectively (but not literally) a cherry-pick. I tried an actual cherry-pick and the rebasing was a nightmare (which I guess I should have seen coming given the huge number of changes).

**Comment by RichardJJG** [comment]
Could you approve, please, @vaikas? Samia isn't able to (she maybe doesn't have permission to approve merges for one or two of these files like she does for the rest of the docs).

**Comment by julz** [comment]
/approve

@RichardJJG do feel very very free at any time to ping me if I can help with git stuff - I might have some git-fu tips for cherry picking if you run in to problems in future, to save you doing things like this manually

**Pull request merged**
