### PR TITLE
Fix getting domain name in Getting Started with Knative App Deployment

### LINKED ISSUE #297: host url is zero in helloworld-go
## Expected Behavior
host url should not be none after 

`export HOST_URL=$(kubectl get services.serving.knative.dev helloworld-go  -o jsonpath='{.status.domain}')
`

## Actual Behavior

host url is zero

## Additional Info

follow the steps in https://github.com/knative/docs/blob/master/install/getting-started-knative-app.md

### PR DESCRIPTION
**Pull request by miosman**
Domain information is available in the route resource and not the the knative service. Updating sample command to reflect the change.

Environment GKE 1.11.7-gke.4, Knative 0.4.0

Fixes  #297 

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by miosman** [comment]
I signed it!

**Comment by samodell** [comment]
Thanks @miosman ! This looks good, but can you resolve the conflicts?

**Comment by miosman** [comment]
@samodell I've fixed the conflict and update the second instance where ksvc is used to get the domain for consistency.

**Pull request merged**
