### PR TITLE
make netlify beta site return to home page

### PR DESCRIPTION
**Pull request by csantanapr**
make netlify hostname default to make it usable on netlify for now
This to fix when clicking on latest version
image

### CODE REVIEW

**Comment by csantanapr** [comment]
@julz this change didn't affect `{{ base_url }}`
Where is this coming from?

**Comment by julz** [comment]
hm.. not sure.. maybe we can try swapping the whole href to be {{ site_url }}. Guess it'll all fix itself when we go live anyway since knative.dev/docs will be the right link then! 🤷 .

**Comment by csantanapr** [comment]
Let's make hard code to netlify domain for now, then will adjust as we move the domain name

**Comment by julz** [comment]
so put site_url back to knative.dev/docs, and hardcode the "latest version" url to the netlify url in main.html for now? yeah, works for me

**Review by julz — APPROVED** [review]
/lgtm

**Comment by csantanapr** [comment]
The change needs to be done on @julz repo branches

**Pull request closed without merging**
