### PR TITLE
Fix issue 3489 (update docs after tools move from eventing-contrib repo to eventing repo)

### LINKED ISSUE #3489: eventing-contrib tools (event-display, appender for example) are moving to eventing
## What is changing? (Please include as many details as possible.)
These tools:
https://github.com/knative/eventing-contrib/tree/main/cmd

Are moving to:
https://github.com/knative/eventing/tree/main/cmd

Many of our existing docs refer to these tools so we need to update the examples.

## How will this impact our users?
All existing examples will continue to work because the images are still in the registry. But for all new usages, we should point the folks to the new repo.

## In what release will this take happen (to the best of your knowledge)?
v0.23

## Context
Link to associated PRs or issues from other repos here.

1.
1.
1.

### PR DESCRIPTION
**Pull request by vaikas**
"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

- Fixes #3489
-
-

### CODE REVIEW

**Comment by vaikas** [comment]
/hold
Hold until https://github.com/knative/eventing/pull/5295 lands and I can validate the release goes out properly.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

Fully agree on the hold for given reasons!

**Review by abrennan89 — APPROVED** [review]

**Comment by vaikas** [comment]
Verified that the artifacts were released for the nightly for:
```
https://storage.googleapis.com/knative-nightly/eventing/latest/websocket-source.yaml
https://storage.googleapis.com/knative-nightly/eventing/latest/appender.yaml
https://storage.googleapis.com/knative-nightly/eventing/latest/event-display.yaml
```

/unhold

**Pull request merged**
