### PR TITLE
Typo fix - contriubtions -> contributions

### LINKED ISSUE #249: Typo in community/README.md
## Expected Behavior

Be a shining example of perfect orthography, including spelling "contributions" correctly

## Actual Behavior

Misspell it as "contriubtions"

## Steps to Reproduce the Problem

1. Follow the "Knative community" link from https://github.com/knative/docs/
2. Read the subsequent page, https://github.com/knative/docs/blob/master/community/README.md
3. Stumble across the word "contriubtions" under "Knative authors"

### PR DESCRIPTION
**Pull request by sleinen**
Fixes #249

## Proposed Changes

* see title

### CODE REVIEW

**Comment by sleinen** [comment]
> Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

I signed it!

**Comment by sleinen** [comment]
/assign @rgregg
(as per the bot's suggestion)

**Comment by evankanderson** [comment]
Thanks, by the way!

**Pull request merged**
