### PR TITLE
Cherry pick changes from master into 0.6

### PR DESCRIPTION
**Pull request by RichieEscarez**
PRs:
#1408 
#1398 
#1392 
#1380 
#1363 
#1357 
#1355 
#1327
#1260

### CODE REVIEW

**Comment by RichieEscarez** [comment]
@chaodaiG Thanks for taking a look at this! Ive run local presubmit and e2etests without success =(

**Comment by chaodaiG** [comment]
@RichieEscarez  no problem

It should be fixed by my PR now

/retest

**Pull request merged**
