### PR TITLE
fix tab formatting - issue #4922

### LINKED ISSUE #4922: Fix tab formatting in code-samples folder
## Background
The files in `code-samples` folder are no longer viewable on the website, only in GitHub. However, this has caused broken formatting because tabbed elements are not available in GitHub markdown. 

## Task
Remove the tabbed formatting, for example `=== "yaml"`, in the files in the `code-samples` folder. Make sure that if the tabbed formatting is under a step, you indent your new formatting within each step.

Files that have this issue:
- [ ] [./code-samples/serving/cloudevents/cloudevents-nodejs/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-nodejs/README.md)
- [ ] [./code-samples/serving/cloudevents/cloudevents-rust/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-rust/README.md)
- [ ] [./code-samples/serving/cloudevents/cloudevents-go/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-go/README.md)
- [ ] [./code-samples/serving/cloudevents/cloudevents-vertx/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-vertx/README.md)
- [ ] [./code-samples/serving/cloudevents/cloudevents-spring/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-spring/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-ruby/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-ruby/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-shell/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-shell/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-java-spring/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-java-spring/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-python/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-python/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-java-spark/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-java-spark/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-go/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-go/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-php/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-php/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-scala/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-scala/README.md)

### PR DESCRIPTION
**Pull request by maryfrances01**
"Fixes #4922"

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
Thanks for the PR, and sorry it took so long to review!

One nit: why'd you go with bolded titles for `kn`/`kubectl`/etc. rather than subheadings (i.e. `### kn`)? I think in general subheadings making it easier to navigate the document, but could be persuaded the other way too...

**Comment by maryfrances01** [comment]
> Thanks for the PR, and sorry it took so long to review!
> 
> One nit: why'd you go with bolded titles for `kn`/`kubectl`/etc. rather than subheadings (i.e. `### kn`)? I think in general subheadings making it easier to navigate the document, but could be persuaded the other way too...

Hi @psschwei - I used bold instead of a heading just because I'm used to not putting headings under a procedure step. If it needs to be a heading, I can go ahead and make that change. 

Let me know!

**Comment by psschwei** [comment]
I took a look at our style guide. No definitive answer, but I think based on the [procedures template](https://github.com/knative/docs/blob/main/contribute-to-docs/templates/template-procedure.md#template) we should update to use subheadings.

**Review by psschwei — COMMENTED** [review]
Thanks so much!
/lgtm
/approve

**Pull request merged**
