### PR TITLE
Removed deprecated observability plugin

### LINKED ISSUE #2804: Confirm if Observability plugin was actually deprecated, and if it was update the docs
## Expected Behavior
https://knative.dev/docs/install/any-kubernetes-cluster/ contains only up to date information about components that can be installed.

## Actual Behavior
It mentions an Observability plugin that was deprecated in 0.14. The oldest currently published version of the docs is now 0.14, so this could be removed from all the documentation if it actually was deprecated at 0.14.

## Steps to Reproduce the Problem

1. See https://knative.dev/docs/install/any-kubernetes-cluster/
1. See https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-observability-plugin

### PR DESCRIPTION
**Pull request by abrennan89**
Fixes #2804 

## Proposed Changes 
- Removed observability plugin from install docs

### CODE REVIEW

**Comment by nak3** [comment]
Umm... I am recently confused about the status of the observability plugin. It announced that it was deprecated since v0.14 but there is a PR like https://github.com/knative/serving/pull/9613 and v0.18 still shipped the bundle.

/cc @mattmoor @markusthoemmes

**Comment by dprotaso** [comment]
Slack discussion from last month

https://knative.slack.com/archives/CAN0F23QW/p1600715808001100

**Comment by skonto** [comment]
@nak3 I as not aware of the status. So we can close my PR and try update docs with monitoring samples.

**Comment by nak3** [comment]
Once https://github.com/knative/serving/pull/9807 was merged, this page https://knative.dev/development/serving/installing-logging-metrics-traces/ also needs to be updated.

**Pull request merged**
