### PR TITLE
Improve Serving encryption docs

### PR DESCRIPTION
**Pull request by ReToCode**
Addressing https://github.com/knative/docs/pull/5804#discussion_r1584701059

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
Thanks @ReToCode for adressing. Just a minor nit, but looks good to me and I think it makes it easier for peoples to understand.

You could also use something like callouts, which would render nicely in asciidoc, but could make sense, here, too. Maybe even our HTML rendering framework does support something like this ? 🤔 

```
kind:ClusterIssuer    
metadata:
  name: cluster-selfsigned-user  # <1>
....
....
# <1>: Issuer used by cert-manager to ...
#      .... <next line>
# <2>: Knative specific issuer that will uses the CA stored
       in the secret "<name>" which has been created by the
       certificate "<name>"
```

But that's just some icing on the cake, so I approve it with a `/hold`. Feel free to adjust or merge.

/approve
/lgtm
/hold

**Comment by ReToCode** [comment]
@rhuss I don't think it is supported with the config used here:
image
Checked with and without the #.

**Comment by ReToCode** [comment]
/unhold

@rhuss PTAL

**Comment by ReToCode** [comment]
/unhold

Let's revisit this as a separate topic. If we do that, we should probably do it as a general pattern :)

**Pull request merged**
