### PR TITLE
delete useless placeholder for ping-source page

### LINKED ISSUE #2963: so many useless placeholder on ping-source page
**Describe the change you'd like to see**
https://knative.dev/docs/eventing/samples/ping-source/#create-a-knative-service

so many useless placeholder there, shall we delete it or not ?

```shell
{{< tabs name="create-service” default="By YAML” >}} {{% tab name="By YAML” %}} ............
```

image

**Additional context**

### PR DESCRIPTION
**Pull request by zhaojizhuang**
**Fixes #2963  delete useless placeholder for ping-source page**

so many useless placeholder there,

```shell
{{< tabs name="create-service” default="By YAML” >}} {{% tab name="By YAML” %}} ............
```

### CODE REVIEW

**Comment by zhaojizhuang** [comment]
Hi, @lionelvillard @n3wscott  can you have a look ? Thanks very much

**Comment by lionelvillard** [comment]
@zhaojizhuang thanks for doing this!

Instead of removing the shortcodes (what you call placeholder), please inline README.md into index.md and delete README.md

/hold

**Comment by zhaojizhuang** [comment]
@lionelvillard Done it. 
> @zhaojizhuang thanks for doing this!
> 
> Instead of removing the shortcodes (what you call placeholder), please inline README.md into index.md and delete README.md
> 
> /hold

**Pull request merged**
