### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by DaveSlinn**
Fixes #(issue-number)

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by DaveSlinn** [comment]
I signed it.

**Comment by samodell** [comment]
@DaveSlinn  Thanks for your PR! It looks like the CLA bot isn't satisfied yet -- can you double-check that the email you used to sign your commit is the same as the email you used when you signed the CLA? That's the most common problem.

**Comment by DaveSlinn** [comment]
Fixed it.

**Comment by samodell** [comment]
Thanks, @DaveSlinn ! 

/lgtm
/approve

**Pull request merged**
