### PR TITLE
fix broken url in docs

### PR DESCRIPTION
**Pull request by saintmalik**
## Summary

Easy navigation and easy reading for others

### CODE REVIEW

**Comment by abrennan89** [comment]
/hold
/approve

@mpetason I wasn't able to test this, but if it works OK for you feel free to merge.
@saintmalik could you also add this change to the master branch please so that it appears for future releases?

**Comment by mpetason** [comment]
/unhold

Looks like it should work

**Comment by saintmalik** [comment]
> /hold
> /approve
> 
> @mpetason I wasn't able to test this, but if it works OK for you feel free to merge.
> @saintmalik could you also add this change to the master branch please so that it appears for future releases?

@abrennan89 it did work, I checked the site now after the merge.

Also should I create a new pull request for this changes against the master branch now?

**Comment by saintmalik** [comment]
> /unhold
> 
> Looks like it should work

Its working bro

**Comment by abrennan89** [comment]
> Also should I create a new pull request for this changes against the master branch now?

Yes please

**Comment by saintmalik** [comment]
> > Also should I create a new pull request for this changes against the master branch now?
> 
> Yes please, you can assign it / tag me for a review too 🙂

Done, check here #3106

**Pull request merged**
