### PR TITLE
Eventing getting started hot fix

### PR DESCRIPTION
**Pull request by omerbensaadon**
Some small changes

### CODE REVIEW

**Comment by omerbensaadon** [comment]
@csantanapr @julz erm this preview link is doing the /development/development/development/ thing

**Review by julz — APPROVED** [review]
/lgtm

**Comment by julz** [comment]
Well, that's weird, do you need to rebase?

**Comment by omerbensaadon** [comment]
oh maybe, let me try

**Comment by julz** [comment]
Yep, you do, compare fix in your branch:

https://github.com/knative/docs/blob/09eb09c60ccd0fe34bfb5000491eb61cd09889ac/hack/build-with-blog.sh#L133

Vs in mkdocs main:

https://github.com/knative/docs/blob/mkdocs/hack/build-with-blog.sh#L133

**Pull request merged**
