### PR TITLE
Change initail to initial.

### PR DESCRIPTION
**Pull request by jmferrer**
Fixes #issue-number

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by RichieEscarez** [comment]
Thanks for your PR @jmferrer. Can you please sign the CLA (https://cla.developers.google.com/) so that I can approve and merge your change?

**Comment by jmferrer** [comment]
I received an e-mail asking me for /assign @vaikas-google
@RichieEscarez : Thank you for your work! cla signed

**Comment by samodell** [comment]
/ok-to-test

@jmferrer  the bot still thinks you don't have a CLA signed. Can you confirm you signed the CLA with the same email you used to sign your git commits?

**Comment by samodell** [comment]
ah, there we go!

/lgtm
/approve

**Pull request merged**
