### PR TITLE
fix: rm deprecated step

### PR DESCRIPTION
**Pull request by vincent0426**
"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

- RabbitMQBroker is deprecated as mentioned here https://github.com/knative-sandbox/eventing-rabbitmq/tree/main/samples/quick-setup

### CODE REVIEW

**Comment by dsimansk** [comment]
@knative/eventing-reviewers PTAL if the step is OK to be removed. Thanks!

**Comment by gabo1208** [comment]
What is deprecated is to create a RabbitMQ Broker without a RabbitMQConfig but not the Broker, so this is completely valid still :)

**Comment by vincent0426** [comment]
Oh, my bad. May I ask what makes the change to create both brokerConfig and broker instead of putting brokerConfig right into broker? Thanks!

**Pull request closed without merging**
