### PR TITLE
Fixes #11810 

### PR DESCRIPTION
**Pull request by jinxin-fu**
bug fix according to https://github.com/open-telemetry/opentelemetry-collector/issues/3845.

fix error:
'service.extensions[0]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[health_check: pprof: zpages:]'

"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

Fixes #11810 
-
-
-

### CODE REVIEW

**Comment by jinxin-fu** [comment]
@googlebot I signed it!

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
