### PR TITLE
Small typo in docs/eventing/getting-started.md

### PR DESCRIPTION
**Pull request by xtreme-sameer-vohra**
## Proposed Changes
Fix small typo - pluralize consumers

### CODE REVIEW

**Comment by csantanapr** [comment]
/lgtm

Thanks for the contribution but you need to fix the bot error with the CLA, you need to have the email associated with the commit in the CLA system
More help here https://github.com/knative/docs/blob/master/CONTRIBUTING.md#contributor-license-agreements

**Review by grantr — APPROVED** [review]
/lgtm

**Comment by grantr** [comment]
/ok-to-test

Thanks for fixing this @xtreme-sameer-vohra!

**Pull request merged**
