### PR TITLE
Fixes link descriptions in serving API docs

### LINKED ISSUE #3143: Fix link descriptions in serving API docs
Re the comments here: https://github.com/knative/docs/pull/3141#discussion_r556715205
Some of the links in the API docs are poorly formatted.
Current example:
```
<a href="https://docs.google.com/presentation/d/10KWynvAJYuOEWy69VBa6bHJVCqIsz1TNdEKosNvcpPY/edit">https://docs.google.com/presentation/d/10KWynvAJYuOEWy69VBa6bHJVCqIsz1TNdEKosNvcpPY/edit</a></p>
```
would be better as:
```
<a href="https://docs.google.com/presentation/d/10KWynvAJYuOEWy69VBa6bHJVCqIsz1TNdEKosNvcpPY/edit">Knative pluggability presentation</a></p>
```

There are multiple examples of this in `docs/reference/api/serving.md`
The links should be updated in this file so that they show a description of the link instead of a long, messy URL.

### PR DESCRIPTION
**Pull request by omerbensaadon**
Fixes #3143

### CODE REVIEW

**Review by evankanderson — COMMENTED** [review]
Is this generated by the process here?

https://github.com/knative/docs/tree/master/docs/reference/api#generating-the-api

**Comment by abrennan89** [comment]
@evankanderson just discussing this in Slack atm

**Comment by omerbensaadon** [comment]
Hey sorry, unsure what to do here to make this passable

**Pull request closed without merging**
