### PR TITLE
added github.com/maximilien/knfun as a Knative client demo sample

### LINKED ISSUE #2131: Add more `kn` client workflow samples and examples
**Describe the change you'd like to see**

Add more sample workflows and examples using `kn` client with Knative

### PR DESCRIPTION
**Pull request by maximilien**
Fixes #2131

## Proposed Changes
- create new `kn` client section in community samples
- add [knfun](https://github.com/maximilien/knfun) to the community samples

### CODE REVIEW

**Comment by samodell** [comment]
Thanks, @maximilien ! Let's remove the "languages" section from the table in the new Client section, since it doesn't seem relevant there. Other than that, LGTM!

**Comment by maximilien** [comment]
Thanks @samodell. Updated.

**Comment by maximilien** [comment]
Looks like failing checks due to:

```bash
community/samples/README.md
	ERROR	../../contributing/DOCS-CONTRIBUTING.md
		Stat contributing/DOCS-CONTRIBUTING.md: no such file or directory
```
the `DOCS-CONTRIBUTING.md` does not exist. So I linked it to the directory.

**Comment by samodell** [comment]
Sorry, @maximilien ; that page was moved into the Community repo; you can update the link to https://github.com/knative/community/blob/master/DOCS-CONTRIBUTING.md

**Comment by samodell** [comment]
Excellent, thanks!

/approve
/lgtm

**Pull request merged**
