### PR TITLE
Document xip.io with ambassador.

### PR DESCRIPTION
**Pull request by mattmoor**

### CODE REVIEW

**Comment by mattmoor** [comment]
/hold
Note that I have been unable to verify this due to: https://github.com/datawire/ambassador/issues/1871

I'm going to hold this until I'm sure someone from Ambassador has taken a look.

It is also notable that this is part of a broader push to move our "setup" to take users through to functioning DNS, so that the samples are (much) simpler.

**Comment by mattmoor** [comment]
/hold cancel

Fixes are needed upstream for this, but AFAIK there is nothing wrong with this PR.

**Comment by kflynn** [comment]
FTR, I looked this over, and I think it looks good from the Ambassador side. We'll keep you posted on upstream fixes!

**Comment by mattmoor** [comment]
Thanks @kflynn

**Pull request merged**
