### PR TITLE
updating ApiServerSource example to use v1

### LINKED ISSUE #2879: Update ApiServerSource docs to use v1
## What is changing? (Please include as many details as possible.)
In 0.19, we are promoting ApiServerSource to v1.
We should update the docs accordingly.

## How will this impact our users?
They will be able to start using ApiServerSource in v1

## In what release will this take happen (to the best of your knowledge)?
0.19

## Context
Link to associated PRs or issues from other repos here.

1. knative/eventing#4166, which has all the PRs linked to.

### PR DESCRIPTION
**Pull request by capri-xiyue**
Fixes #2879 
Helps with knative/eventing#4166

## Proposed Changes 

- Updating ApiServerSource example to use v1
-
-

### CODE REVIEW

**Comment by capri-xiyue** [comment]
assign @nachocano 
assign @lionelvillard

**Comment by capri-xiyue** [comment]
assign @samodell

**Comment by lionelvillard** [comment]
@capri-xiyue can you also update this page: https://github.com/knative/docs/blob/master/docs/eventing/sources/apiserversource.md ?

**Comment by capri-xiyue** [comment]
> @capri-xiyue can you also update this page: https://github.com/knative/docs/blob/master/docs/eventing/sources/apiserversource.md ?

done

**Comment by lionelvillard** [comment]
Do you mind changing the badge?

**Comment by lionelvillard** [comment]
no I mean the APIVersion badge at the very top of the `apiserversource.md` page.

**Comment by capri-xiyue** [comment]
> no I mean the APIVersion badge at the very top of the `apiserversource.md` page.

Done

**Comment by lionelvillard** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
