### PR TITLE
Delete duplicate deploying-from-private-registry.md file

### LINKED ISSUE #4145: Delete duplicate page
There are two versions of [Deploying images from a private container registry](https://knative.dev/docs/developer/serving/deploying-from-private-registry/) in the repo `/docs/serving/deploying-from-private-registry.md` and `/docs/developer/serving/deploying-from-private-registry.md`. 

Remove the version in the Serving guide and add any updates to that file to the version in the developer guide.

### PR DESCRIPTION
**Pull request by snneji**
Fixes #4145

### CODE REVIEW

**Comment by abrennan89** [comment]
@snneji it looks like this one needs a rebase

**Comment by sebgoa** [comment]
looks like it got rebased.

/lgtm

**Review by abrennan89 — APPROVED** [review]
/lgtm

**Pull request merged**
