### PR TITLE
Add any-k8s instructions, thanks to jbeda for the suggestion.

### PR DESCRIPTION
**Pull request by evankanderson**
## Proposed Changes

* This is the install instructions without "how to set up k8s". (Copied from PKS, just for the record)

### CODE REVIEW

**Comment by rgregg** [comment]
Awesome! Can you add a link to this from install/README.md in this PR too?

**Comment by evankanderson** [comment]
D'oh, I totally meant to add that to the same commit.

**Comment by alexellis** [comment]
This looks good, I was just using the GKE version and starting half way down :+1:

**Pull request merged**
