### PR TITLE
Removed Kafka Binding doc and its references

### PR DESCRIPTION
**Pull request by CodesbyUnnati**
## Proposed Changes 

- Have removed the outdated [Readme.md](https://github.com/knative/docs/blob/main/code-samples/eventing/kafka/binding/README.md) file of Kafka Binding.
- Removed the reference of Kafka Binding from [docs/sample/eventing.md](https://github.com/CodesbyUnnati/docs/blob/main/docs/samples/eventing.md) file

### CODE REVIEW

**Comment by pierDipi** [comment]
Thanks @CodesbyUnnati

**Comment by CodesbyUnnati** [comment]
Hi @csantanapr @pmbanugo Can you please review this PR 😄

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
