### PR TITLE
undo adding explicit install command for in-memory channel provisioner

### PR DESCRIPTION
**Pull request by samodell**
Undo #944

### CODE REVIEW

**Comment by RichieEscarez** [comment]
sorry been heads down. whats the context for the removal? is there a related issu?

**Comment by samodell** [comment]
Content is in a comment on #944 -- you don't need to explicitly install the in-memory channel provisioner if you install eventing using release.yaml, because release.yaml comes with it. And release.yaml was what all the install guides currently have users install. You'd only need to install the in-memory channel provisioner separately if you installed eventing.yaml to begin with.

**Comment by samodell** [comment]
/hold

Mark did install from release.yaml, which should have included the in-memory channel provisioner but apparently did not... Investigation is ongoing in #944

**Comment by samodell** [comment]
As confirmed in #968  , it isn't necessary to install the in-memory channel provisioner explicitly. Closing this and opening a new PR to delete the extra unnecessary line.

Installs may still fail the first time through with errors like:
```
unable to recognize "https://github.com/knative/serving/releases/download/v0.4.0/serving.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/build/releases/download/v0.4.0/build.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/build/releases/download/v0.4.0/build.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/build/releases/download/v0.4.0/build.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/build/releases/download/v0.4.0/build.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/eventing/releases/download/v0.4.0/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/eventing/releases/download/v0.4.0/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1"
```

If you see these kinds of errors, run the install commands again to resolve the problem. See #968 for background on what's causing the issue. We also plan to fix this problem in v0.5; to track the fix, see #1036

**Pull request closed without merging**
