### PR TITLE
Split mkdocs config into separate files

### LINKED ISSUE #3797: Decompose `mkdocs.yml` into `mkdocs.yml` + `navigation` + `redirects`
## Description: 
We would like to split up the mkdocs.yml into `main`, `navigation`, and `redirects` in order to make it more manageable + scriptable. 

---

## Story
```
As Carlos the Contributor 
I want mkdocs.yaml split into three different files 
So that mkdocs.yaml is less of a cluster 
And is nicer to look at and work with 
```

## Acceptance Criteria

- [ ] `Separate mkdocs.yml`
```
GIVEN I have pulled the PR for this issue to my local machine
WHEN I look at the /docs files
THEN I see that mkdocs.yml has been separated into `mkdocs.yml`, `navigation` and `redirects`
```

---

- [ ] `Sanity Check`
```
GIVEN I have pulled the PR for this issue to my local machine
WHEN I do `mkdocs serve` in my CLI
THEN the website renders locally without error 
AND the site the PR preview renders without error 
```

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [x] New Contributors

### PR DESCRIPTION
**Pull request by benmoss**
Fixes #3797

### CODE REVIEW

**Comment by omerbensaadon** [comment]
/lgtm 
/approve 

Thanks Ben this is awesome

**Comment by kvmware** [comment]
Don't know how the inherit works (looks like the inherit is above a few lines of where the removed code was), but awesome that files are getting split out to something more manageable!

**Comment by julz** [comment]
I think this may have broken redirects unfortunately :(

**Comment by omerbensaadon** [comment]
This was sloppy acceptance on my part… apologies

**Comment by julz** [comment]
Not sure _why_ it doesn't work.. maybe we have to have it be plugins.yml instead of redirects.yml to make the merge easier or something?

**Comment by julz** [comment]
Ok yeah I see the problem. The inheritance only works with maps not lists, and the plugins section is specified as a list. I can take a crack fixing this.

**Comment by julz** [comment]
This should fix it https://github.com/knative/docs/pull/3933 🤞

**Pull request merged**
