### PR TITLE
Fix rendering issues due to nested shortcodes

### LINKED ISSUE #1459: Knative Eventing sources rendering issues (docs/eventing/sources/readme.md)
This page renders considerably worse than the version that shows on GitHub. We should figure out how we can tweak the markdown to be more consumable on the website.

https://knative.dev/docs/eventing/sources/

### PR DESCRIPTION
**Pull request by RichieEscarez**
Fixes #1459, #1472

- Prevent nesting multiple shortcodes (stop double Markdown processing).
- For "Hugo page bundles", move frontmatter into README.md files
- Switch all README.md filenames to index.md
- Force whitespace in readmetemplate.gomd

In addition, these changes enable us to:
- Use "code includes" in all samples (https://github.com/knative/website/pull/63)

Dependent change: https://github.com/knative/website/pull/62

### CODE REVIEW

**Comment by rgregg** [comment]
Looks like the bulk of this is just adding front-matter to the README.md files and removing the "placeholder" _index.md files? Is there work in the website repo that converts the README.md files back into index files?

**Comment by RichieEscarez** [comment]
> Looks like the bulk of this is just adding front-matter to the README.md files and removing the "placeholder" _index.md files? Is there work in the website repo that converts the README.md files back into index files?

Yes, thats here: https://github.com/knative/website/pull/62/files#diff-798240f4b6c6cb67c4a9268174ffc7a0R100

**Comment by rgregg** [comment]
Got it, thanks!

**Comment by RichieEscarez** [comment]
All of these changes are staged here: https://prstaging--knative-v1.netlify.com/docs/

My testing is complete and all topics are building as expected without any unwanted character or HTML comments.

Testing did surface lots of broken links we need to fix https://github.com/knative/docs/issues/1633

This PR is ready to go but I have to wrap up tests for the dependent change in https://github.com/knative/website/pull/62 (updated build script)

**Pull request merged**
