### PR TITLE
Update links and descriptions of TriggerMesh sources

### PR DESCRIPTION
**Pull request by antoineco**
## Proposed Changes

- Update list of AWS event sources maintained by TriggerMesh
- Fix dead links for the Slack and Zendesk event sources (also maintained by TriggerMesh)

cc @omerbensaadon

### CODE REVIEW

**Review by snneji — COMMENTED** [review]
Looks like an improvement to me. I suggested that you change "a" to "an" in a few locations.

Also, it's good practice to spell out abbreviations such as AWS SNS on first use. For example, the [Amazon website](https://aws.amazon.com/sns/?whats-new-cards.sort-by=item.additionalFields.postDateTime&whats-new-cards.sort-order=desc) uses "Amazon Simple Notification Service (Amazon SNS)" on first use. Not sure if you want to use that here, or if there is a good reason to make an exception to the rule for spelling out abbreviations.

**Comment by csantanapr** [comment]
Thanks, @snneji for the review ❤️ 

/hold

**Comment by antoineco** [comment]
@snneji About the acronyms, that's a good suggestion. The reason why I didn't spell them out is because I have personally never seen anyone referring to Amazon SNS as "Amazon Simple Notification Service". I would even bet a lot of people wouldn't immediately connect the dots if we phrased it that way.

Second reason, it's a table, so very long names like that would their 2 lines, but I'm really just bikeshedding on that one.

The final decision is yours :)

**Comment by omerbensaadon** [comment]
thank you @antoineco 🥇

**Comment by csantanapr** [comment]
I have to agree with @antoineco this AWS services are better known by their acronyms like S3 and SQS and  itself

**Comment by csantanapr** [comment]
@snneji 

You would need to comment on this PR with “@googlebot I consent” to make the CLA bot happy

**Comment by snneji** [comment]
Sure, since you want to save space in the table making an exception for these abbreviations is OK.

**Comment by antoineco** [comment]
The length wasn't my main argument here.

**Pull request merged**
