### PR TITLE
operator install prereq kubernetes 1.16 minimum version

### PR DESCRIPTION
**Pull request by csantanapr**
Updates the minimum version of kubernetes on the operator page

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
@abrennan89 mind looking here for approvals?

**Comment by matzew** [comment]
@samodell @abrennan89  any chance to look here ?

**Comment by abrennan89** [comment]
/lgtm
/approve
@matzew sorry for the delay, just saw this :slightly_smiling_face:

**Pull request merged**
