### PR TITLE
Changes all references of `kn quickstart` to `kn-quickstart`

### LINKED ISSUE #4261: Typo in Knative Quickstart
The command should be kn-quickstart (hyphen to be included) in the step "Install Knative and Kubernetes on a local Docker Daemon using..." under section 'Install the Knative "Quickstart" environment.'   Here, https://knative.dev/docs/getting-started/ .

### PR DESCRIPTION
**Pull request by JeffNeff**
Fixes #4261 

## Proposed Changes 

- Changes references of `kn quickstart` to `kn-quickstart` in both `blog/releases/announcing-knative-v0-25-release.md ` and `docs/snippets/quickstart-install.md`

### CODE REVIEW

**Comment by psschwei** [comment]
/hold

I think the user experience we were aiming for was using the plugin as part of the `kn` client (i.e. `kn quickstart`, not `kn-quickstart`). @omerbensaadon @csantanapr please confirm I'm remembering things right.

**Comment by csantanapr** [comment]
Correct @psschwei

**Comment by psschwei** [comment]
I don't think a doc change is needed (`kn quickstart` without a hyphen is what we want), so this issue/PR can be closed.

**Comment by snneji** [comment]
Thanks for the PR @JeffNeff. I'm going to close it because the issue was resolved without needed docs changes.

**Pull request closed without merging**
