### PR TITLE
links and landing pages for all samples

### PR DESCRIPTION
**Pull request by RichieEscarez**
Add crossing link for all samples, create a main code samples page, and add some consistency:

- Add "Code samples" landing pages:
   - "all code samples" at top level in nav (new)
   - community (edit)
   - serving (edit)
   - build (new)
   - eventing (edit)

- Ensure "Code samples" shows toward the bottom of each section in the nav tree

- Shallow pass at consistent use of "code sample" (vs sample app)

Issue: #1213

### CODE REVIEW

**Comment by RichieEscarez** [comment]
https://5cbaac932a7aed0008125aa3--knative-v1.netlify.com/docs/samples/
https://5cbaac932a7aed0008125aa3--knative-v1.netlify.com/community/samples/
https://5cbaac932a7aed0008125aa3--knative-v1.netlify.com/docs/build/samples/
https://5cbaac932a7aed0008125aa3--knative-v1.netlify.com/docs/eventing/samples/
https://5cbaac932a7aed0008125aa3--knative-v1.netlify.com/docs/serving/samples/

**Comment by samodell** [comment]
@RichieEscarez  should we standardize on a look for these sample landing pages? The Serving page has a prominent table, and then the Eventing and Build pages don't.

**Comment by RichieEscarez** [comment]
> @RichieEscarez should we standardize on a look for these sample landing pages? The Serving page has a prominent table, and then the Eventing and Build pages don't.

I thought about that but decided to focus only on surfacing everything with this round. I think the formatting and consistency can be something we cover in our IA efforts.

**Pull request merged**
