### PR TITLE
Update install instructions to use release 0.1.0 files

### LINKED ISSUE #286: Use 0.1.0 in setup instructions
Our setup instructions point at a nightly release, these should reference our 0.1.0 release.

e.g. https://github.com/knative/docs/blob/master/install/Knative-with-AKS.md#installing-knative-serving

### PR DESCRIPTION
**Pull request by trisberg**
Fixes #286

## Proposed Changes

* Update install instructions to use files from the Serving 0.1.0 release instead of latest

### CODE REVIEW

**Comment by samodell** [comment]
Curious about the rationale behind this change -- why is /latest/ no longer a good strategy? @trisberg 

If we swap out latest for a specific version number, we'll need to update these commands regularly moving forward.

**Comment by mattmoor** [comment]
@samodell it's a function of stability and putting our best foot forward for newcomers.

We know these samples work with 0.1.0, but now we might make breaking changes (intentionally or not).  I don't want prospective users to have a bad experience because of a bad nightly release the day before.

Does that make sense?  WDYT?

**Comment by samodell** [comment]
Makes sense! Definitely agree we want to always direct users to stable versions. Would it be possible to have a "latest-stable" pointer similar to "latest" instead of hard-coding the versions? I don't know the complexity that might be involved, but if it's not a huge amount of work it might be worth it. @mattmoor

**Comment by mattmoor** [comment]
cc @adrcunha 

I think the question is how we define "stable" :)

/hold cancel

**Comment by krancour** [comment]
And if it's perceived as a maintenance burden to update docs with each release... that can always be automated.

**Comment by rgregg** [comment]
Glad we're making this change. 

/lgtm

**Pull request merged**
