### PR TITLE
Incorporate static version of old docs in to site

### PR DESCRIPTION
**Pull request by julz**
Built via manual ./scripts/build.sh of website and then copied over (added a version warning banner in the process, happy to iterate the css for that).

Each release we get to delete one of these docs directories (and the corresponding copy in build.sh) until they all disappear.

Also unpicked the netlify proxy redirects since we now have static html built instead.

Fixes https://github.com/knative/docs/issues/3864
Fixes https://github.com/knative/docs/issues/3801

/assign @omerbensaadon @csantanapr

### CODE REVIEW

**Comment by julz** [comment]
oh annoying, the static files have some approvers files in them, lemme delete

/hold

**Comment by omerbensaadon** [comment]
Am I correct in thinking that all of the static sites for the old versions will be thrown into a folder called `old docs`? 

I think everything looks good, but can we change the name of that folder to `previous versions` or something like that?

**Comment by omerbensaadon** [comment]
Assuming the "latest version" link points to knative.dev on purpose and at launch it will simply link to the homepage

**Comment by omerbensaadon** [comment]
tried to break it, failed! 

Will lgtm after folder name change :D

**Comment by julz** [comment]
Yeah I put them in old-docs, I can make it previous-docs (or archived-docs?) instead easily enough yeah

**Comment by omerbensaadon** [comment]
let's go with archived-docs, because that's really what they are

**Comment by julz** [comment]
(Yeah I was lazy and didn't want to figure out how to make hugo output the right url, so I hard-coded it, should probably make it /docs/ instead actually though)

**Comment by omerbensaadon** [comment]
@julz oh no there is a linting error

**Comment by omerbensaadon** [comment]
Looks like you are missing a new line at the end of each file

**Comment by julz** [comment]
Ugh yeah, that's a pain, those are generated files 🤔 we probably need to tell the lint robot to ignore these directories

**Comment by omerbensaadon** [comment]
What Slack channel should I post this in? #productivity?

**Comment by julz** [comment]
I can look at PRing it later/tomorrow, I think we just need to add archived/ to the list of ignored dirs here: https://github.com/knative-sandbox/.github/blob/main/workflow-templates/knative-style.yaml#L203

**Comment by julz** [comment]
Ooh actually, looks like we might be able to just use .gitattributes to mark the dir as generated, lemme try that

**Comment by julz** [comment]
.. looks like that did it \o/

**Comment by omerbensaadon** [comment]
/lgtm 

🥳

**Pull request merged**
