### PR TITLE
show site feedback information

### LINKED ISSUE #3800: Communicate to users that the `mkdocs` site is in public beta, link them to docs issues for feedback
## Description: 
While we've done a great job on the MkDocs Site, we want users to understand that they are using a site that is recently "hot off the presses" in order to incentivize users to provide feedback on the site as well as excuse any "work in progress" sections. 

Looks like Material for MkDocs has something called an ["announcement bar"](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#announcement-bar) which we can leverage! 

---

## Story
```
As Ursula the User 
I want to understand that I am using a Beta version of the Knative Site
So that set my expectations are set accordingly 
```

## Acceptance Criteria

- [ ] `Visit the Site`
```
GIVEN I have started a fresh session on the Knative site 
WHEN I look up at the top of the page 
THEN I see a banner letting me know the site is in Beta
AND I see the text below: 
```

`Welcome to the new Knative.dev!` ⚠️ `Pardon our progress, if you find any issues with this site, please submit them here!`

---
- [ ] `Click Banner`
```
GIVEN I have started a fresh session on the Knative site 
AND I see the banner at the top of the page
WHEN I click on the banner anywhere except the "x" 
THEN https://github.com/knative/docs/issues/new/choose opens in a new tab
```

----
- [ ] `Click the x` 
```
GIVEN I have started a fresh session on the Knative site 
AND I see the banner at the top of the page
WHEN I click the "x" on the banner
THEN the banner disappears 
```

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [x] New Contributors

### PR DESCRIPTION
**Pull request by shinigambit**
Fixes #3800

### CODE REVIEW

**Comment by kvmware** [comment]
LGTM

**Comment by julz** [comment]
one small issue with this -- the close button isn't persistent, so if you close the banner and click a link it's right back again in the next page. I think it's better to just drop the close button since it's not permanent.

**Comment by julz** [comment]
(apart from that it looks super cool, thanks!)

**Comment by omerbensaadon** [comment]
ooo agreed with Julz on this

**Comment by julz** [comment]
one other piece of feedback.. I find the "report it here" quite confusing when there's no obvious link underlining anywhere. I eventually hover and see my pointer change, but it initially looks like we forgot to link the "here". Could we maybe put the <a> tag _inside_ the paragraph rather than making the whole banner clickable?

**Review by julz — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
