### PR TITLE
Add automated link checking

### PR DESCRIPTION
**Pull request by benmoss**
## Proposed Changes 

- Add a daily build that checks all the links and posts an alert to Slack if it fails (example run here: https://github.com/benmoss/docs/actions/runs/994372503)
- Add a PR build that just checks links that have changed in the PR

The daily build will only run when mkdocs is merged to main, since periodic actions only run on the default branch

We'll want to update the `base-branch` too when we merge it into main.

### CODE REVIEW

**Comment by omerbensaadon** [comment]
dude heck yeah this seems awesome

**Comment by omerbensaadon** [comment]
How can I test this...?

**Comment by benmoss** [comment]
If you want to make a PR to https://github.com/benmoss/docs/tree/mkdocs I've already got it installed there

**Comment by benmoss** [comment]
https://github.com/benmoss/docs/pull/2

**Comment by omerbensaadon** [comment]
badass!! thank you

**Pull request merged**
