### PR TITLE
Added cncf incubation notice

### PR DESCRIPTION
**Pull request by gabo1208**
Fixes [This issue](https://github.com/knative/community/issues/956)

## Proposed Changes 

- 🎁 Added cncf incubation notice section to docs homepage

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
Looks nice. 

One question on the section order: what do you think about swapping the CNCF and "What's Next" sections? I kind of like having "What's Next" as the last one (and also the color flow of white / blue /black for the section backgrounds).

That said, this is N=1 and I don't feel super strongly about it, so feel free to reject :)

**Comment by csantanapr** [comment]
@gabo1208 can you make it smaller in height, I think it looks huge.
image

What about 1/3rd of the size?
image

**Review by psschwei — COMMENTED** [review]
I like it!

/lgtm

**Pull request merged**
