### PR TITLE
v0.11.0 serving, eventing, eventing-contrib API reference docs

### PR DESCRIPTION
**Pull request by bbrowning**
## Proposed Changes

Generated API reference docs for v0.11.0 using the fix from #2054

### CODE REVIEW

**Comment by RichieEscarez** [comment]
Note: these docs were build with the updated script in #2054 
(`KNATIVE_SERVING_COMMIT=v0.11.0 KNATIVE_EVENTING_COMMIT=v0.11.0 KNATIVE_EVENTING_CONTRIB_COMMIT=v0.11.0 ./gen-api-reference-docs.sh`)

**Comment by bbrowning** [comment]
Rebased against latest master to fix conflicts

**Comment by RichieEscarez** [comment]
Staging build looks good, just awaiting the LGTM for the changes in #2054 
https://5df42f87a20218f204084c22--knative.netlify.com/docs/reference/

**Comment by RichieEscarez** [comment]
cherrypick for v0.11: https://github.com/knative/docs/pull/2059

**Pull request merged**
