### PR TITLE
updated to hyper v0.14.7 and rust v1.51.0

### PR DESCRIPTION
**Pull request by 06chaynes**
Updates hyper to v0.14.7 and Rust to v1.51.0.

@slinkydeveloper

### CODE REVIEW

**Comment by 06chaynes** [comment]
> @googlebot I signed it!

**Review by slinkydeveloper — APPROVED** [review]
/lgtm

Nice, thanks for your contrib!

**Comment by abrennan89** [comment]
/approve

Thanks @06chaynes 😄

**Pull request merged**
