### PR TITLE
Repair 'docker build failed' in sample 'knative-routing-go'

### PR DESCRIPTION
**Pull request by ysjjovo**
#Command 'docker build' in sample 'knative-routing-go' got error below.
```
[docker build stage begin.]
Sending build context to Docker daemon 74.24kB
Step 1/8 : FROM golang AS builder
latest: Pulling from library/golang
Digest: sha256:f421eca72e1cf10ef70411d3a73e346ff7f9fc0e5fdd49851c08c92497f80304
Status: Downloaded newer image for golang:latest
---> 272e3f68338f
Step 2/8 : WORKDIR /go/src/github.com/knative/docs/
---> ff955f99eaa3
Removing intermediate container df813ca0da22
Step 3/8 : ADD . /go/src/github.com/knative/docs/
---> cb04af0880c3
Removing intermediate container 3b123175f60e
Step 4/8 : RUN CGO_ENABLED=0 go build ./docs/serving/samples/knative-routing-go/
---> Running in ebad0941239a
can't load package: package github.com/knative/docs/docs/serving/samples/knative-routing-go: cannot find package "github.com/knative/docs/docs/serving/samples/knative-routing-go" in any of:
/usr/local/go/src/github.com/knative/docs/docs/serving/samples/knative-routing-go (from $GOROOT)
/go/src/github.com/knative/docs/docs/serving/samples/knative-routing-go (from $GOPATH)
The command '/bin/sh -c CGO_ENABLED=0 go build ./docs/serving/samples/knative-routing-go/' returned a non-zero code: 1
{"exitCode":8, "message":"docker build failed or timeout "}
```

### CODE REVIEW

**Comment by ysjjovo** [comment]
@googlebot I signed it!

**Comment by ysjjovo** [comment]
Why tests status is always waiting.

**Comment by evankanderson** [comment]
I think this sample is intended to be run from a $CWD of the root directory of the entire repo, and to rely on the `vendor/` directory there.

It looks like this changes the Dockerfile to map the sample directory into the root, but you'll need to change the [Setup step 3 command](https://github.com/knative/docs/blob/master/docs/serving/samples/knative-routing-go/README.md#setup)

If you want to covert this to `go mod` format, that might make more sense when rewriting the Dockerfile.

**Comment by mpetason** [comment]
Tested what @evankanderson was saying and it does look like it works if you run it from the root directory. The paths will actually match up and work. It is confusing running it from knative-docs/ instead of access it via the samples directory. I would also recommend updating the documentation to match the Dockerfile if this is going to be built from the knative-routing-go sample folder instead. 

```
$ docker build \
>   --tag "${REPO}/knative-routing-go" \
>   --file=docs/serving/samples/knative-routing-go/Dockerfile .
Sending build context to Docker daemon  77.29MB
Step 1/8 : FROM golang AS builder
 ---> 2421885b04da
Step 2/8 : WORKDIR /go/src/github.com/knative/docs/
 ---> Using cache
 ---> 8d2757472759
Step 3/8 : ADD . /go/src/github.com/knative/docs/
 ---> b06712053dcb
Step 4/8 : RUN CGO_ENABLED=0 go build ./docs/serving/samples/knative-routing-go/
 ---> Running in abe24d6f4c9c
Removing intermediate container abe24d6f4c9c
 ---> ec266fc3219d
Step 5/8 : FROM gcr.io/distroless/base
latest: Pulling from distroless/base
24f0c933cbef: Pull complete 
69e2f037cdb3: Pull complete 
Digest: sha256:2b0a8e9a13dcc168b126778d9e947a7081b4d2ee1ee122830d835f176d0e2a70
Status: Downloaded newer image for gcr.io/distroless/base:latest
 ---> c4c70323b0c2
Step 6/8 : EXPOSE 8080
 ---> Running in 2cf5a36a0054
Removing intermediate container 2cf5a36a0054
 ---> 64d3bfc0755e
Step 7/8 : COPY --from=builder /go/src/github.com/knative/docs/knative-routing-go /sample
 ---> 1a2dadd238b9
Step 8/8 : ENTRYPOINT ["/sample"]
 ---> Running in dce4bb91df91
Removing intermediate container dce4bb91df91
 ---> f8e5811ef09d
Successfully built f8e5811ef09d
Successfully tagged mpetason/knative-routing-go:latest
```

**Comment by evankanderson** [comment]
We should move this example to `go mod` and allow it to be run from the sample directory rather than repo root.

**Pull request closed without merging**
