### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kaiass**
KafkaSource sasl type is specified as 'saslType' config parameter but should be 'type'.

"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-
-
-

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
Yes, this is correct, reference: https://github.com/knative-sandbox/eventing-kafka/blob/3992a225fc57927c9b0dcfc4fcdb6b4e17db2a11/pkg/apis/bindings/v1beta1/kafka_types.go#L60-L62

Thanks for the fix @Kaiass!

/lgtm

**Comment by Kaiass** [comment]
@pierDipi  Glad to help!

**Pull request merged**
