### PR TITLE
Add .md extension to internal links

### LINKED ISSUE #4201: Add .md to internal links in the help folder
Add `.md` to every relative link in the files in the [`docs/help/`](https://github.com/knative/docs/tree/mkdocs/docs/help) folder. (Do not add it to absolute links.)

**Detail:** Many of our internal links lack the .md extension. That made sense for Hugo but it doesn't for MkDocs and our link checker bot.

### PR DESCRIPTION
**Pull request by RichardJJG**
Fixes #4201

### CODE REVIEW

**Comment by RichardJJG** [comment]
I know one of the "fixes" is in dummy text within a template topic, but even there it's worth writing the links as we expect them to be written in actual docs.

**Review by abrennan89 — APPROVED** [review]
/lgtm

**Pull request merged**
