### PR TITLE
Blue-green deployment update for 0.8

### LINKED ISSUE #1489: blue/green deployment tutorial should use new v1beta1 API shape
Knative version 0.6+
https://knative.dev/docs/serving/samples/blue-green-deployment/

Doing blue green deployment is done via:
- Using *one* Service object.
- Controlling the revision names
- Updating the traffic section with the revision names and percentages

### PR DESCRIPTION
**Pull request by meteatamel**
Updated blue-green deployment sample with Knative 0.8 instructions

Fixes #1489

### CODE REVIEW

**Comment by sebgoa** [comment]
I tested this, this is good.

/lgtm

**Comment by dgerd** [comment]
/assign @mattmoor 

Hrmmm.. I don't have approvers for this branch.

**Pull request merged**
