### PR TITLE
Update Java samples

### PR DESCRIPTION
**Pull request by brunoborges**

### CODE REVIEW

**Comment by brunoborges** [comment]
TODO: update the acual doc articles that contain step-by-step instructions.

**Comment by snneji** [comment]
> TODO: update the acual doc articles that contain step-by-step instructions.

Hi @brunoborges, thanks for the PR! Do you plan to update the instructions as part of this PR or are you going to submit another one?

**Comment by snneji** [comment]
Hi @brunoborges, we have moved the location of code samples. They are now located here: https://github.com/knative/docs/tree/main/code-samples/serving

**Comment by brunoborges** [comment]
I'll start fresh in the near future then. Thanks!

**Pull request closed without merging**
