### PR TITLE
implemented the new case study section of the home page

### LINKED ISSUE #6031: implement the case study section of the home page .
implement the case study section of the home page according to the new proposed design

### PR DESCRIPTION
**Pull request by ShravaniAK**
Fixes #6031 

implemented the new design of the case study section , did the following changes
1. changed the background color of each case study to white.
2. changed the font family and removed the italic style. 
3. added margin and padding .
4. Changed the color of the horizontal line and the font.
5. added box shadow effect on Hover .

Before :
Screenshot 2024-06-28 at 2 40 41 PM

After:
Screenshot 2024-06-28 at 2 40 55 PM

### CODE REVIEW

**Comment by Cali0707** [comment]
Hey @zainabhusain227 @mmejia02 when you have some time can you compare the preview to the designs and leave any feedback here?

**Review by Cali0707 — CHANGES_REQUESTED** [review]
Hey @ShravaniAK , feedback on these changes from todays UX WG review was:
1. There should be a larger padding at the top of the case study boxes so that there is a bit more space between the company logo and the border of the box
2. There should be more space between the "Knative is a [Cloud Native Computing Foundation](https://www.cncf.io/) incubation project" text and the "Case Studies" section
3. For the hover effect on the individual case studies, we should only change the border colour, and not do any box shadow. We should also add a transition to this so that it animates nicely
4. The entire case study box should use the pointer for the mouse, and should be clickable and take users to the case study page. Currently, this only works if users click on the text in the box.
5. We should incorporate the arrows from the design in https://github.com/knative/ux/issues/146

Thanks for all your work on this so far, once we have these fixes this should be good to merge

**Comment by ShravaniAK** [comment]
@Cali0707 , I have implemented all the changes requested, except for the "incorporate the arrows" , I think that it's a new feature implementation that can be made in a new separate pr.

**Comment by ShravaniAK** [comment]
Also for point 2 , I have fixed that in #6036

**Comment by Cali0707** [comment]
@ShravaniAK it looks like this has some conflicts now that your other PR merged, would you mind fixing those?

**Comment by ShravaniAK** [comment]
@Cali0707 I have fixed the conflicts!

**Comment by Cali0707** [comment]
Thanks @ShravaniAK ! There are a few issues that need fixing (see video below):

1. When hovering over a case study, some of the text is shifted by the border
2. The transition between no border and border should be animated

https://github.com/user-attachments/assets/0aecdff0-4733-478d-84b4-7dda9cff1e41

**Comment by ShravaniAK** [comment]
@Cali0707 I have fixed both the issues, can you please review them once again, Thanks!

**Review by Cali0707 — APPROVED** [review]
/lgtm
/approve

Thanks @ShravaniAK !

**Pull request merged**
