### PR TITLE
Adding Knative Eventing Example

### PR DESCRIPTION
**Pull request by salaboy**
Fixes #issue-number or description of the problem the PR solves

## Proposed Changes 

-
-
-

### CODE REVIEW

**Comment by sebgoa** [comment]
it would be nice to get a small sentence in the PR. The template is actually helpful.

**Comment by jonatasbaldin** [comment]
Awesome article, would love to have in the docs ✨

**Comment by salaboy** [comment]
is there something else required for this to be merged?

**Pull request merged**
