### PR TITLE
Add default tabs on configuring-autoscaling documentation

### LINKED ISSUE #2436: Autoexpand example section when multiple tabs are given
## Expected Behavior

Examples which have different flavors presented by tabs should already show the default presentation, like in

image

## Actual Behavior

In the current version of the new [autoscaling docs](https://knative.dev/development/serving/configuring-autoscaling/) the examples are not expanded by default, which leads to a view like:

image

For the reader is not clear whether this is already the example or what she should do. It's not obvious that you have to press a link to show the example. Also, if you press a link to reveal one of the example, you get never back to this empty view, so why not already start with the first example shown ? (the borders then make it also clear that this is tabbed view. these borders are missing in the initial view).

## Steps to Reproduce the Problem

1. Got to https://knative.dev/development/serving/configuring-autoscaling/ and check the examples

### PR DESCRIPTION
**Pull request by jonatasbaldin**
Fixes #2436 

## Proposed Changes 
- Adds the default tabs on configuring-autoscaling documentation

### CODE REVIEW

**Comment by evankanderson** [comment]
Waiting for #2411 to merge and will approve after that.

**Comment by vagababov** [comment]
We had a discussion about that and kind of agreed on no defaults, but 🤷 
/cc @julz @markusthoemmes

**Comment by markusthoemmes** [comment]
It would've been nice to get feedback via the actual working group here. I left the default tabs out deliberately to have less noise when just scrolling through the doc and searching for the setting you're looking for.

**Comment by jonatasbaldin** [comment]
Hey @markusthoemmes, sorry for that, still understanding the process for the Pull Requests :<

We can revert this if the working group believes it is better 🤔 But I agree with @rhuss that the empty tabs can be misleading if people don't click on it.

**Comment by markusthoemmes** [comment]
Yeah let's leave it as-is. I guess it's debatable anyway. I just would've liked to get the change to review.

**Comment by julz** [comment]
FWIW (I guess this is a feature request :)) I think the core problem is the CSS doesn’t properly support non-expanded tab groups, so they look confusing. The nicest fix would be if we could make it so non-expanded tab groups were less visually confusing, then we wouldn’t need to expand everything by default to work around that.

**Pull request merged**
