### PR TITLE
Add the missing section of "Installing Istio without sidecar injection"

### LINKED ISSUE #2608: Installing Istio for Knative(development/install/installing-istio.md) missed the section header for "Installing Istio Without Sidecar Injection"
## Actual Behavior
development/install/installing-istio.md missed the section header for "Installing Istio Without Sidecar Injection"

## Expected Behavior
It shouldn't

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

### PR DESCRIPTION
**Pull request by houshengbo**
Fixes #2608 

## Proposed Changes 

- This PR added the missing section of `Installing Istio without sidecar injection`.

### CODE REVIEW

**Comment by abrennan89** [comment]
@houshengbo is this just adding a new heading, or is it still WIP? :slightly_smiling_face:

**Comment by nak3** [comment]
/lgtm

@abrennan89 I am sure that it is just adding a new heading.

**Comment by abrennan89** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
