### PR TITLE
Run all knative-sample images as non root

### PR DESCRIPTION
**Pull request by karthikmurali60**
Fixes https://github.com/knative/serving/issues/14566

## Proposed Changes 

- Run all knative-sample images as non root

### CODE REVIEW

**Comment by kauana** [comment]
Hello @karthikmurali60, I'm thinking we should remove the `-S` then the adduser command since not all images run on alpine.

Thoughts @dprotaso?

**Comment by ReToCode** [comment]
+1 on the `-S` comment, other than that, good to get this in.

**Review by ReToCode — CHANGES_REQUESTED** [review]
See comments above

**Comment by prushh** [comment]
Sorry for the intrusion; I was working on this issue before that @karthikmurali60 answered me (see [comment](https://github.com/knative/serving/issues/14566#issuecomment-1807391961)).

I have a draft PR (prushh/docs#1) on my repository if you are interested.

I would like to expose some points:

- the README.md file of each project should be updated when the Dockerfile is reported;
- the containers should be tested to be sure that there are no errors at build or run time;
- why define the user twice when using multi-stage build instead of just the last stage?
- if I am not wrong, non-alpine images should use `useradd` /`groupadd` commands instead of `adduser`/`addgroup`.

Thanks for your time.

**Comment by ReToCode** [comment]
Ah, I did not get that. 

These are all very good points 👍 is it possible that you coordinate to combine your work?

**Comment by kauana** [comment]
> * if I am not wrong, non-alpine images should use `useradd` /`groupadd` commands instead of `adduser`/`addgroup`.

It seems both `useradd` and `adduser` [offer the same features](https://superuser.com/questions/547966/whats-the-difference-between-adduser-and-useradd). I would prefer keeping all images consistent, unless this is not possible for some obscure reason.

**Comment by prushh** [comment]
> Ah, I did not get that.

My bad, I started working on it since he hadn't responded for a while.

> is it possible that you coordinate to combine your work?

No problem here!

---

I would like to know if you have any preferences on the Dockerfile structure in order to standardise them a bit:

1. Is it better to have some ARG instructions containing variables (e.g. username, pid, etc.) or to specify them hardcoded in the RUN instructions? 
2. Is it okay to define the user only in the last stage when possible?
3. As @kauana suggests, we will use `adduser`/ `addgroup` commands to keep all images consistent (I thought they weren't available in some distros)
4. Is it okay to use the user directory (ex. "/home/${USER}/app") for each application?
5. What type of OS are `gcr.io/distroless/static` and `gcr.io/distroless/base` images?

**Comment by prushh** [comment]
> But if you have a draft-build pushed to a public registry I'm happy to try to run them before merging.

I pushed the _cloudevents-go_ sample using the following image definition.

<details>
<summary> Show Dockerfile </summary>

```Dockerfile
# Use the official Golang image to create a build artifact.
# This is based on Debian and sets the GOPATH to /go.
# https://hub.docker.com/_/golang
FROM golang:1.13 as builder

ARG TARGETOS
ARG TARGETARCH

# Create and change to the app directory.
WORKDIR /app

# Copy local code to the container image.
COPY . ./

# Ensure Go modules are on and create the go.mod and go.sum files.
# Also builds the binary
ENV GO111MODULE=on
RUN go mod init cloudevents.go \
    && CGO_ENABLED=0 GOOS=linux GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -v -o server

# Allows the container builds to reuse downloaded dependencies.
RUN go mod download

# Use the official Alpine image for a lean production container.
# https://hub.docker.com/_/alpine
# https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
FROM alpine:3

ARG USER=appuser
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Add a user so the server will run as a non-root user.
RUN addgroup -g $USER_GID $USER && \
    adduser -u ${USER_UID} -G $USER -D $USER && \
    apk add --no-cache ca-certificates

# Create and change to the app directory.
WORKDIR "/home/${USER}/app"

# Copy the binary to the production image from the builder stage.
COPY --from=builder /app/server ./server

# Set the non-root user as current.
USER $USER

# Run the web service on container startup.
CMD ["./server"]
```

</details>

You can find it at https://hub.docker.com/r/prushh/cloudevents-go

**Comment by ReToCode** [comment]
@prushh tested on OpenShift, works fine with a random runtime user:

```
/home/appuser/app $ id
uid=1000730000(1000730000) gid=0(root) groups=0(root),1000730000

/home/appuser/app $ ls -ltra
total 12160
drwxr-sr-x    1 appuser  appuser         17 Nov 17 15:55 ..
-rwxr-xr-x    1 root     root      12450916 Nov 17 15:55 server
drwxr-sr-x    1 root     appuser         20 Nov 17 15:55 .

/home/appuser/app $ ps
PID   USER     TIME  COMMAND
    1 10007300  0:00 ./server
   13 10007300  0:00 sh
   29 10007300  0:00 ps
```

**Comment by prushh** [comment]
@karthikmurali60 Could you please give me access to your `sample-images-non-root` branch?

Otherwise, I could create a new PR with both our commits.

**Comment by prushh** [comment]
@ReToCode How can I proceed? He hasn't answered in a while...

**Comment by ReToCode** [comment]
> @ReToCode How can I proceed? He hasn't answered in a while...

Feel free to open a new PR on your fork, referencing this PR here. I'll close this one.

**Pull request closed without merging**
