### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by ericbottard**

### CODE REVIEW

**Comment by samodell** [comment]
Thanks, @ericbottard ! We'll be able to merge this in after you sign your CLA.

**Comment by samodell** [comment]
Hey @ericbottard  -- please take a look at the bot's comments about CLAs. If you get that sorted, we can merge this.

**Comment by ericbottard** [comment]
Hmm, weird, I should already be approved via company wide Pivotal CLA

**Comment by samodell** [comment]
Hey @ericbottard  -- is there anyone you can check with on your end about the CLA?

**Comment by samodell** [comment]
This typo was just fixed in #676

**Pull request closed without merging**
