### PR TITLE
Renamed Community docs section to Contributing, added func contrib docs

### PR DESCRIPTION
**Pull request by abrennan89**
Fixes https://github.com/knative/docs/issues/4538 and https://github.com/knative/docs/issues/5048

### CODE REVIEW

**Comment by abrennan89** [comment]
@lance @nainaz FYI there are two "good first issue" labels for func - can you update this please so that it only uses https://github.com/knative-sandbox/kn-plugin-func/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fgood-first-issue (consistent with the other projects)

**Comment by lance** [comment]
> @lance @nainaz FYI there are two "good first issue" labels for func - can you update this please so that it only uses https://github.com/knative-sandbox/kn-plugin-func/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fgood-first-issue (consistent with the other projects)

✅ -  Done

**Comment by lance** [comment]
Looking at the preview, I wonder why Serving, Eventing and Client all have a Knative prefix. Should it perhaps be consistent?

**Review by psschwei — COMMENTED** [review]
/lgtm

**Comment by psschwei** [comment]
Sorry @lance , looks like Github doesn't handle concurrency quite as well as Knative :smile:

**Pull request merged**
