### PR TITLE
add approvers ux

### PR DESCRIPTION
**Pull request by csantanapr**
add approvers to OWNER

/assign @omerbensaadon

### CODE REVIEW

**Comment by omerbensaadon** [comment]
i feel it would be weird to lgtm this myself lol

**Comment by csantanapr** [comment]
it feels weirded to add the approval manually, so wanted to make it legit.
We can ask @evankanderson your ok approving this?

**Comment by csantanapr** [comment]
I think is being more than 3 months since I have been reviewing PRs and doing contribs to docs

**Comment by evankanderson** [comment]
Given the current discussion around merging the two WGs, this seems reasonable to me.

/lgtm
/approve

**Pull request merged**
