### PR TITLE
docs: add github event source install instructions

### PR DESCRIPTION
**Pull request by alex-dixon**
## Proposed Changes

- add instruction to install GitHub event source (same as GitLab example)

### CODE REVIEW

**Comment by snneji** [comment]
Hi @alex-dixon, looks like there a failing test here. Could you take a look at your git settings:

```
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az243-955.eyhnzsvkqwvufobmc3lzdbadce.jx.internal.cloudapp.net>) not allowed
```
https://github.com/knative/docs/pull/4184/checks?check_run_id=3525644621

**Comment by alex-dixon** [comment]
@snneji Weird. Not sure how to fix this one.

```
git log


commit dd7f1fbf682570b90f65573f52f4c2e43b836c58 (HEAD -> patch-1, origin/patch-1)
Author: Alex Dixon <alex.dixon@wearesalty.com>
Date:   Sun Sep 5 08:03:19 2021 -0700

    docs: add github event source install instructions

commit a07d7cfc185b61c6344764708eff18a1be9d0b2a (origin/mkdocs, origin/HEAD, mkdocs)
Author: Carlos Santana <csantana23@gmail.com>
Date:   Fri Sep 3 09:46:58 2021 -0400

    Add new release blog for v0.25 (#4152)

    * made copy using v0.24

    Signed-off-by: Carlos Santana <csantana23@gmail.com>

    * add serving release notes

    Signed-off-by: Carlos Santana <csantana23@gmail.com>

    * remove extra julz
 ````

I made the changes and the PR via the GitHub UI.

Let me know if I should close this and open a new one or however you'd like to proceed.

**Comment by alex-dixon** [comment]
@snneji Here's what I have set. 

```sh
$ git config user.name
Alex Dixon
```
```sh
$ git config user.email
alex.dixon@wearesalty.com
```

```sh
$ git config --global user.name
Alex Dixon
```
```sh
$ git config --global user.email
alex.dixon@wearesalty.com
```

**Comment by snneji** [comment]
I asked about the failing test and I think I might be able to merge this PR without it causing an issue.
/lgtm
/approve

**Pull request merged**
