### PR TITLE
Use golang:alpine instead of golang for example Dockerfile.

### PR DESCRIPTION
**Pull request by gyliu513**
This is a follow up action for https://github.com/knative/docs/pull/571

/cc @vdemeester

### CODE REVIEW

**Comment by grayside** [comment]
As I commented on #571, using alpine as the base for any "building" image means developers that iterate on top of the Dockerfile may need to add their own basic development dependencies (ca-certificates, gcc, etc)

For these non-helloworld samples, I think it's more reasonable to do that, especially since these are not using multi-stage builds. However, it would be helpful for an inline comment to point out this concern and link to relevant documentation. Perhaps https://hub.docker.com/_/golang/ with a pointer to read the section about alpine images?

**Comment by vdemeester** [comment]
@grayside sounds fair :wink:

**Comment by gyliu513** [comment]
@grayside @vdemeester done.

**Pull request merged**
