### PR TITLE
Add link to image in Dockerhub

### PR DESCRIPTION
**Pull request by steren**
Mainly for consistency with other samples.

### CODE REVIEW

**Comment by adrcunha** [comment]
Build tests are failing because:

```
I0110 23:28:26.564] serving/samples/helloworld-go/README.md:141: MD007 Unordered list indentation
```

Open the full log and you'll see this line.

**Comment by steren** [comment]
I do not see what's wrong on line 141.

Please send a commit in the branch to fix the issue, as I do not know how to fix this.

**Comment by samodell** [comment]
The documentation for the linter says that 2 spaces must be used for indented items in a list, but if you do that, it breaks the numbering for the ordered list, and the linter still had complaints about list formatting.

@adrcunha Is there a way to disable the linter but keep the link checker active? We have the Prettier bot, which does a lot of the same markdown improvements and wasn't impeding workflow.

**Pull request merged**
