### PR TITLE
Replace Bazel commands with ko

### LINKED ISSUE #403: Bazel commands in logging plugin setup
In the "Setting up a logging plugin" topic, there are bazel commands without context. 
https://github.com/knative/docs/blob/master/serving/setting-up-a-logging-plugin.md

Are you required to install and use bazel in these steps?

`# In case there is no change with the controller code`
**`bazel run config:controller.delete`**
`# Deploy the configuration for sidecar`
`kubectl apply --filename config/config-observability.yaml`
`# Deploy the controller to make configuration for sidecar take effect`
**`bazel run config:controller.apply`**

I found this commit, which removed bazel commands from knative/serving: https://github.com/knative/docs/commit/3840c7a74cf89e02bf9d4654b889fe76c895814b

Can these bazel commands just be removed too or do you need to replace these steps with other commands?

/assign @yanweiguo
-->

### PR DESCRIPTION
**Pull request by yanweiguo**
Fixes #403

### CODE REVIEW

**Comment by yanweiguo** [comment]
I'm afraid not if we have to redeploy the controller.

@mdemirhan can the controller pick up configs in config-observability.yaml dynamically? If so, then we can just remove the command.

**Comment by mdemirhan** [comment]
Talked to @mattmoor about this just now and he said config maps are already automatically reloaded when they are modified. No need to restart or redeploy the controller for the changes to be picked up. Please validate and let me know if that is not the case.

**Comment by RichieEscarez** [comment]
Sorry, I was out of office last week (and will alao be OOO most of this week). Marking as a Hold because I have wide sweeping edits in progress for this file and will incorporate these details there (including the missing instructions/links for bazel). My changes are being tracked in issus #447 .

**Comment by RichieEscarez** [comment]
Have been sidetracked with all the 0.2 release changes and need to revisit all my edits around the original 0.1 files. Just going to merge this for now and then manually deal with the merge conflict in my "in-progress" edits (#447).

/approved

**Pull request merged**
