### PR TITLE
minor edits to examples

### LINKED ISSUE #418: k8s-events sample minor mistakes
## Expected Behavior

Executing the steps in the [Readme.md](https://github.com/knative/docs/blob/master/eventing/samples/k8s-events/README.md) samples/k8s-events deploys the function.

## Actual Behavior

The [function.yaml](https://github.com/knative/docs/blob/master/eventing/samples/k8s-events/function.yaml) file instructs the user to replace {username} with their dockerhub username but the image in the example references github.com rather than docker.io. It is not obvious that the whole url needs to be changed and is inconsistent with the other samples.

Also, the command to show the yaml output in 'Understanding what happened' doesn't use the full feed name. It should read `kubectl get --output yaml feed k8s-event-flow-....`

## Steps to Reproduce the Problem

1. Execute the [steps](https://github.com/knative/docs/tree/master/eventing/samples/k8s-events) to deploy the k8s-events sample
2. 
3.

### PR DESCRIPTION
**Pull request by sjwoodman**
Fixes #418 

## Proposed Changes

* Changed github.com url for image to docker.io/{username}
* Added -.... to name of feed to indicate user needs to edit the command to include full feed name

### CODE REVIEW

**Comment by sjwoodman** [comment]
I signed it!

**Comment by bbrowning** [comment]
The integration test failure was unrelated to this change and due to an issue impacting all repos that is now fixed.

/test pull-knative-docs-integration-tests

**Pull request merged**
