### PR TITLE
Update installation documentation with Minishift

### PR DESCRIPTION
**Pull request by xeviknal**
## Proposed Changes

- Enabling admissions-webhook can be done with an add-on.
- Replacing `kubectl` commands by `oc`

### CODE REVIEW

**Comment by sebgoa** [comment]
/lgtm

need to move to 0.5.0 ( a rebase will probably do this and fix the conflict)

**Comment by xeviknal** [comment]
Changes rebased from master :)

**Comment by samodell** [comment]
There's a conflict to resolve, then we should be able to get this merged in, @xeviknal

**Comment by xeviknal** [comment]
Conflicts resolved :)

**Pull request merged**
