### PR TITLE
fix: Responsive Design Enhancements for Knative Docs Home Page

### LINKED ISSUE #5876: Responsive Design Enhancements for knative.dev Home Page
I've noticed some responsiveness issues on the knative.dev landing page:

- The buttons lack some spacing between them, and maybe we can add some uniform padding to the main headline.
Home - Knative

- This should stack vertically instead of appearing side by side.
Home - Knative

- Alignment is inconsistent.
Home - Knative

- On smaller screens, stacking the case studies vertically could enhance readability.
Home - Knative

- The footer also requires attention.
Home - Knative

### PR DESCRIPTION
**Pull request by asr2003**
- Fixes #5876

## Proposed Changes 

**Before:**

image

image

image

image

image

**After**:

WhatsApp Image 2024-05-26 at 21 38 58_cfbe194b

WhatsApp Image 2024-05-26 at 21 39 43_fffd0ca9

WhatsApp Image 2024-05-26 at 21 40 25_a900817b

WhatsApp Image 2024-05-26 at 21 41 01_88a15fe0

WhatsApp Image 2024-05-26 at 21 41 13_2775f612

WhatsApp Image 2024-05-26 at 21 41 26_d757376a

### CODE REVIEW

**Comment by asr2003** [comment]
@Cali0707 @zainabhusain227 I am almost done with changes outlined in the issue. PTAL

**Comment by aliok** [comment]
hey @asr2003 

This issue is part of an LFX project for this summer. If you're interested in the program, please focus on your proposal, instead of working on the project.

Thanks

**Comment by varshith257** [comment]
@aliok Sorry, I didn't known this issue is part of it. I didn't seen it in upstream issue. I am searching it as part of issues that I can contribute to familiar with codebase and craft good proposal by understanding codebase.

**Comment by asr2003** [comment]
@aliok Thanks for the clarification. I had worked on it as part of contributing to the repo so that I can get familiar with the codebase and it will make to craft a good proposal. I think got misconception that this issue isn't linked in upstream issue.

**Pull request closed without merging**
