### PR TITLE
Fixed an example of imagePullSecrets

### LINKED ISSUE #4128: An example of creating secret that missing docker-registry parameter
## Expected Behavior

The Kubernetes secret resource is created successfully.

## Actual Behavior

Run commands below. This command is written in a document at https://knative.dev/docs/developer/serving/deploying-from-private-registry/#procedure

```
kubectl create secret container-registry \
  --docker-server=https://gcr.io/ \
  --docker-email=my-account-email@address.com \
  --docker-username=my-grc-username \
  --docker-password=my-gcr-password
```

```
Error: unknown flag: --docker-server
See 'kubectl create secret --help' for usage.
```

## Steps to Reproduce the Problem

1. Setup Kubernetes.
1. Setup knative
1. Run kubectl create secret command

### PR DESCRIPTION
**Pull request by reoring**
Fixes #4128 

## Proposed Changes 

- fixed a example of imagePullSecrets

### CODE REVIEW

**Review by julz — APPROVED** [review]
thanks @reoring!

/lgtm
/approve
/ok-to-test

Looks like you'll need to [submit the CLA](https://github.com/knative/docs/pull/4143#issuecomment-902494019) before we can merge this.

**Comment by reoring** [comment]
@julz Thank you for reviewing! I've singed CLA🙏

**Comment by julz** [comment]
Once you've signed it you should be able to reply here with `@googlebot I signed it!` and it should update the status.

**Comment by julz** [comment]
Oh that's funny, I think me saying that caused the bot to recheck anyway ☺️

**Comment by reoring** [comment]
hahaha. Googlebot is so smart!🤖

**Pull request merged**
