### PR TITLE
Release 1.15 blog

### PR DESCRIPTION
**Pull request by Leo6Leo**
## Proposed Changes 

- Add the release 1.15 blog

### CODE REVIEW

**Review by Cali0707 — COMMENTED** [review]
LGTM from me, thanks @Leo6Leo

**Comment by dsimansk** [comment]
/lgtm

For other reviewers.
/hold

**Comment by dsimansk** [comment]
IMO, it's fine. Given @Cali0707 has reviewed the update as well. :)

/unhold

**Pull request merged**
