### PR TITLE
 serving/samples/helloworld-kotlin: pin gradle to known working version

### PR DESCRIPTION
**Pull request by grayside**
Pin the version of gradle (to 4.10).

Note that gradle:5.2 is also available, but I've found it does not build on Cloud Build.

### CODE REVIEW

**Comment by saturnism** [comment]
consider using gradle wrapper in the future.

**Comment by grayside** [comment]
Hi @saturnism, if the gradle wrapper makes sense in a "helloworld" Dockerfile for Kotlin, it would be great to get a PR or an issue with more details on the suggestion. I am not a Kotlin developer and am just looking to stabilize this sample.

**Comment by ahmetb** [comment]
/lgtm
thanks for pinning to a MAJOR.MINOR.

**Pull request merged**
