### PR TITLE
Fix snippets link

### LINKED ISSUE #3852: Snippets (Content Reuse) link doesn't work
The link from https://dev-knative.netlify.app/development/help/contributor/ to Content Reuse is broken

### PR DESCRIPTION
**Pull request by benmoss**
Fixes #3852

### CODE REVIEW

**Comment by omerbensaadon** [comment]
Still broken in the Netlify preview

**Comment by benmoss** [comment]
Argh, snippets are excluded, and I don't want to include a link to the mkdocs branch since that'll be getting merged soon

**Pull request merged**
