### PR TITLE
Creating OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by samodell**
Fixes #(issue-number)
#655 
## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by adrcunha** [comment]
@samodell You don't need to `/retest` the go coverage job, it's not a blocker for any PR.

**Comment by samodell** [comment]
@adrcunha  Oh, good to know! Are any of the other tests non-blocking as well? I just assumed they were all blockers...

**Comment by adrcunha** [comment]
Only the go-coverage job is not a blocker, all the others are. Look for the "Required" tag in the list of checks below.

**Pull request merged**
