### PR TITLE
add blog for 2021 annual report

### PR DESCRIPTION
**Pull request by itsmurugappan**
Add blog for 2021 annual report

cc @vaikas  @pmorie

### CODE REVIEW

**Comment by vaikas** [comment]
/lgtm
/approve
/hold

Thanks!! Looks great from my pov, just adding a hold so others can take a looksie: @pmorie @lance @thisisnotapril @csantanapr 

Feel free to remove the hold if you're good with it :)

**Comment by csantanapr** [comment]
Thank so much @itsmurugappan for picking this up 🙏

**Pull request merged**
