### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wutongjie23hao**
add the generation of go.mod .

Fixes #issue-number or description of the problem the PR solves

## Proposed Changes 

-
-
-

### CODE REVIEW

**Comment by wutongjie23hao** [comment]
@googlebot I signed it!

**Comment by abrennan89** [comment]
pull-knative-docs-integration-tests seems to be failing on this @wutongjie23hao 
Please fix this issue and then this should merge automatically, since it has been approved/has lgtm.
Thanks.

**Pull request merged**
