### PR TITLE
Clarify installation steps with Docker For Mac

### PR DESCRIPTION
**Pull request by chtison**
Keep istio gateway service to `LoadBalancer` type.
Remove command replacing `LoadBalancer` by `NodePort` in knative serving yaml installation step because `grep LoadBalancer serving.yaml` returns nothing.

### CODE REVIEW

**Comment by sebgoa** [comment]
@chtison could you sign the Google CLA before we test and review this ? thank you

**Comment by chtison** [comment]
I signed it!

**Comment by sebgoa** [comment]
Could you send the PR towards master instead of the release-0.4 branch. We release 0.5.0 already and need to make sure this gets to master.

(interestingly we don't need to NodePort either in minikube since LoadBalancer will work as well).

/lgtm

/ok-to-test

**Comment by samodell** [comment]
Yep, @chtison  this PR should be made against the master branch.

**Pull request closed without merging**
