### PR TITLE
Replace links to old doc templates

### LINKED ISSUE #3949: Change references to old docs templates to the new templates
Richie's docs templates are referenced in the PR pull template and likely elsewhere also. If the new templates are merged now, reference those instead. The exception might be Richie's blog template -- assuming some people still blog.

Also, link to the new templates from the Style Guide main page.

### PR DESCRIPTION
**Pull request by RichardJJG**
Fixes #3949

### CODE REVIEW

**Comment by RichardJJG** [comment]
This also deletes some references to Hugo front matter I found in the blog template because, of course, that stuff no longer applies.

**Review by abrennan89 — APPROVED** [review]
Not sure how to check the links for these are working, so I'm trusting that you already have @RichardJJG 😄 Feel free to remove the hold if everything is working OK.

/hold
/lgtm

**Comment by RichardJJG** [comment]
> Not sure how to check the links for these are working, so I'm trusting that you already have @RichardJJG 😄 Feel free to remove the hold if everything is working OK.
> 
> /hold
> /lgtm

I also couldn't work out how to check. The prow-robot seems happy and these files are internal-facing so I think I'll just un-hold and run the risk.

**Pull request merged**
