### PR TITLE
responsive styling for case study section on Home page

### PR DESCRIPTION
**Pull request by ShravaniAK**
I have made the case study section on Home page responsive on all devices .

### CODE REVIEW

**Comment by ShravaniAK** [comment]
I have worked on the feedback that was received during the UX meet, 
1. in mobile view, made the card wider 
2. also in the mobile view aligned the text in the center

**Comment by Cali0707** [comment]
@ShravaniAK thank you for the changes, we will try and do a final review tomorrow in the UX meeting

**Comment by Leo6Leo** [comment]
The PR is approved during the UX WG meeting. But please fix the merging conflict before we proceed. Thank you for the great work @ShravaniAK

**Comment by Cali0707** [comment]
Hey @ShravaniAK can you fix the merge conflicts so that we can merge this?

**Review by Cali0707 — APPROVED** [review]
/lgtm

**Pull request merged**
