### PR TITLE
Update references to event-display image

### LINKED ISSUE #2389: Outdated references to event-display image
The `event-display` image referenced in multiple places in the docs is very much outdated and does not work with v1 CloudEvents.

The full image name is `gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display`.

I will try to figure out what the release process is for this image and send a PR to update those outdated references.

### PR DESCRIPTION
**Pull request by antoineco**
Fixes #2389

## Proposed Changes

- Update references to event-display image

### CODE REVIEW

**Comment by n3wscott** [comment]
yikes thanks!
/lgtm
/approve

**Comment by antoineco** [comment]
@matzew looks like we need one of

  - evankanderson
  - mattmoor
  - dprotaso
  - vaikas
  - rgregg
  - mchmarny
  - averikitsch

**Pull request merged**
