### PR TITLE
Blog post about TM committee dissolving

### PR DESCRIPTION
**Pull request by aliok**
- Blog post about https://github.com/knative/community/pull/1506

### CODE REVIEW

**Comment by aliok** [comment]
/hold
Depends on https://github.com/knative/community/pull/1506

**Comment by aliok** [comment]
I don't get why I don't see the new post in the navigation 😕

**Comment by krsna-m** [comment]
thanks for the blog post

**Comment by ReToCode** [comment]
The title looks a bit off to me: https://deploy-preview-5852--knative.netlify.app/blog/steering/2024-02-04-trademark-committee-dissolved/. Other than that, LGTM

**Comment by aliok** [comment]
> The title looks a bit off to me: https://deploy-preview-5852--knative.netlify.app/blog/steering/2024-02-04-trademark-committee-dissolved/. Other than that, LGTM

Oh, right.

Thanks!

https://deploy-preview-5852--knative.netlify.app/blog/steering/2024-02-14-trademark-committee-dissolved/ --> should be good now.

**Comment by aliok** [comment]
The [process change](https://github.com/knative/community/pull/1506) is complete, we should be fine to merge this without additional SC approval or something, if the content is right.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
