### PR TITLE
Revert changes to community

### PR DESCRIPTION
**Pull request by julz**
This commit reverts changes made to community which assumed it was being built by mkdocs (since it's still built with hugo) and caused formatting to break in the community tab.

/assign @omerbensaadon I did a straight `git checkout HEAD~10 community/` so please check I didn't revert something we actually wanted here, but it looks right to me

### CODE REVIEW

**Comment by omerbensaadon** [comment]
Can you do a find and replace for shell -> bash?

**Comment by julz** [comment]
> Can you do a find and replace for shell -> bash?

Do we care about applying these rules to community? Couldn't we/shouldn't we leave that folder till after GA when we fix up community to use mkdocs?

Either way, if we do want to do that again I'd suggest we re-apply it in a different PR so each PR does one thing as much as possible: having PRs making lots of unrelated changes made this a bit harder to track down via git bisect than it needed to be

**Comment by omerbensaadon** [comment]
Sorry, I wasn't clear, it was already fixed but this PR changes it back to shell, so it's a regressive change

**Comment by omerbensaadon** [comment]
@julz I will leave it up to you just in case you did understand my first message as I meant it!

**Comment by julz** [comment]
I personally think we should probably just leave community/ alone for now, but if it was intentional to fix shell->bash there as well as elsewhere I'm happy to do that conversion again in a follow-on PR once this lands. (It took longer than it should have to track this bug down, and it was harder to revert cleanly and safely, because the commit that introduced the problem made lots of changes at once, so I'd like to avoid repeating that in the fix iyswim).

/unhold

**Comment by julz** [comment]
as soon as this merges Ill do a follow-on to s/shell/bash/ in community, and we can double check that all looks right with hugo (I assume it does, but since the broader change this came in with actually broke community and we didn't realise, we should check!)

**Pull request merged**
