### PR TITLE
#789: serving/samples/helloworld-csharp: update to dotnet sdk 2.2

### LINKED ISSUE #789: helloworld-csharp broken with dotnet sdk 2.2
If I go install dotnet SDK today, I'll get 2.2.

But the dotnet SDK provided in https://github.com/knative/docs/blob/b850378d5c17e5540d7bb0387133233485c3d662/serving/samples/helloworld-csharp/Dockerfile uses 2.1

The docs also say 2.1 but not sure how realistic it is to expect people will install/have the older version.

### PR DESCRIPTION
**Pull request by grayside**
Fixes #789 

## Proposed Changes

- Update Dockerfile to use dotnet sdk 2.2
- Update code for dotnet 2.2 compatibility

## Steps Taken

1. Switch Dockerfile to extend from microsoft/dotnet:2.2-sdk

2. Update application code for dotnet 2.2:
```sh
cd serving/samples/helloworld-csharp
docker run --rm --workdir /app -v $PWD:/app/helloworld-csharp microsoft/dotnet:2.2-sdk dotnet new web --force -o helloworld-csharp
```

3. Confirm application code does not need refactor

4. Restore custom changes (e.g., listen to `$PORT` and `$TARGET`)

```sh
git checkout Startup.cs
git checkout Program.cs
```

5. Build & Test container image locally

### CODE REVIEW

**Comment by grayside** [comment]
There are two new configuration files that were generated, do those need to be added to the README?

**Comment by ahmetb** [comment]
I think we can leave them out since they weren't there.

**Comment by ahmetb** [comment]
but not super sure either.

**Comment by samodell** [comment]
Closing in favor of #883

**Pull request closed without merging**
