### PR TITLE
 inline ping-source's README.md into index.md (#2964)

### PR DESCRIPTION
**Pull request by lionelvillard**
backport https://github.com/knative/docs/pull/2964 to 0.18

### CODE REVIEW

**Comment by csantanapr** [comment]
There are two problems with the CLA bot  two authors in the commit

**Comment by abrennan89** [comment]
@lionelvillard can you try pushing this again please to fix the CLA issue?
cc @thisisnotapril

**Review by abrennan89 — APPROVED** [review]
@grantr can you please fix the CLA

**Comment by grantr** [comment]
Both authors have previously signed the CLA.

**Comment by csantanapr** [comment]
Thanks @grantr  only a Googe is able to fix this CLA issues

**Pull request merged**
