### PR TITLE
Fixed broken links in any-kubernetes-cluster related to eventing

### PR DESCRIPTION
**Pull request by mpetason**
#2949 

## Proposed Changes 

- Updated Apache Camel-K Source to knative-sandbox
- Updated Apache CouchDB Source to knative-sandbox

### CODE REVIEW

**Review by abrennan89 — APPROVED** [review]
Looks good, let's get a LGTM from someone who can confirm those are correct though

**Comment by pierDipi** [comment]
Kafka and Natss links need to be updated as well.

**Comment by abrennan89** [comment]
@pierDipi I have a PR open to fix Natss and I can add any other links that need updating to that if you want to add comments to it :slightly_smiling_face: https://github.com/knative/docs/pull/2965/files

**Pull request merged**
