### PR TITLE
Removed deprecated observability plugin

### PR DESCRIPTION
**Pull request by abrennan89**
Relates to #2904

### CODE REVIEW

**Comment by mattmoor** [comment]
Are we sure that there aren't any things referencing this?

**Comment by abrennan89** [comment]
@mattmoor the monitoring bundle has been removed now for the 0.19 release, so I think it's suitable to remove this now.
There are some other references in docs for monitoring, but we will remove them all and Stavros has opened new issues to track creating replacement docs instead of leaving the old ones in there.

**Pull request merged**
