### PR TITLE
Documenting the Trigger annotation case for the Broker creation

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes 

- With https://github.com/knative/eventing/pull/2034 we can now also create a broker, using an annotation on the Trigger. Added documentation for that
-

/assign @grac3gao

### CODE REVIEW

**Comment by matzew** [comment]
/assign @samodell  

for approval

**Comment by grantr** [comment]
/approve

But I don't think I'm actually an approver

**Comment by grantr** [comment]
typo nit: `/approve` 😁

**Pull request merged**
