### PR TITLE
Drop the `-alpine` for dotnet, it isn't multi-arch.

### PR DESCRIPTION
**Pull request by mattmoor**
This is serving from a Graviton EKS cluster built with this sample: https://helloworld-csharp.default.mink.dev

/assign @csantanapr @abrennan89

### CODE REVIEW

**Comment by csantanapr** [comment]
I think after 0.19 lands we should update the README of the samples to mention `docker buildx` they can use for building arm64

**Comment by mattmoor** [comment]
@csantanapr Good idea, want to open an issue?

**Comment by csantanapr** [comment]
Thank @mattmoor I verified on raspberry pi4 with `docker buildx`
```
curl https://helloworld-csharp.default.pi.csantanapr.com
Hello World!
```

**Pull request merged**
