### PR TITLE
Fix Istio installation for CI

### LINKED ISSUE #2891: Documentation e2e tests are broken because of an incorrect istio installation
## Expected Behavior
E2E tests to pass.

## Actual Behavior
They don't anymore because it tries to install Istio and the files it's looking for are no longer there.

As can be seen in the failing test logs here:
#2863 

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_docs/2863/pull-knative-docs-integration-tests/1313210531447836675

```
Context "gke_knative-boskos-58_us-central1_e2e-cls" modified.
- Cluster is gke_knative-boskos-58_us-central1_e2e-cls
- Docker is gcr.io/knative-boskos-58/docs-e2e-img/7916
>> Bringing up Istio
>> Running Istio CRD installer
error: unable to read URL "https://raw.githubusercontent.com/knative-sandbox/net-istio/master/third_party/istio-stable/istio-crds.yaml", server reported 404 Not Found, status code=404
```

But they were removed here:
https://github.com/knative-sandbox/net-istio/commit/6bbca066373b21689b5d90381c27920533809e82#diff-2d8f29ff21e42a47545b7012fc6d9891

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

### PR DESCRIPTION
**Pull request by nak3**
This patch fixes current CI issue - https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_docs/2860/pull-knative-docs-integration-tests/1313087628718903296

net-istio upstream changed the istio installation profile and so this doc repo also needs to be updated.

Fixes #2891

### CODE REVIEW

**Comment by nak3** [comment]
The markdown test issue is handling in https://github.com/knative/test-infra/pull/2479

/cc @tcnghia @ZhiminXiang @JRBANCEL @dprotaso @rafaeltello

**Comment by vaikas** [comment]
Fixes #2891 

Thanks! :)
/lgtm
/approve

**Comment by dprotaso** [comment]
the job should be removed: https://github.com/knative/test-infra/pull/2479

dunno how to remove the check

**Comment by nak3** [comment]
And actually `pull-knative-docs-markdown-link-check` is an optional test. It should not be necessary to pass :confused: 
Hmm... why it does not trigger to merge.

**Comment by nak3** [comment]
I tried to create a new PR for this https://github.com/knative/docs/pull/2892 but it failed `pull-knative-docs-markdown-link-check`...

**Comment by nak3** [comment]
@abrennan89 Could you please give your /lgtm and /approve label?
It seems the label did not work.

```
tide Pending — Not mergeable. Needs approved, lgtm labels.
```

**Comment by abrennan89** [comment]
/lgtm
/approve

Thank you @nak3 ! :tada:

**Pull request merged**
