### PR TITLE
Upload README.md and FIX 404 URL in Branch master

### LINKED ISSUE #3283: "View/Edit this Page" Button missing README.md
## Expected Behavior

To edit target pages

## Actual Behavior

404 Not Found

企业微信截图_20210228141157

## Steps to Reproduce the Problem

1.  separate _index.md to _index.md and README.md

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

### PR DESCRIPTION
**Pull request by Xunzhuo**
Fixes #3283

## Proposed Changes 

- Separate _index.md
- Add README.md

### CODE REVIEW

**Comment by abrennan89** [comment]
I don't understand this PR, we are actually moving away from doing this and removing the README files afaik?

**Review by pierDipi — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by abrennan89** [comment]
@RichieEscarez since we had been making an effort to move away from the READMEs, I think we need a better solution to fixing this unless we're going to move everything back to READMEs?
cc @evankanderson

**Comment by RichieEscarez** [comment]
Like I mention in Slack, the problem is outlined here: https://github.com/knative/website/issues/230

This was also discussed in the workgroup in the past here: https://docs.google.com/document/d/13-neXVH-1n1ELWgukSzySnWj-4X6UB2pGGws2z2NH3M/edit?resourcekey=0-GLlQKxB-vhyCFDbZMyPiyg#heading=h.owax4qrq4zkv

In short, we cant do it both ways. If we move away from readme.md files, the build logic needs to be changed and all readme.md files should be removed. Overall, work needs to be done one way or another. 

@abrennan89 how do you propose we proceed here? Its not clear what solution you are referring to (ie some other alternative than what was discussed previously)?

**Comment by abrennan89** [comment]
@RichieEscarez I'm not proposing anything either way, I just wanted to make sure we're not wasting our time if we keep removing the READMEs only for others to add them back in, as is being done in this PR. Someone needs to make a call and it shouldn't be me because I don't know that much about the site build logic.

Re it being discussed previously, I was physically there, but the conversation was between yourself and @evankanderson - like I said, because I don't know much about how this works. As far as I was aware, the outcome was "Slowly remove README files. Replace with _index.md files only."
I just wanted your input because this PR contradicts that.

I see there's a TODO in the WG notes:
```
TODO: Update the Knative site build to fully process the contents of _index.md files (the way it does for READMEs)
```
What's actually required to be done here? Can you and @evankanderson or someone else help to finish the work on this? It seems like it should be high priority to make sure effort isn't being wasted or duplicated either by us moving things out of READMEs or folks re-adding them after they're removed like this.

**Comment by evankanderson** [comment]
+1 to the hold, since I don't understand what's being fixed here. The original PR references 404s, but doesn't provide the pages with the broken link.

**Comment by Xunzhuo** [comment]
企业微信截图_20210304195121
企业微信截图_20210304195136

**Comment by RichieEscarez** [comment]
@abrennan89 fair enough. Since I was away when you all decided to make the shift, and more importantly, this is not priority work given my limited bandwidth, I don't think I should be assigned to these items. I definitely have already spent time helping explain the impact and outlined the work needed to help someone fix these items.

Additional time spent answering the same questions really eats into my ability to contribute elsewhere (and where I think we all agree is more needed).

Im sure you can understand the difficult balance between being responsive and helpful to requests while under time constraints.

**Comment by abrennan89** [comment]
We've decided to update the build to stop using the READMEs. It may break in some places temporarily where we have yet to remove these in favor of index, but we'll fix them as we find them. Closing this PR since we should not be re-adding the READMEs please.

**Pull request closed without merging**
