### PR TITLE
Removed references to consolidated-channel-specific secrets

### PR DESCRIPTION
**Pull request by eric-sap**
As of knative-sandbox PR 680 (https://github.com/knative-sandbox/eventing-kafka/pull/680), the consolidated channel no longer uses a distinct secret format.

## Proposed Changes

- Removed references to consolidated-channel-style secrets (ca.crt and related fields) that are now part of the config-kafka configmap (and the same as the distributed channel)

### CODE REVIEW

**Comment by eric-sap** [comment]
After all of the modifications to make the consolidated-vs-distributed authentication clear, we decided to merge the secret types anyway.  Hopefully this is just a simple removal of a section; the preview looks correct to me.

**Comment by abrennan89** [comment]
/approve

Can I get someone from @knative/eventing-reviewers to take a look and lgtm this please?

**Comment by csantanapr** [comment]
/assign @matzew 
/assign @travis-minke-sap 
Could you folks take a look when you have a chance?

**Comment by travis-minke-sap** [comment]
looks good to me - will leave for Matthias to approve/merge.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
