### PR TITLE
[release-0.18] Fix default installation without sidecar injection (#2775)

### PR DESCRIPTION
**Pull request by nak3**
This is a cherry-pick for https://github.com/knative/docs/commit/bd6307f3c3440e69a836c52effc6be9c653d991f against release-0.18 branch.

/cc @ZhiminXiang @JRBANCEL @guillaumeblaquiere

### CODE REVIEW

**Comment by nak3** [comment]
Could you please take a look? @ZhiminXiang @JRBANCEL @tcnghia

**Comment by nak3** [comment]
@mpetason @abrennan89 @tcnghia 
Could you please approve this?

**Review by tcnghia — APPROVED** [review]

**Pull request merged**
