### PR TITLE
Update community Dart sample

### PR DESCRIPTION
**Pull request by kevmoo**
## Proposed Changes

- Format server file
- Fix bug when running server without a port specified
- Update dependencies
- Small tweaks to pubspec file

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @jonasfj @mit-mit

**Comment by kevmoo** [comment]
What are our next steps here?

**Comment by kevmoo** [comment]
@sebgoa @gyliu513 @carieshmarie – help?

**Comment by sebgoa** [comment]
/assign @samodell 

This seems ready for merge

**Pull request merged**
