### PR TITLE
serving/samples/helloworld-java: update Dockerfile to respect PORT

### PR DESCRIPTION
**Pull request by averikitsch**
Respects PORT env variable by passing variable to springboot/tomcat server.

### CODE REVIEW

**Comment by averikitsch** [comment]
cc @grayside

**Comment by grayside** [comment]
The key detail being `-Dserver.port=${PORT}`? That seems reasonable to me, did you get a chance to test it locally?

It looks like you pulled in my changes from #512, should the other PR be closed?

**Comment by averikitsch** [comment]
Officially tested locally.
Incorporated your changes in order to be able to visualize it all together.

**Pull request merged**
