### PR TITLE
fix: cronjob.yaml indent two spaces

### LINKED ISSUE #3218: Sink binding(docs/eventing/sources/sinkbinding.md)
As follows `ref:` should indent two spaces
image

```yaml
apiVersion: sources.knative.dev/v1alpha1
kind: SinkBinding
metadata:
  name: bind-heartbeat
spec:
  subject:
    apiVersion: batch/v1
    kind: Job
    selector:
      matchLabels:
        app: heartbeat-cron
    sink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: event-display
```

### PR DESCRIPTION
**Pull request by yangyunfeng007**
Change-Id: Iad1e74b9e58a9a194a4e6ef71fcfbd82d9b3fb57

Fixes #3218

## Proposed Changes 

-
-
-

### CODE REVIEW

**Comment by yangyunfeng007** [comment]
@zhaojizhuang

**Review by abrennan89 — APPROVED** [review]

**Pull request merged**
