### PR TITLE
Add instructions for OpenShift

### PR DESCRIPTION
**Pull request by pmorie**
This PR adds instructions and a script for testing out Knative on OpenShift using `oc cluster up`.

Thanks to @bbrowning for a big assist with this.

### CODE REVIEW

**Comment by pmorie** [comment]
/hold

I would like to have some other folks validate these instructions before this is merged

**Comment by evankanderson** [comment]
It's worth calling out somewhere that the OpenShift instructions will only work on a Linux host, unlike many of the other instructions, which either:
1. Use an external cluster
2. Use a VM (Minikube) with availability across multiple OSen.

**Comment by evankanderson** [comment]
(Particularly vis the bash script, but also to highlight that Mac probably won't work, either.)

**Comment by sspeiche** [comment]
Validated this on my Mac, though I had a snag with getting IP access directly to the host. So I just rsh'd onto the `knative-ingressgateway` pod and then did...

```
# curl -H "Host: helloworld-go.default.example.com" http://localhost:80  
 Hello World: Go Sample v1!
```

**Comment by pmorie** [comment]
I am happy to call those things out. This is a first pass and we will be
evolving these instructions, possibly adopting minishift.

**Comment by evankanderson** [comment]
It would be nice to have the OpenShift instructions look more like the other instructions or be "OpenShift incorporates knative directly, install with OpenShift directions" (no shell script).

Still, it looks like these instructions will work for Mac and Linux, so:

/lgtm
/approve

I'll let Paul cancel the hold.

**Comment by sabre1041** [comment]
Confirmed success using the same method @sspeiche mentioned. 

However, I would recommend replacing `kubectl` command with `oc` as `kubectl` may not be available on the local machine

**Comment by pmorie** [comment]
@evankanderson I've added long-form instructions in addition to the script, PTAL

**Comment by matzew** [comment]
Hrm,

using the `knative-with-openshift.sh` script, I end with this:

```
activator-6c8667f8f7-mtn62    0/2       Init:CrashLoopBackOff   1          21s
autoscaler-76d4647c56-676c7   0/2       Init:CrashLoopBackOff   1          21s

activator-6c8667f8f7-mtn62    0/2       Init:CrashLoopBackOff   1          26s
autoscaler-76d4647c56-676c7   0/2       Init:Error              2          26s

activator-6c8667f8f7-mtn62    0/2       Init:Error              2          31s
autoscaler-76d4647c56-676c7   0/2       Init:CrashLoopBackOff   2          31s

activator-6c8667f8f7-mtn62    0/2       Init:Error              2          36s
autoscaler-76d4647c56-676c7   0/2       Init:CrashLoopBackOff   2          36s

activator-6c8667f8f7-mtn62    0/2       Init:CrashLoopBackOff   2          41s
autoscaler-76d4647c56-676c7   0/2       Init:CrashLoopBackOff   2          41s

```



here is my `oc version`:

```
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0+7fb1705-27
kubernetes v1.10.0+b81c8f8
```

**Comment by matzew** [comment]
@pmorie I am getting these `Init:CrashLoopBackOff` on my Fedora - native `oc` install

Any ideas ?

**Comment by bbrowning** [comment]
@matzew Can you gather some information from the pods as to why they're crash looping? `oc describe pod activator-6c8667f8f7-mtn62` will output status and relevant events. Also, if there's an issue that needs fixing here, it may be better to open a new issue so we can track it properly.

**Comment by matzew** [comment]
```
➜  KNative oc describe pod activator-6994fbf985-r67vc
```

Here is the output:

```
Name:           activator-6994fbf985-r67vc
Namespace:      knative-serving
Node:           localhost/192.168.178.23
Start Time:     Thu, 27 Sep 2018 10:42:58 +0200
Labels:         app=activator
                pod-template-hash=2550969541
                role=activator
Annotations:    openshift.io/scc=anyuid
                sidecar.istio.io/inject=true
                sidecar.istio.io/status={"version":"2e0c897425ef3bd2729ec5f9aead7c0566c10ab326454e8e9e2b451404aee9a5","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs...
Status:         Pending
IP:             172.17.0.26
Controlled By:  ReplicaSet/activator-6994fbf985
Init Containers:
  istio-init:
    Container ID:  docker://04515bcad698cd0338b0689708e4c66d3e4b2e176e7bae0c0f352e9e8517e669
    Image:         docker.io/istio/proxy_init:1.0.2
    Image ID:      docker-pullable://docker.io/istio/proxy_init@sha256:e16a0746f46cd45a9f63c27b9e09daff5432e33a2d80c8cc0956d7d63e2f9185
    Port:          <none>
    Host Port:     <none>
    Args:
      -p
      15001
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      8080,
      -d
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 27 Sep 2018 10:45:54 +0200
      Finished:     Thu, 27 Sep 2018 10:45:54 +0200
    Ready:          False
    Restart Count:  5
    Environment:    <none>
    Mounts:         <none>
Containers:
  activator:
    Container ID:  
    Image:         gcr.io/knative-releases/github.com/knative/serving/cmd/activator@sha256:c4edcf3f36a2cbd4af01ca659ced29994e39be322b29ce3a09bbdfeb00555f1d
    Image ID:      
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      -logtostderr=false
      -stderrthreshold=FATAL
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/config-logging from config-logging (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from controller-token-5s8xh (ro)
  istio-proxy:
    Container ID:  
    Image:         docker.io/istio/proxyv2:1.0.2
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      proxy
      sidecar
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      activator
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15007
      --discoveryRefreshDelay
      1s
      --zipkinAddress
      zipkin.istio-system:9411
      --connectTimeout
      10s
      --statsdUdpAddress
      istio-statsd-prom-bridge.istio-system:9125
      --proxyAdminPort
      15000
      --controlPlaneAuthPolicy
      NONE
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:  10m
    Environment:
      POD_NAME:                      activator-6994fbf985-r67vc (v1:metadata.name)
      POD_NAMESPACE:                 knative-serving (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      ISTIO_META_POD_NAME:           activator-6994fbf985-r67vc (v1:metadata.name)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
Conditions:
  Type           Status
  Initialized    False 
  Ready          False 
  PodScheduled   True 
Volumes:
  config-logging:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      config-logging
    Optional:  false
  controller-token-5s8xh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  controller-token-5s8xh
    Optional:    false
  istio-envoy:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  Memory
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.controller
    Optional:    true
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
Events:
  Type     Reason     Age               From                Message
  ----     ------     ----              ----                -------
  Normal   Scheduled  4m                default-scheduler   Successfully assigned activator-6994fbf985-r67vc to localhost
  Normal   Pulled     2m (x5 over 4m)   kubelet, localhost  Container image "docker.io/istio/proxy_init:1.0.2" already present on machine
  Normal   Created    2m (x5 over 4m)   kubelet, localhost  Created container
  Normal   Started    2m (x5 over 4m)   kubelet, localhost  Started container
  Warning  BackOff    2m (x10 over 3m)  kubelet, localhost  Back-off restarting failed container
```

**Comment by matzew** [comment]
and for the `autoscaler` pod:

```
Name:           autoscaler-b567f5554-2pwht
Namespace:      knative-serving
Node:           localhost/192.168.178.23
Start Time:     Thu, 27 Sep 2018 10:42:58 +0200
Labels:         app=autoscaler
                pod-template-hash=612391110
Annotations:    openshift.io/scc=anyuid
                sidecar.istio.io/inject=true
                sidecar.istio.io/status={"version":"2e0c897425ef3bd2729ec5f9aead7c0566c10ab326454e8e9e2b451404aee9a5","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs...
Status:         Pending
IP:             172.17.0.27
Controlled By:  ReplicaSet/autoscaler-b567f5554
Init Containers:
  istio-init:
    Container ID:  docker://7b17d0e20ac77d14f4f7552249c7ed21e60dadccbcf45627a55f40d15c9be51d
    Image:         docker.io/istio/proxy_init:1.0.2
    Image ID:      docker-pullable://docker.io/istio/proxy_init@sha256:e16a0746f46cd45a9f63c27b9e09daff5432e33a2d80c8cc0956d7d63e2f9185
    Port:          <none>
    Host Port:     <none>
    Args:
      -p
      15001
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      8080, 9090,
      -d
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 27 Sep 2018 10:46:06 +0200
      Finished:     Thu, 27 Sep 2018 10:46:06 +0200
    Ready:          False
    Restart Count:  5
    Environment:    <none>
    Mounts:         <none>
Containers:
  autoscaler:
    Container ID:   
    Image:          gcr.io/knative-releases/github.com/knative/serving/cmd/autoscaler@sha256:f0dbe0b6c2bc50c40e58bda00aeb8623671ddd15568e44d9cdf135e83cb5a8f8
    Image ID:       
    Ports:          8080/TCP, 9090/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/config-autoscaler from config-autoscaler (rw)
      /etc/config-logging from config-logging (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from controller-token-5s8xh (ro)
  istio-proxy:
    Container ID:  
    Image:         docker.io/istio/proxyv2:1.0.2
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      proxy
      sidecar
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      autoscaler
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15007
      --discoveryRefreshDelay
      1s
      --zipkinAddress
      zipkin.istio-system:9411
      --connectTimeout
      10s
      --statsdUdpAddress
      istio-statsd-prom-bridge.istio-system:9125
      --proxyAdminPort
      15000
      --controlPlaneAuthPolicy
      NONE
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:  10m
    Environment:
      POD_NAME:                      autoscaler-b567f5554-2pwht (v1:metadata.name)
      POD_NAMESPACE:                 knative-serving (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      ISTIO_META_POD_NAME:           autoscaler-b567f5554-2pwht (v1:metadata.name)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
Conditions:
  Type           Status
  Initialized    False 
  Ready          False 
  PodScheduled   True 
Volumes:
  config-autoscaler:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      config-autoscaler
    Optional:  false
  config-logging:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      config-logging
    Optional:  false
  controller-token-5s8xh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  controller-token-5s8xh
    Optional:    false
  istio-envoy:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  Memory
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.controller
    Optional:    true
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
Events:
  Type     Reason     Age               From                Message
  ----     ------     ----              ----                -------
  Normal   Scheduled  5m                default-scheduler   Successfully assigned autoscaler-b567f5554-2pwht to localhost
  Normal   Pulled     3m (x5 over 5m)   kubelet, localhost  Container image "docker.io/istio/proxy_init:1.0.2" already present on machine
  Normal   Created    3m (x5 over 5m)   kubelet, localhost  Created container
  Normal   Started    3m (x5 over 5m)   kubelet, localhost  Started container
  Warning  BackOff    5s (x24 over 5m)  kubelet, localhost  Back-off restarting failed container
```

**Comment by matzew** [comment]
@bbrowning Hey, Ben,

I did follow your advice, and did create a new issue:

https://github.com/knative/docs/issues/417

**Pull request merged**
