### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by pugang1985**
Fixed typo

### CODE REVIEW

**Comment by samodell** [comment]
hey @pugang1985 ! Thanks for your PR. If you sign your CLA, we'll be able to merge this in. See the bot's comment above for more info.

**Comment by pugang1985** [comment]
@googlebot I signed it!

**Comment by pugang1985** [comment]
@samodell OK, I have done that now. Would you please help check whether it's OK now?

**Comment by samodell** [comment]
Hmm @pugang1985 , since the bot hasn't run again, there might be a mismatch between the email used to sign your git commits and the email you used to sign the CLA. Can you confirm that you've used the same email for both?

If you have, it might be a failure in the bot.

**Comment by pugang1985** [comment]
Sorry for that, now I tried again and used the exact email as my google account to sign it. Should be ok, can you help check again?

**Comment by samodell** [comment]
No worries; it's good to go now!

/lgtm
/approve
/ok-to-test

**Pull request merged**
