### PR TITLE
Mkdocs styles and home refactor + navigation menu nav items fixes 

### LINKED ISSUE #3561: Fixed navigation menu nav links color
## Expected Behavior
- Navigation nav links should be visible to the user

## Actual Behavior
- Nav links are invisible except for the active one

## Steps to Reproduce the Problem

1. Go to a mobile resolution
2. Open the top nav menu

### PR DESCRIPTION
**Pull request by gabo1208**
Fixes #3561, #3548

## Proposed Changes

- Better organization of the css (take them out of the templates html
- Removed all home content from the navs section to the content section
this re-enables some theme features like the back to top button, fixed header (with shadow)
and scrolling events detection on the landing (home) page

You can view the results of this PR [here](https://gabo1208.github.io/docs-1/)

### CODE REVIEW

**Comment by julz** [comment]
looks awesome - thanks! Think you'll need to rebase on #3558 though to pick up the [little extra css there ](https://github.com/knative/docs/pull/3558/files#diff-e367d91bc273f41e7df5de1babaed6b2878046bdd06fbc4a385674f695bb7a25R15-R22 )for the blog and community links.

(btw having stuff under the header instead of content was actually intentional to try to make the header feel like one larger continuous block on the homepage, but with the new animated gradient we already moved away from that anyway so this seems reasonable to me; either way the reorg of the css is nice)

**Comment by julz** [comment]
.. hah, I just realised #3558 didnt actually merge yet, so I guess whichever lands last will have to rebase! :D

**Comment by gabo1208** [comment]
Yeeeh XD was waiting for the merge @julz but feel free to merge this firs :p

**Comment by julz** [comment]
was it this PR that made the top block bigger or was it the gradient PR? Im not sure I personally like the header being _quite_ this big (Im not a designer, tho!):

image

**Comment by julz** [comment]
.. looks like it was gradient that changed that 🤷  anyway no big deal

I think let's hold off on this until #3558 lands if only so you can fix up my crappy css to be in the right place etc, if that's ok? :D

**Comment by gabo1208** [comment]
Was the gradient PR, i just reorganized those styles to the separated files and integrated them with the new home html layout

**Comment by julz** [comment]
(yeah the gradient is _sick_!)

**Comment by gabo1208** [comment]
Sure! Lets wait for #3558 then 👍🏼

**Comment by gabo1208** [comment]
@googlebot I consent.

**Comment by julz** [comment]
@googlebot I consent

**Comment by shinigambit** [comment]
@googlebot  I consent

**Comment by gabo1208** [comment]
@googlebot I consent

**Comment by gabo1208** [comment]
Too much troubles with the rebase

**Pull request closed without merging**
