### PR TITLE
Fix the broken links for serving and eventing configuration by configmap

### PR DESCRIPTION
**Pull request by houshengbo**
## Proposed Changes 

- Anchor links expect lowercase letters only. This PR converts the uppercase letters into lowercase letters.

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/assign @abrennan89

**Comment by abrennan89** [comment]
/approve
Thanks @houshengbo !

**Comment by abrennan89** [comment]
@houshengbo does this need to be picked back into older branches and if so can you please raise PRs for that?

**Pull request merged**
