### PR TITLE
Adding redirect guidance, redirect for community

### LINKED ISSUE #3999: Document how to add a re-direct
**Describe the change you'd like to see**
See above 

**Additional context**

### LINKED ISSUE #4000: Broken community link
It seems almost all repo needs to update the link https://knative.dev/contributing/ to https://knative.dev/community/contributing/

### PR DESCRIPTION
**Pull request by omerbensaadon**
Fixes #3999 
Fixed #4000

### CODE REVIEW

**Comment by nak3** [comment]
LGTM but it seems github action produces an error.

**Comment by benmoss** [comment]
I don't think this works, I see this in my logs:

```
WARNING  -  redirects plugin: 'contributing' is not a valid markdown file!
WARNING  -  Redirect target 'community/contributing/README.md' does not exist!
```

**Comment by benmoss** [comment]
Still seeing this:

```
WARNING  -  Redirect target '/community/contributing/README.md' does not exist!
```

https://app.netlify.com/sites/knative/deploys/60edac2004ad3b0007eda2b9?utm_source=github&utm_campaign=bot_dl#L156

**Comment by omerbensaadon** [comment]
@nak3 @benmoss

**Comment by julz** [comment]
unfortunately I don't think `/retest` will work to retrigger netlify previews since they're not triggered by prow. Maybe try closing and reopening the PR?

**Comment by omerbensaadon** [comment]
This is weird...

**Comment by omerbensaadon** [comment]
wow ok that did it. 

A slight weirdness of hugo is that you have to have an _index.md file, it does not accept READMEs.

**Pull request merged**
