### PR TITLE
types for channel/subscription have been moved to beta1

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

- pointing to recent beta1 changes for the types of channel/subscription
-
-

### CODE REVIEW

**Comment by n3wscott** [comment]
We do not have the reconcilers or the CRDs for v1beta1 yet but the plan is targeting v0.13 release

**Comment by samodell** [comment]
@matzew  re: Scott's comment above, are there any changes we need to make to this PR before it goes in?

**Comment by evankanderson** [comment]
I rewrote parts of the eventing README, so you may need to merge.

**Comment by abrennan89** [comment]
@matzew this needs a rebase I think, then we can go ahead and merge it?

**Comment by matzew** [comment]
/close

we are on v1 works already

**Pull request closed without merging**
