### PR TITLE
Update contour docs and two additional link typos

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

Fixes the contour installation guide to be consistent with recent changes: https://github.com/knative/net-contour/commit/66f1ac98bd338cff6b92bccdf1b3b79c27078824

This also removes some extraneous `v`s from two version links

### CODE REVIEW

**Comment by chuckha** [comment]
@googlebot I signed it!

**Comment by sebgoa** [comment]
this seems to be correct with the new docs

/ok-to-test

**Comment by chuckha** [comment]
/test pull-knative-docs-markdown-link-check

just curious if this could possibly flake or if i'm doing something incorrect

**Comment by chuckha** [comment]
@sebgoa After looking through all the GitHub links the failing `natss` one appears somewhat unusual. Most other GitHub links are for hard-coded versions or branches. The other version links that I found had a typo in them so I fixed that while I was there, please see the attached screenshot.

If you had advice on how to proceed that would be great. I can also dig more into this later today, but right now the thing populating the template variables is not directly obvious to me.

Screen Shot 2020-02-24 at 10 04 09 AM

**Comment by abrennan89** [comment]
Hey @chuckha :slightly_smiling_face: it looks like this PR might need to be rebased since it has conflicts. I believe that these markdown test failures happen often and don't actually affect our ability to merge or anything (I remember asking this same question a long time ago, but the version of Slack we have doesn't allow us to access old msgs or I'd point you to it :disappointed: )

Richie or Sam would know more, but both of them are either working on other projects or on long term leave atm. @mattmoor @carieshmarie any ideas who would be the expert of these failures in Richie/Sam's absence? Thanks.

**Comment by chuckha** [comment]
@abrennan89 thank you for the feedback! PR rebased!

**Comment by abrennan89** [comment]
Ah, I took another look at this and I think I might see what the problem is.

docs/serving/using-auto-tls.md
ERROR../install/Knative-with-Contour.md Stat docs/install/Knative-with-Contour.md: no such file or directory
ERROR ../install/Knative-with-Gloo.md Stat docs/install/Knative-with-Gloo.md: no such file or directory
ERROR https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme.html#creating-a-basic-acme-issuer Bad Request (HTTP error 400)

In the older versions of https://knative.dev/docs/install/ those files that we link to existed, but in the latest pre-release version for 0.13, all of the vendor specific install docs have been removed: https://knative.dev/development/install/

I think the fix would be to remove or update the links in `docs/serving/using-auto-tls.md` to "Before you begin" section (https://knative.dev/docs/serving/using-auto-tls/ shows this) that point to Gloo and Contour.
On top of this, the link pointing to https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme.html#creating-a-basic-acme-issuer now redirects to https://cert-manager.io/docs/configuration/acme/ in the browser, so this should be updated.

Maybe try this and see if it fixes the issue, although I've just realised that since this PR is an update to Contour docs and afaik this isn't included in knative.dev anymore, there might be a bigger question here about whether we should be adding this PR at all?
@mattmoor can you provide any input on this? Thanks.

**Comment by chuckha** [comment]
/close

everything in this PR was fixed in a different PR

**Pull request closed without merging**
