### PR TITLE
Fixes a typo in docs

### PR DESCRIPTION
**Pull request by MichalPitr**
This PR fixes a simple typo.

### CODE REVIEW

**Comment by psschwei** [comment]
Thanks for the PR @MichalPitr ! Once you sign the EasyCLA, we can merge this.

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
Added `hold` so that 5393 could be merged. Please unhold when CLA issue is fixed.

**Comment by MichalPitr** [comment]
@psschwei when I click on the "authorize" link, I get the following error message:{"errors": `{"Invalid OAuth2 state": "NnjotKHWVbngrv5PQft3gCALx65RfE"}}`

Am I missing some steps?

**Comment by psschwei** [comment]
Have you authorized the Linux Foundation: EasyCLA oauth app? I'm pretty sure that's what's handling the oauth (but will tag @kvmware @upodroid to confirm)

**Comment by MichalPitr** [comment]
@psschwei  Should be good now! I was trying to sign it from a mobile device and it seemingly doesn't work there. Works fine on a desktop.

**Comment by psschwei** [comment]
Awesome! Thanks for the PR (and for working through the CLA issues :smile: ) !

/hold cancel

**Pull request merged**
