### PR TITLE
Suggestions for getting started

### PR DESCRIPTION
**Pull request by abrennan89**
## Proposed Changes

- make Before you begin the README/landing page, includes pre-Knative steps
- Added install page for `konk` and `kn` to live in

### CODE REVIEW

**Comment by omerbensaadon** [comment]
This is exactly the sort of tech-writer's touch I needed, thank you @abrennan89 :)

**Review by omerbensaadon — APPROVED** [review]

**Comment by abrennan89** [comment]
/approve
@omerbensaadon can you re-lgtm please

**Pull request merged**
