### PR TITLE
Installation for eventing not release.

### PR DESCRIPTION
**Pull request by JensonCraft**
Fixes #issue-number

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by JensonCraft** [comment]
@googlebot I signed it!

**Comment by RichieEscarez** [comment]
@vaikas can you please verify this change? I believe at some point in the past this was reverted from eventing.yaml back to release.yaml so I want to make sure this is correct.

**Comment by samodell** [comment]
Hey @JensonCraft  

release.yaml installs eventing + the in-memory ClusterChannelProvisioner, while eventing.yaml installs eventing without the ClusterChannelProvisioner -- that has been true for the past few releases; see the Eventing releases page: https://github.com/knative/eventing/releases

Can you explain your reasoning behind making this change for the minikube install?

**Comment by samodell** [comment]
@JensonCraft I'm closing this out, but feel free to re-open with an explanation of the changes if you still feel this needs to be applied. Thanks!

**Pull request closed without merging**
