### PR TITLE
Update ContainerSource docs and examples to use v1

### PR DESCRIPTION
**Pull request by eclipselu**
Part of https://github.com/knative/eventing/issues/4175 , follow-up of https://github.com/knative/eventing/pull/4270 and https://github.com/knative/eventing/pull/4319

## Proposed Changes 

- Updated ContainerSource docs and example
- Fixed Reference Documentation links for APIServiceSource, ContainerSource, PingSource and SinkBinding

### CODE REVIEW

**Comment by eclipselu** [comment]
cc @capri-xiyue

**Comment by capri-xiyue** [comment]
assign @lionelvillard

**Comment by eclipselu** [comment]
ping @lionelvillard 
can you take a look? Thanks a lot.

**Comment by eclipselu** [comment]
/assign @evankanderson 
Can you take a look? Thanks!

**Pull request merged**
