### PR TITLE
Fix the documentation URL for the language pack

### PR DESCRIPTION
**Pull request by dorbae**
Fix the documentation URL for the language pack

"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

- Fix 404 Not found exception by altering the URL which has been changed

### CODE REVIEW

**Comment by psschwei** [comment]
Thanks for the PR @dorbae !

You'll need to [sign the CLA](https://github.com/knative/docs/pull/5344#issuecomment-1333428424) in order for this to merge.

**Review by lance — COMMENTED** [review]
/lgtm
/approve

**Comment by dorbae** [comment]
> sign the CLA

Hi, @psschwei. I signed it. Thank you for helping!

**Pull request merged**
