### PR TITLE
Updated landing page

### LINKED ISSUE #1881: Update: Knative overview
Update the Knative overview @ https://knative.dev/docs/:

- Cover Knative at a high level only. 
- Should explain what "Knative" means (Serving and Eventing components)
- And then explain what each component is/provides (high level picture)
- Use something visual (matrix or diagram) to show how each component can be used (together/standalone)
- Introduce "Why" to use each component, then link to the new "Uses cases" topic for details (Learn more...)

### PR DESCRIPTION
**Pull request by abrennan89**
Fixes #1881 

## Proposed Changes 

- move Audience information to contributor docs
- Updated introduction / overview to remove fluff, additional words that don't add value or would be difficult for users to understand

### CODE REVIEW

**Review by evankanderson — COMMENTED** [review]
/lgtm

**Comment by vaikas** [comment]
It's complaining about newlines in pdf files...
```
  reviewdog: Reporting results for "EOF Newline"
  Error: [EOF Newline] reported by reviewdog 🐶
  Missing newline
  
  Raw Output:
  ./community/contributing/images/logo/rgb/knative-logo-rgb.ai:2518: Missing newline
  Error: [EOF Newline] reported by reviewdog 🐶
  Missing newline
  
  Raw Output:
  ./community/contributing/images/logo/cmyk/knative-logo-cmyk.ai:5594: Missing newline
  Error: Process completed with exit code 1.
```

vaikas-a01:eventing vaikas$ file !$
file ~/Downloads/knative-logo-rgb.ai
/Users/vaikas/Downloads/knative-logo-rgb.ai: PDF document, version 1.5

**Comment by vaikas** [comment]
Aaand, the istio-crds are nowhere to be found, so there's that which is nice...

```
Context "gke_knative-boskos-58_us-central1_e2e-cls" modified.
- Cluster is gke_knative-boskos-58_us-central1_e2e-cls
- Docker is gcr.io/knative-boskos-58/docs-e2e-img/7916
>> Bringing up Istio
>> Running Istio CRD installer
error: unable to read URL "https://raw.githubusercontent.com/knative-sandbox/net-istio/master/third_party/istio-stable/istio-crds.yaml", server reported 404 Not Found, status code=404
```

And indeed, they are not there (so not just a transient issue)
vaikas-a01:eventing vaikas$ curl -L 'https://raw.githubusercontent.com/knative-sandbox/net-istio/master/third_party/istio-stable/istio-crds.yaml' > /tmp/istio-crds.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0      8      0  0:00:01  0:00:01 --:--:--     8
vaikas-a01:eventing vaikas$ cat /tmp/istio-crds.yaml
404: Not Foundvaikas-a01:eventing vaikas$

**Pull request merged**
