### PR TITLE
Fix rocket image on small screens

### PR DESCRIPTION
**Pull request by markusthoemmes**
Sadly, I broke this, so here I am fixing it. Also slightly adjusting the positioning on small screens so it doesn't hug the screen corner as much.

### CODE REVIEW

**Comment by omerbensaadon** [comment]
I really want this rocket to be on the left side of the text... :D

**Comment by omerbensaadon** [comment]
Relevant to #3640

**Comment by shinigambit** [comment]
For me the text seems like the bigger issue, I would expect the rocket to become part of the text's background and the text to occupy the whole width or maybe even show at the top of the text instead.

I was thinking something like this but centering the rocket idk:
Screen Shot 2021-05-22 at 12 08 10
Sorry the image looks so huge

**Comment by markusthoemmes** [comment]
IMO, the rocket shouldn't be on the left side as a default as it breaks the left eye-line, where all text uniformly starts there. That'd look weird I think.

**Comment by shinigambit** [comment]
@markusthoemmes yeah, my default responsive view was Galaxy S9 and the text looks stretched I can see how it looks better in most devices.

For reference this is how it looks in a Galaxy S9 / Galaxy S5:

**Pull request closed without merging**
