### PR TITLE
Removed errant ./ instances

### LINKED ISSUE #4043: Fix all instances of ./ in relative links
Fix all instances of ./

Detail: `[<some-page>](./<some-folder>/<some-page>)` is not valid (and the link checker doesn't like it -- it causes 404 errors in staging). The link must be one of the following:

`[<some-page>](../<some-folder>/<some-page>)`
`[<some-page>](<some-folder>/<some-page>)`

### PR DESCRIPTION
**Pull request by RichardJJG**
Fixes #4043

### CODE REVIEW

**Comment by RichardJJG** [comment]
@abrennan89, could you approve, please? (Samia can't do so yet, but fingers crossed will have that power soon)

**Comment by abrennan89** [comment]
@RichardJJG does this need to be cherrypicked into 0.24?

**Pull request merged**
