### PR TITLE
Sample App: Fix the content in the bad word filter knative function code

### PR DESCRIPTION
**Pull request by Leo6Leo**
## Proposed Changes 

- Fixed the input and output cloudevent format

### CODE REVIEW

**Comment by Cali0707** [comment]
Hey @Leo6Leo what's the context on this change?

**Comment by Leo6Leo** [comment]
@Cali0707  As some of the schema is changed from the time when the original PR get merged, thus making this PR to reflect the new schema change.

**Comment by Leo6Leo** [comment]
/cc @pierDipi @Cali0707 

This PR should be good to be merged. Further changes will be performed in https://github.com/knative/docs/pull/5948

**Review by Cali0707 — APPROVED** [review]
/lgtm

**Pull request merged**
