### PR TITLE
Updates links in `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by JeffNeff**
Fixes an issue mentioned in: https://github.com/knative/docs/issues/4197

## Proposed Changes 

- Updates some broken links. Please note, I could not find the appropriate links for `website help` and `maintainer help` I removed them... if these pages do exist somewhere else I would prefer to re-link them

### CODE REVIEW

**Comment by JeffNeff** [comment]
@snneji  would you mind looking over this and see if it was proper to remove the two referenced links? I feel uneasy about it, but also could not locate the referenced documents.

**Comment by snneji** [comment]
Thanks for fixing the broken links! :) 

I think it's fine to delete those links, we no longer use those pages.

**Pull request merged**
