### PR TITLE
[Automated] Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc abrennan89 dprotaso vaikas
/assign abrennan89 dprotaso vaikas

### CODE REVIEW

**Comment by abrennan89** [comment]
/retest
@mattmoor FYI this one is failing

**Comment by dprotaso** [comment]
Started a slack thread - https://knative.slack.com/archives/C012AK2FPK7/p1601910100019600

`net-istio` repro changed which broke the docs installation

**Comment by dprotaso** [comment]
blocked on: https://github.com/knative/docs/pull/2889

**Pull request closed without merging**
