### PR TITLE
Cherry-Pick 0.16 - Updated links for broker and trigger. Broke up the single link into t…

### PR DESCRIPTION
**Pull request by mpetason**
…wo links so that trigger takes you to the correct location. (#2962)

#2943 

## Proposed Changes 

- cherry-pick to release-0.16

### CODE REVIEW

**Comment by evankanderson** [comment]
This link doesn't seem to work:

https://knative.dev/v0.16-docs/eventing/triggers/

But this one does:

https://knative.dev/v0.16-docs/eventing/broker/


/close

**Comment by mpetason** [comment]
@evankanderson thanks for catching this. I need to test cherry pick links next time. (was first time doing a cherry pick so I got a bit excited and didn't think to double check links)

**Comment by evankanderson** [comment]
No problem, that's what code review helps with. 😁

**Pull request closed without merging**
