### PR TITLE
[WIP] Eventing Trigger Filtering docs

### LINKED ISSUE #1271: Document advanced trigger filter for eventing
## What is changing? 

[Advanced trigger filter proposal](https://github.com/knative/eventing/pull/1047)

## In what release will this take happen (to the best of your knowledge)?
0.6

From https://github.com/knative/eventing/issues/930:
Problem
We need more advanced filtering mechanisms than just exact match on Cloud Event types and sources.

Persona:
Event Consumer

Exit Criteria
Being able to configure advanced filters on triggers, either with CEL or some other language.

## Suggestions for where to add this content

- Update/add/delete necessary info in https://github.com/knative/docs/tree/release-0.5/docs/eventing/README.md
   - And link to new topic (details below)
- Create new Event Trigger topic 
   - add new file (filtering.md): https://github.com/knative/docs/tree/release-0.5/docs/eventing/ **filtering.md**
   - Title, maybe: "**Event Triggers**"
- Key focal points to address in the document:
  - Try to create sections as follows:
     1. overview/conceptual content
        - Address "why user should use a filter" (ie. Use a filter in your event trigger to reduce and filter out only the attributes of an event that you want sent to the event subscribers.)
     2. requirements/prerequisites (create a "Before you begin" section)
        - list all requirements and link to relevant content
        - Link to [CEL](https://github.com/google/cel-spec) -> explain (ie. Trigger filters support expressions written in CEL.)
     3. "how to" info (the "task-oriented" step by step details for creating an event filter in a trigger) -> use a gerund in title (for example *Filtering event attributes*)
     4. Example(s) (show them how and where they would/can create a filter in their trigger) i see lots in the proposal and it would be most consumable if we could organize these to some degree
     5. Link to what the next logical step would be (and include links to related info) to keep the user moving forward

### PR DESCRIPTION
**Pull request by grantr**
Fixes #1271.

## Proposed Changes

-  Document Trigger Filtering, a feature scheduled to be added in v0.6.0. Proposal at https://github.com/knative/eventing/pull/1047.

/cc @RichieEscarez

### CODE REVIEW

**Comment by grantr** [comment]
Advanced Trigger Filtering was delayed to 0.7

**Comment by samodell** [comment]
@grantr  Did trigger filtering go into the 0.7 release?

**Comment by grantr** [comment]
It did not. Indefinitely delayed.

**Comment by samodell** [comment]
Got it, thanks!

**Comment by rgregg** [comment]
Closing this indefinitely delayed PR. Please open again when we're ready to commit.

**Pull request closed without merging**
