### PR TITLE
Added autoscaling docs and scale-to-zero details

### LINKED ISSUE #1362: Create documentation for autoscaling
## What is changing? (Please include as many details as possible.)

Adding autoscaler and scale-to-zero documentation.

## In what release will this take happen (to the best of your knowledge)?
v0.5-v0.6

## Context
Link to associated PRs or issues from other repos here.

1. #1332

### PR DESCRIPTION
**Pull request by abrennan89**
Fixes #1362 

## Proposed Changes

- added autoscaling.md
- updated links

### CODE REVIEW

**Comment by abrennan89** [comment]
Thanks @samodell :) the changes should be ready now

**Comment by samodell** [comment]
/lgtm
/approve

Thanks for adding this, Ashleigh!

**Pull request merged**
