### PR TITLE
updating sidecar injector ConfigMap and restarting pod

### LINKED ISSUE #417: Openshift 3.10 (oc cluster up) does not get knative serving running
## Expected Behavior

Running version of knative-service

## Actual Behavior

* `Init:CrashLoopBackOff`
* `Init:Error`

of `activator` and `autoscaler` pods:

```
activator-6994fbf985-r67vc   0/2       Init:CrashLoopBackOff   7          12m
autoscaler-b567f5554-2pwht   0/2       Init:CrashLoopBackOff   7          12m
```

## Steps to Reproduce the Problem

1. usage of latest `oc` binary 
2. execute the `knative-with-openshift.sh` 
3. watch the errors on the `knative-serving` part

## Additional Info

My `oc version`:

```
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0+fd501dd-48
kubernetes v1.10.0+b81c8f8
```

I am also getting warnings in my Fedora 28 -> **New SELinux security alert**

### PR DESCRIPTION
**Pull request by matzew**
Fixes #417

Openshift needs sidecar-injector pod CM change, and pod restart

## Proposed Changes

* updating the `ConfigMap` 
* restarting the `sidecar-injector` pod

### CODE REVIEW

**Comment by bbrowning** [comment]
The test infrastructure was having some issues earlier that I believe are now resolved.

/retest

**Comment by matzew** [comment]
@bbrowning I added a check for `SELinux`, it disabled or not

**Comment by matzew** [comment]
was tested on Mac by @hhiden and @sjwoodman 

I did the `Linux` test ;-)

**Comment by bbrowning** [comment]
Putting on hold while we work out the best OpenShift developer experience for Knative.

/hold

**Pull request closed without merging**
