### PR TITLE
fix live preview

### PR DESCRIPTION
**Pull request by shivamgupta2020**
This PR resolve **live preview** that is currently not working properly.

### CODE REVIEW

**Comment by Cali0707** [comment]
/cc @Leo6Leo 
Can you TAL when you have a chance?

**Comment by Leo6Leo** [comment]
@shivamgupta2020 @Cali0707  Can you provide me with more context about this PR? Is it trying to solve these failures of github actions?

image


Without the changes in this PR, the compilation works fine on my [sample app PR](https://github.com/knative/docs/pull/6007) and locally. Not sure what is the issue with live preview. If clarification can be provided, that would be really appretiated.

**Comment by Leo6Leo** [comment]
image

Weird when I visit /blog locally. Any ideas on what could the cause?

**Comment by shivamgupta2020** [comment]
@Leo6Leo , currently the website doesn't reload when changes are made. We have to run `./hack/docker/run.sh` or `mkdocs serve` each time to view changes. This PR fixes live preview reloading, so the website automatically reloads when changes are made.

**Review by Leo6Leo — CHANGES_REQUESTED** [review]
Please see the comment. Nice catch! @shivamgupta2020

**Pull request closed without merging**
