### PR TITLE
Cleaning up home design

### PR DESCRIPTION
**Pull request by gabo1208**
- Added new svgs
- Fixed blog button colors
- Removed unused images

### CODE REVIEW

**Comment by csantanapr** [comment]
LOL
reviewdog is giving linting error on an a picture file
image

**Comment by csantanapr** [comment]
We need to find out how to configure review dog to ignore .svg

**Comment by gabo1208** [comment]
Hahaha I found that hilarious too xD I'm on it

**Comment by csantanapr** [comment]
@gabo1208 I opened a PR here https://github.com/knative-sandbox/.github/pull/177

**Pull request merged**
