### PR TITLE
Drop documentation for custom-metrics API

### PR DESCRIPTION
**Pull request by markusthoemmes**
We no longer support this since ages. So let's drop it.

### CODE REVIEW

**Review by julz — APPROVED** [review]

**Comment by abrennan89** [comment]
@markusthoemmes thanks for updating this - are there any other places in the docs that link to this or anything that need to be updated?
Otherwise lgtm, feel free to remove the hold if not

/hold
/lgtm

**Comment by markusthoemmes** [comment]
I did search for `custom.*metric` and nothing relevant popped up.

/unhold

**Comment by markusthoemmes** [comment]
I guess this lacks an approval :(

**Comment by abrennan89** [comment]
Oof, thought Julz approving was enough, sorry!

/approve

**Review by abrennan89 — APPROVED** [review]

**Pull request merged**
