### PR TITLE
Update Knative cosign verify docs

### PR DESCRIPTION
**Pull request by BobyMCbobs**
Fixes: #5567, #5494

## Proposed Changes

- update snippet for `cosign verify` with images
- update snippet for `cosign verify` with blobs

### CODE REVIEW

**Comment by dprotaso** [comment]
I believe this fixes - https://github.com/knative/serving/issues/13970

**Review by upodroid — APPROVED** [review]
LGTM

Thanks

**Comment by BobyMCbobs** [comment]
Woohoo!

Thank you @dprotaso, @upodroid!

**Pull request merged**
