### PR TITLE
Format markdown

### PR DESCRIPTION
**Pull request by mattmoor-sockpuppet**
Produced via: `prettier --write --proseWrap=always $(find -name '*.md' | grep -v vendor)`

### CODE REVIEW

**Comment by evankanderson** [comment]
I typo'ed the flag, it is `--prose-wrap=always`. I don't know if the text output of the command could be included somewhere in the commit message (but not the PR comment)?

@mattmoor

**Comment by mattmoor** [comment]
@evankanderson weird, that's why I ran it, to see failures. 😨

**Pull request merged**
