### PR TITLE
We do not have an activator in Eventing

### LINKED ISSUE #5277: There is no Eventing activator
The `KnativeEventing` operator installation talks about `activator`, which is a component from serving, not eventing.:

https://knative.dev/docs/install/operator/configuring-eventing-cr/#override-the-affinity

IMO we should use a different workload to describe the override of the `affinity`

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #5277

## Proposed Changes 

- describing `affinity` on a different deployment, since there is no activator in Eventing

NOTE: this just fixing the problem w/ the `ACTIVATOR`, not trying to address https://github.com/knative/docs/issues/5276  (which is a separate issue)

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Review by psschwei — COMMENTED** [review]
/approve

**Pull request merged**
