### PR TITLE
Move scale bounds settings to annotation field

### PR DESCRIPTION
**Pull request by nak3**
## Proposed Changes
- This patch moves `autoscaling.knative.dev/{minScale,maxScale}` to `spec.template.metadata.annotations`, where is correct settings.

You can refer to https://github.com/knative/serving/blob/master/docs/scaling/README.md as well.

### CODE REVIEW

**Comment by RichieEscarez** [comment]
If this change also applies to the 0.9 release, you can open another PR or add the `cherrypick-0.9` label to this PR (in which case the cherrypick will happen at a later time depending on backlog)

**Comment by nak3** [comment]
/cherrypick-0.9

**Comment by nak3** [comment]
/label cherrypick-0.9

Thank you @RichieEscarez

**Comment by mattmoor** [comment]
If you want this cherry picked to 0.9, create a PR against `release-0.9` and put `[RELEASE 0.9]` in the title, please.

**Pull request merged**
