### PR TITLE
Fixed Broken Image Links

### PR DESCRIPTION
**Pull request by hpandeycodeit**
Fixes: 

The website has a couple of  broken image links on this page: 
https://www.knative.dev/docs/install/knative-with-gardener/

Under the following sections: 

1. Access Gardener [Download Kubeconfig for Gardner](https://www.knative.dev/docs/install/knative-with-gardener/images/gardener_service_account.png)
2. Creating a Kubernetes cluster [shoot creation](https://www.knative.dev/docs/install/knative-with-gardener/images/gardener_shoot_creation.png)

## Proposed Changes

- Fixed the dead links on this page.

### CODE REVIEW

**Comment by samodell** [comment]
Hi @hpandeycodeit , thanks for your PR! The Knative website is right now pulling from the documentation in the release-0.3 branch, so we wouldn't want to merge these changes into master.

We also have a known issue where we're having trouble getting links to resolve from both the website and within GitHub, because of the way the static site generator is handling relative links, so this might be a symptom of that. @RichieEscarez  is working on a fix for that issue, and if that resolves this error, we will close out this PR. Hold for now.

/hold

**Comment by samodell** [comment]
@hpandeycodeit  Can you instead make this PR against the release-0.3 branch? We've confirmed that this isn't related to the issue mentioned above.

**Comment by hpandeycodeit** [comment]
@samodell thanks for the clarification! I just created a PR against release-0.3 branch.Thanks!

**Comment by samodell** [comment]
Thanks, @hpandeycodeit ! I'll take a look.

**Pull request closed without merging**
