### PR TITLE
Move all serving stuff to v1beta1 apiVersion

### PR DESCRIPTION
**Pull request by mattmoor**
/hold

### CODE REVIEW

**Comment by samodell** [comment]
@mattmoor  Is the timeline for this v1.0 or 0.7/0.8?

**Comment by dgerd** [comment]
The v1beta1 endpoint will be available starting at Serving 0.7. While the v1alpha1 endpoint will still be available there is little disadvantage to pointing our samples and new users towards the newer API endpoint.

**Comment by mattmoor** [comment]
This is for 0.7

**Comment by mattmoor** [comment]
@samodell LMK if there is anything else?

**Comment by samodell** [comment]
Looks good! Since this is for 0.7, we can take off the hold and merge it in when you're ready, @mattmoor 

/lgtm
/approval

**Pull request merged**
