### PR TITLE
Add correct URL to fluent-bit-collector.yaml

### LINKED ISSUE #4315: YAML referenced in Logging Documentation goes to 404
## Expected Behavior
The referenced YAML for deployment is successful

## Actual Behavior
The referenced YAML goes to 404

## Steps to Reproduce the Problem

In [Logging](https://knative.dev/docs/admin/collecting-logs/) documentation, the referenced YAML in Step 1 points to `https://github.com/knative/docs/raw/main/docs/admin/install/collecting-logs/fluent-bit-collector.yaml` but this gives 404. Looking at the repo, it looks like it should have been `https://raw.githubusercontent.com/knative/docs/main/docs/admin/collecting-logs/fluent-bit-collector.yaml`

## Additional Info
**Additional context**
N/A

**Install information:**
N/A

### PR DESCRIPTION
**Pull request by lamw**
Fixes #4315 
Signed-off-by: William Lam <wlam@vmware.com>

## Proposed Changes 

- Add correct URL for `fluent-bit-collector.yaml`

### CODE REVIEW

**Comment by lamw** [comment]
@googlebot I signed it!

**Comment by lamw** [comment]
@googlebot I signed it!

**Comment by abrennan89** [comment]
@thisisnotapril something weird happening here it looks like, can you help @lamw please?

**Comment by lamw** [comment]
@abrennan89 @thisisnotapril Not sure whats going on. I just confirmed CLA has been signed through our internal process and email has been added to CLA Google Group .... perhaps you can check and let me know how to proceed further

**Comment by thisisnotapril** [comment]
overriding the CLA bot check; confirmed CLA on file

**Comment by abrennan89** [comment]
@lamw are you still working on this one?

**Comment by lamw** [comment]
This seems to be resolved now. Closing PR

**Pull request closed without merging**
