### PR TITLE
Fix telemetry Dockerfile and typo

### PR DESCRIPTION
**Pull request by savitaashture**
Fixes https://github.com/knative/docs/issues/1294

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by sebgoa** [comment]
/lgtm

We need to fix the CLA issue

content is good, it would be nice to know which issue this fixes and if there are no open issues for it , you could open one.

thanks for the PR

**Comment by savitaashture** [comment]
Signed from the email which is configured in the git commits.

**Comment by savitaashture** [comment]
@sebgoa 

Thank you.

Fixed CLA issue.

There was no issue for this PR so created new one 
https://github.com/knative/docs/issues/1294

**Comment by sebgoa** [comment]
the three fixes are:

/lgtm

but they fix three different issues (e.g the buildback cnb url, and a lack of cloning in the grpc example).

/retest

I would encourage you to fix one issue with a PR (next time).

**Comment by savitaashture** [comment]
Thank you @sebgoa 

I will take care next time.

**Pull request merged**
