### PR TITLE
chore: remove front matter from blog template

### PR DESCRIPTION
**Pull request by lance**
Hugo is no longer used, so this is not needed.

Fixes: https://github.com/knative/docs/issues/5099

/kind cleanup

### CODE REVIEW

**Comment by dprotaso** [comment]
Should we remove it from existing blog pages?

ie. https://deploy-preview-5583--knative.netlify.app/blog/releases/announcing-knative-v1-7-release/ ?

**Comment by lance** [comment]
> Should we remove it from existing blog pages?
> 
> ie. https://deploy-preview-5583--knative.netlify.app/blog/releases/announcing-knative-v1-7-release/ ?

Sure - I'll do that

**Comment by dprotaso** [comment]
The nav is a bit off - 
Screenshot 2023-05-30 at 15 23 21

**Comment by lance** [comment]
@dprotaso what do you mean? It looks the same as knative.dev as far as I can tell (although I made it consistently prefixed with "Announcing knative"). Here is the published nav 
image

**Comment by dprotaso** [comment]
Is it me or is 1.6 etc missing the period in the middle ?

**Comment by dprotaso** [comment]
The PR deployment is on the right - and it seems like it's making it worse
Screenshot 2023-05-31 at 11 26 10

**Comment by dprotaso** [comment]
maybe we do need the front matter?

**Comment by lance** [comment]
> maybe we do need the front matter?

I just pushed a commit that uses front matter on the 1.9 release and it's definitely better than without.

image

**Comment by dprotaso** [comment]
> But it seems to me like the release announcements are better when front matter is used. I'm inclined to revert the changes to the release announcements, and to add front matter to the handful of them which did not use it (1.6 and up). WDYT?

I agree

**Comment by lance** [comment]
> > But it seems to me like the release announcements are better when front matter is used. I'm inclined to revert the changes to the release announcements, and to add front matter to the handful of them which did not use it (1.6 and up). WDYT?
> 
> I agree

OK - I've done this. There are two articles in the Releases blog posts that I think should retain the new style of heading/title and be moved to the Articles blog posts, since they differ in form and style from all of the other release posts.

**Comment by dprotaso** [comment]
/lgtm
/approve

> Also, it's interesting - I realized when looking at these two outliers that the first top-level heading is used for the menu nav, and set in the meta tags. But there is no author information in meta tags, and the description in the tag is just "Knative Blog".

Wanna make a follow up issue?

**Comment by lance** [comment]
> /lgtm /approve
> 
> > Also, it's interesting - I realized when looking at these two outliers that the first top-level heading is used for the menu nav, and set in the meta tags. But there is no author information in meta tags, and the description in the tag is just "Knative Blog".
> 
> Wanna make a follow up issue?

https://github.com/knative/docs/issues/5588

**Pull request merged**
