### PR TITLE
Update first-trigger.md

### PR DESCRIPTION
**Pull request by jjasghar**
Fixing some formatting.

### CODE REVIEW

**Comment by jjasghar** [comment]
Sanity check on https://deploy-preview-4367--knative.netlify.app/development/getting-started/first-trigger it looks like it is correct now.

**Comment by snneji** [comment]
@jjasghar have you signed the CLA? The PR cannot merge until it has the `cla: yes` label.

**Comment by jjasghar** [comment]
I'll double check. sorry :-O

**Comment by jjasghar** [comment]
I believe i just signed the CLA.

**Comment by csantanapr** [comment]
Thank you for the contribution @jjasghar 👋 
Did you sign the CLA with the same email you use author on the commit? `awesome@ibm.com`

**Comment by jjasghar** [comment]
ah damn, it was jja@ibm.com i think. :-/ can i add awesome@ibm.com somehow? (GitHub has it as one of my emails....)

**Comment by csantanapr** [comment]
You can sign the CLA again with another email, I think that's what I did it was a long time ago

**Comment by csantanapr** [comment]
Or replace the commit force push and use a different email

**Comment by julz** [comment]
Hey @jjasghar - I think since you're with IBM you should be covered by the corporate CLA and shouldn't need to sign the individual one (as far as I remember, anyway). I'll dig up the intranet page for signing up and send it to you on IBM slack in a minute.

**Comment by chizhg** [comment]
@googlebot

**Comment by jjasghar** [comment]
yay! ok, that should be good now. Sorry about all this.

**Pull request merged**
