### PR TITLE
added Linkedln page link

### LINKED ISSUE #5972: We should add our LinkedIn page link to follow us section of our website
**Describe the change you'd like to see**
In the Follow us section we should have the link to our Linkedin page as well
https://www.linkedin.com/company/knative
**Additional context**

### PR DESCRIPTION
**Pull request by shivamgupta2020**
Fixes #5972 

## Proposed Changes 

- Added Linkedln page link in Follow us section.
image

### CODE REVIEW

**Review by aliok — CHANGES_REQUESTED** [review]
Can you please revert the formatting changes that are not relevant to the task?

Also, can you add some spacing between X and LinkedIn logos?

**Comment by shivamgupta2020** [comment]
> Can you please revert the formatting changes that are not relevant to the task?
> 
> Also, can you add some spacing between X and LinkedIn logos?

@aliok I have updated the linting of code and add some space between the logo.
Updated Look - 
Screenshot from 2024-05-29 04-47-02

**Comment by shivamgupta2020** [comment]
> I think it will look much better if we split the logos section into 4 columns. One column for each logo.
> 
> Also while hovering it shows the logo into greenish gradient which can be made better if we change the color into the actual logo color (egs: black for Twitter logo) or we can also change the logo color into color matching Knative logos while hovering. 
> 
> cc: @aliok @shivamgupta2020  

Hi @DhairyaMajmudar ,
I think splitting the section into four parts isn't necessary since LinkedIn and Twitter perform the same task. Also, the color change on hover hasn't been decided by the UX team yet, so we should hold off on that for now. However, I like your suggestion to use the actual logo color on hover.

**Comment by aliok** [comment]
@shivamgupta2020 

If you remove the irrelevant formatting changes, we can merge this PR. Thanks!

**Comment by shivamgupta2020** [comment]
> @shivamgupta2020
> 
> If you remove the irrelevant formatting changes, we can merge this PR. Thanks!

@aliok, I've reverted the formatting changes. Please review it on your machine.

**Comment by aliok** [comment]
@shivamgupta2020 

When I check https://github.com/knative/docs/pull/5976/files I see they are still there.

**Comment by shivamgupta2020** [comment]
@aliok, I've reverted the formatting changes. Please review it.

**Comment by nainaz** [comment]
Looks good to me. I like the space between X and in. 
Maybe it is just my eyes, in looks smaller like this :) 
Thank you again @shivamgupta2020!

**Comment by aliok** [comment]
Thanks @shivamgupta2020 

It looks great.

About the previous comments about colors, etc. Let's address them separately as we need to change those everywhere.

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
