### PR TITLE
Fix 'verion' mispelling in check-install-version

### PR DESCRIPTION
**Pull request by joaedwar**
Relates to [Issue #1119](https://github.com/knative/docs/issues/1119)

Fixes #(1119 )

## Proposed Changes

- 'verion' typo fix
- removed unnecessary article 'a' in line 33

### CODE REVIEW

**Comment by samodell** [comment]
@chaodaiG  Any idea why the docs-integration-tests are failing here? I'm seeing this in the error logs:

```I0401 16:11:28.802] 2019/04/01 16:11:28 main.go:312: Something went wrong: failed to prepare test environment: --provider=gke boskos failed to acquire project: resource not found
I0401 16:11:28.804] Test subprocess exited with code 1
I0401 16:11:50.832] ERROR: (gcloud.compute.target-pools.list) Some requests did not succeed:
I0401 16:11:50.833]  - Required 'compute.targetPools.list' permission for 'projects/knative-tests'
I0401 16:11:50.833] 
I0401 16:12:12.552] ERROR: (gcloud.compute.target-pools.list) Some requests did not succeed:
I0401 16:12:12.553]  - Required 'compute.targetPools.list' permission for 'projects/knative-tests'
I0401 16:12:12.553] 
I0401 16:12:12.636] Artifacts were written to /workspace/_artifacts
I0401 16:12:12.636] Test result code is 1
I0401 16:12:12.639] ==================================
I0401 16:12:12.640] ==== INTEGRATION TESTS FAILED ====
I0401 16:12:12.640] ==================================
W0401 16:12:12.669] Run: ('/workspace/./test-infra/jenkins/../scenarios/../hack/coalesce.py',)
E0401 16:12:12.669] Command failed
I0401 16:12:12.669] process 635 exited with code 1 after 0.9m
E0401 16:12:12.669] FAIL: pull-knative-docs-integration-tests
I0401 16:12:12.670] Call:  gcloud auth activate-service-account --key-file=/etc/test-account/service-account.json
W0401 16:12:13.117] Activated service account credentials for: [prow-job@knative-tests.iam.gserviceaccount.com]
I0401 16:12:13.177] process 848 exited with code 0 after 0.0m
I0401 16:12:13.178] Call:  gcloud config get-value account
I0401 16:12:13.498] process 860 exited with code 0 after 0.0m
I0401 16:12:13.498] Will upload results to gs://knative-prow/pr-logs using prow-job@knative-tests.iam.gserviceaccount.com
I0401 16:12:13.498] Upload result and artifacts...
I0401 16:12:13.498] Gubernator results at https://gubernator.k8s.io/build/knative-prow/pr-logs/pull/knative_docs/1122/pull-knative-docs-integration-tests/1112749193161609216
I0401 16:12:13.499] Call:  gsutil ls gs://knative-prow/pr-logs/pull/knative_docs/1122/pull-knative-docs-integration-tests/1112749193161609216/artifacts
W0401 16:12:14.520] CommandException: One or more URLs matched no objects.
E0401 16:12:14.650] Command failed```

**Comment by chaodaiG** [comment]
@samodell , this is a problem happening in every knative repo right now, it's tracked here: https://github.com/knative/test-infra/issues/638
And Stephen is actively working on it

**Comment by samodell** [comment]
Thanks for the info, @chaodaiG !

**Pull request merged**
