### PR TITLE
Update the email to be relevant

### PR DESCRIPTION
**Pull request by vagababov**
I kept Dan since he's still the author of the latest version. And fixed
Evan't email to be a routable one.

/assign @evankanderson mattmoor

### CODE REVIEW

**Comment by evankanderson** [comment]
I'm wondering if we should move this to an appendix, and include Doug as well.

**Comment by vagababov** [comment]
Either works.

**Comment by vagababov** [comment]
Sorted and added doug and put in the end.

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
