### PR TITLE
Add SASL for KafkaSource docs

### PR DESCRIPTION
**Pull request by abrennan89**
Fixes https://github.com/knative/docs/issues/3583

- Added SASL docs
- Moved "clean up" to end of section (source deletion should be after all the other options)

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
Thanks!

**Comment by pierDipi** [comment]
GH actions failures seem unrelated

**Comment by abrennan89** [comment]
@pierDipi it seems like it broke the page merging this https://knative.dev/development/eventing/sources/kafka-source/ 😖

**Pull request merged**
