### PR TITLE
fixing Apache Kafka Event Source and Verify Sections

### PR DESCRIPTION
**Pull request by Shashankft9**
Fixes https://github.com/knative/docs/issues/2520

## Proposed Changes 

- Updating the log captures since they have changed in recent releases, also adding some steps to see these logs.

### CODE REVIEW

**Comment by Shashankft9** [comment]
@evankanderson hey just noticed a small typo in the commit, mistake from my side, here: https://github.com/knative/docs/pull/2530/files#diff-57cd3f3beea2fe9c34f6cb8cec8a4f80R188

Can we revert this commit and I'll commit the updated one?

**Comment by evankanderson** [comment]
It's probably easier to send a new PR for the typo; I'm currently iterating on PRs so if you get it in in the next 40 minutes I can probably approve it ASAP.

**Comment by Shashankft9** [comment]
sure, on it.

**Pull request merged**
