### PR TITLE
fix helloworld-go filename

### PR DESCRIPTION
**Pull request by Gekko0114**
Fixes hello-world-go's filename's typo

## Proposed Changes 

- In [README.md](https://github.com/knative/docs/blob/main/code-samples/eventing/helloworld/helloworld-go/README.md), helloworld.go and eventschemas.go files are used. But instead of eventschemas.go, eventchemas.go exists in this repository. Fixed this filename's typo.

### CODE REVIEW

**Comment by Gekko0114** [comment]
Hi @lance ,
Thank you for this repository, this repository is very helpful.
And I would appreciate it if you approved my PR.
Thanks

**Review by lance — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
