### PR TITLE
Fix comment indentation

### PR DESCRIPTION
**Pull request by RichardJJG**
"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-
-
-

### CODE REVIEW

**Comment by RichardJJG** [comment]
Assigned @snneji for review

**Comment by abrennan89** [comment]
@RichardJJG I think I already fixed this yesterday which is why it's saying to rebase: https://knative.dev/development/install/any-kubernetes-cluster/

**Comment by snneji** [comment]
Hi @RichardJJG. Maybe this PR can be closed since the issue was fixed by @abrennan89?

**Comment by RichardJJG** [comment]
@snneji, @abrennan89,  yep, thanks, I've closed it.

**Pull request closed without merging**
