### PR TITLE
Changed filename from serving.yaml to serving-core.yaml in upgrade docs

### LINKED ISSUE #2669: Upgrading your installation(docs/install/upgrade-installation.md)
Since current version([v0.16.0](https://github.com/knative/serving/releases/)) does not release serving.yaml anymore, the [Performing the upgrade](https://knative.dev/docs/install/upgrade-installation/#performing-the-upgrade) part needs improving.

### PR DESCRIPTION
**Pull request by mpetason**
Fixes #2669 

## Proposed Changes 

- It looks like we moved from serving.yaml to serving-core.yaml so I modified the upgrade file path

### CODE REVIEW

**Comment by nak3** [comment]
Although this is correct fix, the upgrade doc still misses "how to upgrade the plugins". As far as I know, the moving serving.yaml to serving-core.yaml dropped some plugin resources like net-istio, etc.

**Comment by dprotaso** [comment]
/hold

good point @nak3 - we'll probably want a blurb about that

**Comment by dprotaso** [comment]
actually - we could do that separately and unblock this

/unhold

**Comment by nak3** [comment]
> actually - we could do that separately and unblock this

Yes, I think it is a little bit complicated task :cry:  We should do it in separated PR.

**Pull request merged**
