### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by jamesalbert**
## Proposed Changes

* guides -> guide

### CODE REVIEW

**Comment by jamesalbert** [comment]
whoa there google

**Comment by labadav** [comment]
Thank you for the PR, @jamesalbert , please take a look and see if you can get your CLA signed. The Googlebot left a comment with instructions above.

**Comment by labadav** [comment]
Since no updates here, I created a PR to fix the typo here:
https://github.com/knative/docs/pull/335

**Comment by labadav** [comment]
Closing this one

**Pull request closed without merging**
