### PR TITLE
Copy VENDOR-LICENSE over from eventing repo

### LINKED ISSUE #488: Broken VENDOR-LICENSE symlinks cause build to fail in sample
When following instructions in k8s-events sample the docker image build fails due to VENDOR-LICENSE symlinks in /vendor/github.com/knative/eventing/cmd packages pointing into a non-existent third_party directory.

### PR DESCRIPTION
**Pull request by gsf**
This file is referenced by symlinks in eventing/cmd. Fix #488

### CODE REVIEW

**Comment by gsf** [comment]
Alternatively, eventing/cmd could be removed, as all it contains are the kodata files. Do they need to be vendored?

**Comment by mattmoor** [comment]
This is generated and generally in flux, so we shouldn't update it manually.

Does running `./hack/update-deps.sh` fix this?

**Comment by mattmoor** [comment]
@n3wscott can you help out here?

**Comment by gsf** [comment]
Running `./hack/update-deps.sh` does not fix this.

**Comment by mattmoor** [comment]
I see, it looks like `dep` is too clever and prunes `third_party/`, but not the things that link there.

Does adding a `.dockerignore` file for this sample with `*/kodata/*` help?

**Comment by gsf** [comment]
Looks like `hack/update-deps.sh` in the eventing repo relies on `update_licenses` to generate the VENDOR-LICENSE:

https://github.com/knative/eventing/blob/0191960e6bf7cc6d4b99d3e486b109d558f47d64/hack/update-deps.sh#L34-L35

**Comment by n3wscott** [comment]
I think the correct thing to do is just remove the cmd dirs from eventing: https://github.com/knative/docs/pull/490

**Pull request closed without merging**
