### PR TITLE
fix broken links.

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

- fix broken links to various eventing sources.

### CODE REVIEW

**Comment by rgregg** [comment]
This PR really changes the formatting of the document. Do we need to make those changes, or could we just fix the broken links?

**Comment by samodell** [comment]
@rgregg  When I preview the rendered changes, this looks fine to me -- just seems like some words have changed within the table, and the links have been updated. Can you point to what formatting changes you were concerned about?

**Comment by lionelvillard** [comment]
the diff looks weird but the rendering is ok.

**Comment by rgregg** [comment]
The diff is what I was looking at, where the formatting of the table has changed dramatically (looks like maybe an auto-table formatter was used). My big concern is that the semantics of the table format changed (e.g. rows don't start and end with |) and that might cause issues for rendering engine used on the website vs. how GitHub renders the content.

**Comment by lionelvillard** [comment]
readme.md is generated, so maybe the generator has changed?

**Comment by rgregg** [comment]
Good point, let's not block on my feedback :)

**Pull request merged**
