### PR TITLE
Add jonatasbaldin in docs-reviewers

### PR DESCRIPTION
**Pull request by jonatasbaldin**
Fixes #issue-number or description of the problem the PR solves

## Proposed Changes 
- Add myself as a doc reviewer ✨

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
@evankanderson rebased ✨

**Comment by evankanderson** [comment]
It looks like you have conflict markers you'll need to clean up.

**Comment by jonatasbaldin** [comment]
🤦

removed :)

**Comment by evankanderson** [comment]
The number of times I've done `git commit -m 'Oops, fixed' && git push origin` without actually including the file in the commit is ... high.

😬

**Pull request merged**
