### PR TITLE
Document contentMode for KafkaSink

### LINKED ISSUE #4400: Document content mode for KafkaSink
## What is changing? (Please include as many details as possible.)

KafkaSink has a `contentMode` field that specifies the content mode
of the output CloudEvent.
Possible values are `structured` or `binary`.

## How will this impact our users?

No impact, this feature has already been released many releases ago.

## In what release will this take happen (to the best of your knowledge)?
Ex. v0.2-v0.3

This feature has already been released many releases ago.

## Additional info

- Page to update https://knative.dev/docs/developer/eventing/sinks/kafka-sink/
- Types https://github.com/knative-sandbox/eventing-kafka-broker/blob/4c7f76d726a9c41a806106a397419bfa89a80122/control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_types.go#L83-L95

/kind eventing

### PR DESCRIPTION
**Pull request by pierDipi**
Fixes #4400 

## Proposed Changes 

- Document contentMode for KafkaSink

### CODE REVIEW

**Review by abrennan89 — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
PR stuck :confused: 

```
Pending — Not mergeable. Retesting: pull-knative-docs-build-tests pull-knative-docs-unit-tests
```

/test pull-knative-docs-unit-tests
/test pull-knative-docs-build-tests

**Pull request merged**
