### PR TITLE
Fix #1239 - add a note on how docs are built

### LINKED ISSUE #1239: How to build the docs website (knative.dev) locally?
**Describe the change you'd like to see**
Instructions on how to build the docs locally.

**Additional context**
I noticed some formatting errors and wanted to debug them but I can't debug without being able to build the docs locally.

### PR DESCRIPTION
**Pull request by aliok**
Fixes #1239 

## Proposed Changes
- Note how the docs in this repo are built and then published to <https://knative.dev>

### CODE REVIEW

**Comment by aliok** [comment]
I signed the CLA now

**Comment by sebgoa** [comment]
considering there is no README in https://github.com/knative/website I think we need to expand on how to actually do it.

**Comment by RichieEscarez** [comment]
Thanks @aliok! But Im actually just going to close this since Im in the process of writing up the site maintainer docs which will include these types of cross linking.

**Comment by aliok** [comment]
@RichieEscarez no problem. What's important is documenting how the docs are built.
If you already have a ticket/PR, could you please ping me? I would like to help with verifying the instructions in site maintainer docs.

**Comment by aliok** [comment]
@RichieEscarez 

> If you already have a ticket/PR, could you please ping me? I would like to help with verifying the instructions in site maintainer docs.

Well, ticket https://github.com/knative/docs/issues/1239 is OK to reuse for this IMO.

**Pull request closed without merging**
