### PR TITLE
fix broken links (from link checking report tool testing)

### PR DESCRIPTION
**Pull request by RichieEscarez**
contributes to fixing items in #1750

/cc @adrcunha  @eallred-google

### CODE REVIEW

**Comment by adrcunha** [comment]
The link checker failed because the script isn't available. Looks like this PR is based on an old commit. Any chance you can rebase, Richie?

**Comment by RichieEscarez** [comment]
> The link checker failed because the script isn't available. Looks like this PR is based on an old commit. Any chance you can rebase, Richie?

I rebased and it failed again. This is against the "release-0.10" branch (vs. "master") and I don't think we checked in that script to this branch?

**Comment by adrcunha** [comment]
Good catch, I didn't realize that this is not the master branch. Indeed, unless we check in the presubmit script (do we want to?) the job will fail.

**Comment by RichieEscarez** [comment]
> Good catch, I didn't realize that this is not the master branch. Indeed, unless we check in the presubmit script (do we want to?) the job will fail.

Is there additional work associated with adding that script to the `release-0.10` branch? I would be nice to have it but I dont think it warrants any extra effort on top of just opening a PR to copy that file there.

On that note, will there be any additional "release" work needed when we cut/create a release branch for an archived docs version (ie. for the "release-0.11" branch)?

**Comment by adrcunha** [comment]
> > Good catch, I didn't realize that this is not the master branch. Indeed, unless we check in the presubmit script (do we want to?) the job will fail.
> 
> Is there additional work associated with adding that script to the `release-0.10` branch? It would be nice to have it but I dont think it warrants any extra effort on top of just opening a PR to copy that file there.

No, it's just a cherrypick PR.

> On that note, will there be any additional "release" work needed when we cut/create a release branch for an archived docs version (ie. for the "release-0.11" branch)?

No, at that point the script will be already in the branch.

**Pull request merged**
