### PR TITLE
Fix knative-monitoring namespace and accessing-logs URL

### PR DESCRIPTION
**Pull request by vdemeester**
The namespace is `knative-monitoring` instead of `monitoring`

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
Hum, elsewhere in the docs, there is reference to `monitor` namespace too… I'm gonna check the serving yaml to deploy it to see which namespace there on

**Comment by bbrowning** [comment]
The integration test failure was unrelated to this change and due to an issue impacting all PRs in the docs repo that is now fixed.

/test pull-knative-docs-integration-tests

**Pull request merged**
