### PR TITLE
Update link to camel.yaml

### LINKED ISSUE #3102: Apache Camel source(docs/eventing/samples/apache-camel-source/index.md)
## Expected Behavior

The Camel artifacts have moved to [eventing-camel](https://github.com/knative-sandbox/eventing-camel/releases) from [eventing-contrib v0.18.4](https://github.com/knative/eventing-contrib/releases/tag/v0.18.4). So the reference in [Prerequisites](https://knative.dev/docs/eventing/samples/apache-camel-source/#prerequisites) needs to be updated.

## Actual Behavior

The link in the documentation points to [eventing-contrib](https://github.com/knative/eventing-contrib/releases) which no longer hosts camel sources.

## Steps to Reproduce the Problem

1. Apache Camel source, Prerequisites, [Step 3](https://knative.dev/docs/eventing/samples/apache-camel-source/#prerequisites)
1. It says __Install the Camel Source from the `camel.yaml` in the [Eventing Sources release page](https://github.com/knative/eventing-contrib/releases):__
1. Current releases of Eventing Sources do not contain `camel.yaml`.

### PR DESCRIPTION
**Pull request by abrennan89**
Fixes #3102

### CODE REVIEW

**Review by vaikas — APPROVED** [review]
/lgtm

**Comment by abrennan89** [comment]
🤷🏻‍♀️ no CP I guess 😅

**Pull request merged**
