### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by trent-abc**
Fixes two broken links to certmanager.io docs

### CODE REVIEW

**Comment by dprotaso** [comment]
/ok-to-test
@trent-abc you'll need to sign the CLA

**Comment by trent-abc** [comment]
I'll pass after reading the CLA. Feel free to copy my code in another PR

**Comment by dprotaso** [comment]
As part of transitioning to the CNCF we're revisiting this soon

Curious if you have opinions on - https://lfx.linuxfoundation.org/tools/easycla/
or 
https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin

**Comment by trent-abc** [comment]
I can't speak for others but I would contribute under DCO. I was wary of signing the CLA due to the "full name and email address included and maintained indefinitely" disclaimer at the top.

**Pull request closed without merging**
