### PR TITLE
Fix typos in the sample yaml file

### PR DESCRIPTION
**Pull request by xclud**
Fix typos in the sample yaml file.

### CODE REVIEW

**Comment by omerbensaadon** [comment]
@xclud thank you so much for your contribution!

**Comment by omerbensaadon** [comment]
If you're interested in getting more involved, join us in the Knative Slack at https://slack.knative.dev/! Message me and I can help direct you :)

**Comment by xclud** [comment]
@omerbensaadon Indeed i would like to join you guys. I messaged you. Thanks for the invitation.

**Pull request merged**
