### PR TITLE
Correct link for Knative Serving documentation

### PR DESCRIPTION
**Pull request by MandarJKulkarni**
"Fixes #issue-number" or "Add description of the problem this PR solves"

## Proposed Changes 

-
-
-

### CODE REVIEW

**Comment by nak3** [comment]
Hi @mpetason @MandarJKulkarni, I think it is better to fix this in main branch first and cherry-pick for release-0.21 branch.

**Comment by mpetason** [comment]
@nak3 good catch, I didn't look at the branch. I agree.

**Comment by MandarJKulkarni** [comment]
I have created PR for master branch 
https://github.com/knative/docs/pull/3383

**Comment by csantanapr** [comment]
/close

lets do it with cherry pick

**Pull request closed without merging**
