### PR TITLE
Remove-hugo-community

### LINKED ISSUE #4515: Take down Hugo community site
After #4394 has been completed, take down the Hugo version of the community site so that only the MkDocs site is available to users.

### Tasks

- Make changes to the build scripts
- Remove the [`community`](https://github.com/knative/docs/tree/main/community) folder

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #4515

### CODE REVIEW

**Comment by csantanapr** [comment]
When this lands we don't use the website repo and we can archive it.

**Review by snneji — APPROVED** [review]
/lgtm

**Comment by snneji** [comment]
@csantanapr does this need to be cherry picked back to 0.25? I imagine at least the community folder can go from those versions.

**Pull request merged**
