### PR TITLE
Remove outdated samples

### PR DESCRIPTION
**Pull request by vaikas-google**
## Proposed Changes

* Remove old samples and once new Github Source is working, add a sample here for it.
* https://github.com/knative/eventing-sources/issues/78

### CODE REVIEW

**Comment by alexander-alvarez** [comment]
@vaikas-google the README still references some of these files https://github.com/knative/docs/blame/master/eventing/README.md#L82

**Comment by alexander-alvarez** [comment]
Also out of curiosity for the uninitiated, where can I read about the replacement (or relocation) of Kafka buses?

**Comment by matzew** [comment]
@alexander-alvarez they are not yet there.

For instance that is a PR now for a Kafka Channel Provisioner:

https://github.com/knative/eventing/pull/468

**Pull request merged**
