### PR TITLE
Update kube-version to 1.10.7

### PR DESCRIPTION
**Pull request by aslom**
```
knative1 $ ibmcloud cs cluster-create --name=$CLUSTER_NAME \
>   --zone=$CLUSTER_ZONE \
>   --kube-version=1.10.3 \
>   --machine-type=b2c.4x16 \
>   --workers=3
Creating cluster...
FAILED

A previous patch was specified. Only the most recent patch for a particular minor version can be specified during cluster-create.  To list supported Kubernetes versions, run 'ibmcloud ks kube-versions'. (E0156)
Incident ID: 5533234a-df08-478b-b298-ab0ddbe67dfe
knative1 $ ibmcloud ks kube-versions
OK
Version
1.8.15 (deprecated, unsupported in 9 days)
1.9.10
1.10.7 (default)
1.11.2
To assess the differences across versions, see https://console.bluemix.net/docs/containers/cs_versions.html#cs_versions.
```

After change:

```
knative1 $  ibmcloud cs cluster-create --name=$CLUSTER_NAME \
>       --zone=$CLUSTER_ZONE \
>       --kube-version=1.10.7 \
>       --machine-type=b2c.4x16 \
>       --workers=3
Creating cluster...
OK
```

Fixes #(issue-number)

## Proposed Changes

* 
* 
*

### CODE REVIEW

**Comment by aslom** [comment]
@labadav I should be now added to IBM CLA - let me know if it is not showing up.

**Comment by uwefassnacht** [comment]
With the proposed change, we will probably have the same issue some time from now (once v.1.10.7 becomes no longer supported). 

Instead, I would presume that future default versions will be compatible with knative and therefore we should not include the version number at all (omitting the `--kube-version` option) from the command.

**Comment by aslom** [comment]
@uwefassnacht sounds good to me - do you want me to test it?

**Comment by uwefassnacht** [comment]
@aslom yes please.

**Comment by aslom** [comment]
Tested without --kube-version and it worked:

```
knative1 $ ibmcloud cs vlans --zone $CLUSTER_ZONE
OK
ID        Name   Number   Type      Router         Supports Virtual Workers
2439461          883      private   bcr02a.dal13   true
2439459          857      public    fcr02a.dal13   true
knative1 $ export PRIVATE_VLAN_ID=2439461
knative1 $ export PUBLIC_VLAN_ID=2439459
knative1 $ ibmcloud cs cluster-create --name=$CLUSTER_NAME \
>   --zone=$CLUSTER_ZONE \
>   --machine-type=b2c.4x16 \
>   --workers=3 \
>   --private-vlan $PRIVATE_VLAN_ID \
>   --public-vlan $PUBLIC_VLAN_ID
Creating cluster...
OK

knative1 $ ibmcloud cs clusters | grep $CLUSTER_NAME
knative2   98ce7f93b61f4aecbe631e9f4fcf243c   normal   18 minutes ago   3         Dallas     1.10.8_1524
```

**Comment by aslom** [comment]
Anything else needed?

**Pull request merged**
