### PR TITLE
docs(code-samples/go): fix indentation for code and package missing

### PR DESCRIPTION
**Pull request by maxgio92**
This PR fixes small documentation format for Golang sample code.

### CODE REVIEW

**Comment by psschwei** [comment]
@maxgio92  Thanks for the PR!

Seems to be an issue with the remote reference:

```bash
$ git fetch upstream pull/5362/head:pr-5362 --force
fatal: couldn't find remote ref pull/5362/head
```

Seeing a similar error in netlify that's causing the deploy preview to fail (`git ref pull/5362/head does not exist or you do not have permission`)

FWIW, I'm able to access https://github.com/maxgio92/docs/tree/docs/code-samples-go , so not exactly sure what's causing the problem here...

**Comment by maxgio92** [comment]
Is there something I can do @psschwe? I just rebased on `main` branch`.

**Comment by psschwei** [comment]
It looks like the indentation was fixed in #5443 ... were there things missed in that PR that still need to be fixed?

**Comment by maxgio92** [comment]
Don't think so @psschwei. Actually the diff shows one against older head :)
I think we can close this

**Comment by maxgio92** [comment]
Thanks

**Pull request closed without merging**
