### PR TITLE
Update getting-started/clean-up.md

### PR DESCRIPTION
**Pull request by speza**
Noticed what looks like some typos in the `docs/getting-started/clean-up.md` file.

## Proposed Changes 
- Fixed typos in `docs/getting-started/clean-up.md`

### CODE REVIEW

**Comment by snneji** [comment]
Hi @speza, thanks for the PR! It seems that the CLA test is failing. Before we can merge your PR, can you [sign the CLA](https://github.com/knative/docs/pull/4580/checks?check_run_id=4525591153). Make sure you sign it using the same email address you used for GitHub to make the commit.

**Comment by speza** [comment]
Apologies, that should be done now @snneji 👍

**Comment by speza** [comment]
@snneji not sure why that retest didn't pass on the CLA. I have signed it, used the correct email and set the username to `speza`.

**Comment by snneji** [comment]
Hi @speza, I'll try to find out what the problem is.

**Comment by csantanapr** [comment]
I reran the cla job o github and that fixed the issue

**Comment by csantanapr** [comment]
Welcome @speza and thank you for the contribution 🚀

**Comment by snneji** [comment]
Thanks for fixing this. 🙂
/approve
/lgtm

**Pull request merged**
