### PR TITLE
Cherry pick a few commits that were erroneously made directly into release-0.19

### PR DESCRIPTION
**Pull request by arturenault**
- Remove prometheus addon from Istio installation instructions (#3096)
- Add docs on mTLS and Istio authorization policy (#3118)
- Fix typo in istio authorization docs (#3120)

### CODE REVIEW

**Comment by arturenault** [comment]
@tcnghia @markusthoemmes ping :)

**Review by abrennan89 — APPROVED** [review]
/lgtm
/hold
@markusthoemmes please remove the hold when you're able to take a look and approve this

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve
/unhold

**Pull request merged**
